knative/func

client.go, cmd/create.go, cmd/delete.go, cmd/describe.go, cmd/root.go, cmd/version.go, config.go, function.go, go.mod, kubectl/deployer.go, progress/progress.go, prompt/prompt.go, prompt/prompt_test.go
Adds a simple progress indicator which writes a progress spinner, current steps and message.  A simple line is written if in verbose mode so as not to interfere with standard output, and nothing is written if nonverbose and a noninteractive terminal.  Fixes #11
=> Progress indicator

appsody/initializer.go, cmd/completion.go, cmd/completion_util.go, cmd/create.go, cmd/delete.go, cmd/describe.go
Add shell completions from @matejvasek
=> Shell comp

cmd/update.go, go.mod, knative/updater.go
=> feat: remove dependency on `kn` binary

.github/workflows/releases.yaml
This commit adds automated releases to GitHub Releases when a release tag is pushed.
Fixes: https://github.com/boson-project/faas/issues/32
=> actions: add automated releases of faas binary

Makefile
Adding multiple platforms to the makefile.
=> Adding multiple platforms to Makefile

cmd/list.go, knative/lister.go
=> The `list` sub-command uses namespace.

client.go, cmd/create.go, function.go
=> fix: image override

client.go, cmd/completion_util.go, cmd/delete.go, knative/remover.go
There was namespace issue, there was hard-coded `faas` namespace.
=> fix: delete command

client.go, cmd/completion_util.go, cmd/delete.go, knative/describer.go, knative/remover.go
This PR includes the two fix commits from @matejvasek that landed on `develop` but not `main` prior to https://github.com/boson-project/faas/commit/8a60c5e0c44d28d2ff085e56299217e05e408df8
=> fix: describe works without Kn Eventing and delete command 

go.mod, go.sum
=> chore: update `pack` dep version

.github/workflows/pull_requests.yaml, Makefile, function_unit_test.go, templates_test.go
=> chore: run GH actions on Windows and macOS

cmd/build.go, cmd/create.go, cmd/delete.go, cmd/deploy.go, cmd/describe.go, cmd/list.go, cmd/update.go, config.go, docs/commands.md
Fixes: https://github.com/boson-project/faas/issues/142
=> chore: rename .faas.yaml to faas.yaml

.gitignore
=> chore: ignore vscode files

cmd/build.go, cmd/delete.go, cmd/describe.go, cmd/run.go, docs/commands.md
=> chore: commands are checking that Function is initialized

go.mod, go.sum
- This reverts commit cc5435a84bb3a020a903edf02bd0e1f964d82beb.
- Points knative/client at v0.17.2
=> Point knative/client at v0.17.2

cmd/create.go, cmd/deploy.go, cmd/root.go, cmd/run.go, config.go, docker/runner.go, function.go, knative/deployer.go
=> Allow set envvars

docs/developers_guide.md
Encountered while reading dev guide.
=> Add link to CLI installation in developer guide

client.go, cmd/describe.go, knative/deployer.go, knative/describer.go, knative/remover.go
Outputs of commands were quite incositent, trying to fix that.
=> chore: tweak output & verbose messages

knative/deployer.go
Until the next release of Quarkus in November, we'll need to have some special
checks so that we don't add these probes to Quarkus based functions. In the
meantime, we can at least set the liveness and readiness endpoints on the
Node.js/Go functions to /health/liveness and /health/readiness respectively.
Fixes: https://github.com/boson-project/faas/issues/169
=> feat: add health probes to node & go service

client.go, client_test.go, config.go, docker/pusher.go, docker/runner.go, function.go, go.mod, knative/deployer.go, mock/pusher.go
Using image Digest in the Knative Service. Haven't moved to Docker Go SDK, because with this library it is [quite hard ](https://github.com/moby/moby/issues/39377#issuecomment-503589708) to use some authentication 💩 
We can try to migrate to this lib post Dev Preview. Issue created: https://github.com/boson-project/faas/issues/179
Fixes: #141 
Fixes: #140
=> src: use image digest

function.go, function_test.go
=> fix: image parsing

client.go, client_test.go, cmd/init.go
I did not implement a prompt if the user doesn't choose. It seems odd to me that a flag would be required. I'm happy to discuss this, however.
Fixes: https://github.com/boson-project/faas/issues/191
=> feat: change default runtime to Node.js HTTP

knative/deployer.go, knative/lister.go
=> src: add boson.dev/runtime label to kservice

client.go, cmd/completion_util.go, cmd/list.go, go.mod, knative/lister.go, mock/lister.go
Depends on https://github.com/boson-project/faas/pull/203 - this needs to be merged first
before:
```bash
./faas list                                                                                       
myfunc
mygofunc
myqfunc
```
after:
```bash
./faas list                                                                                   
NAME      RUNTIME  URL                                                             KSERVICE  READY
myfunc    node     http://myfunc-default.apps.zroubali.devcluster.openshift.com    myfunc    True
mygofunc  go       http://mygofunc-default.apps.zroubali.devcluster.openshift.com  mygofunc  True
myqfunc   quarkus  http://myqfunc-default.apps.zroubali.devcluster.openshift.com   myqfunc   True
```
Fixes: #192
=> feat: list command - improved output

.github/workflows/ci.yaml
Fixes: https://github.com/boson-project/faas/issues/204
=> chore(ci): fix versioning for release builds

docker/runner.go
=> fix: use image name for run command

client.go, cmd/list.go, knative/lister.go
Fixes: https://github.com/boson-project/faas/issues/224
=> feat: add --all-namespaces flag to `func list`

cmd/describe.go, cmd/list.go, docs/commands.md
Fixes: https://github.com/boson-project/func/issues/223
=> fix: change --format flag to --output for list and describe commands

knative/deployer.go
=> fix: set envVars when creating a function

go.mod
=> src: remove logrus dependency

docker/pusher.go, docker/pusher_test.go
=> Fix digest regex

client.go, client_test.go, cmd/func/main.go, cmd/root.go, cmd/run.go, docker/runner.go, docker/runner_test.go, go.mod, mock/runner.go, plugin/plugin.go
=> fix: `func run` now uses Docker API, not binary

docker/runner.go
=> fix: exposed port

docs/guides/integrators_guide.md
Just some small changes to keep this example synced with the changes in client.
=> docs: integrators guide update

docs/guides/python.md
=> docs: add template reference docs for Python

templates/go/events/go.mod, templates/go/http/go.mod
=> chore: bump CE version in Go templates

README.md, docs/README.md, docs/guides/nodejs.md
Minor fixes, modifed Node.js guide a little bit, I removed the reference to Lance's local setup (@lance I hope you don't take it personally 😄 )
=> docs: minor chores and fixes

docs/guides/golang.md
=> docs: Golang function developer's guide

docs/guides/quarkus.md
=> docs: add template reference docs for Quarkus

cmd/build.go
=> fix: default for `--builder` flag

docs/guides/developers_tutorial.md
=> docs: tutorial references to /latest/ for binary download

Makefile
=> src: cleanup after test

cmd/root_test.go
=> src: add tests

cmd/deploy.go, cmd/run.go, docs/guides/commands.md, docs/guides/func_yaml.md
=> src: update cli help for env

config.go
Currently contents of `func.yaml` are not validated, so users are able to specify anything in there (and that content ignored).
- adding validation check
- polishing the error message a little bit:
```
$ func deploy                                                                                                                                          
Error: yaml: unmarshal errors:
line 10: field foo not found in type function.config
line 11: field baz not found in type function.config
```
->
```
$ func deploy 
Error: 'func.yaml' config file is not valid:
line 10: field foo is not valid
line 11: field baz is not valid
```
=> src: check that func.yaml is valid

cmd/emit.go
=> src: fail fast with conflicting flags

Makefile
=> chore: bump golangci-lint version

docs/guides/nodejs.md, templates/node/events/README.md, templates/node/events/index.js, templates/node/events/package-lock.json, templates/node/events/package.json, templates/node/events/test/integration.js, templates/node/events/test/unit.js, templates/node/http/index.js, templates/node/http/package-lock.json, templates/node/http/package.json, templates/node/http/test/integration.js
Pretty-printing the contents of the event and its envelope for each
request. This is handy when invoked as a Knative event sink as some
sources, e.g. Kafka, ignore the response body.
=> src(templates)!: modify the nodejs event template to accept a cloudevent

cmd/deploy.go
=> fix: password read on windows

buildpacks/builder.go, go.mod
prevent permission denied on docker socket mount
=> fix: disable selinux labeling

cmd/deploy.go, docker/credentials_helper.go, docker/credentials_helper_test.go, go.mod
=> fix: use credsstore

docs/guides/developers_tutorial.md, docs/guides/podman.md
=> doc: how to use podman

AUTHORS, OWNERS
Preparation for the move to knative-sandbox.
See: https://github.com/knative/community/issues/613
=> chore: add AUTHORS and OWNERS files

.github/workflows/pull_requests.yaml, hack/test-integration-podman.sh
=> CI run integration test against podman

.github/workflows/ci.yaml, .github/workflows/pull_requests.yaml, Makefile, hack/allocate.sh, hack/registry.sh
:broom: Restructures Makefile for better readability.
:gift: Adds `make help` with summary of primary targets
:gift: Lowers initial developer setup  for core development by creating a separate target for running language template unit tests
:wastebasket: removes unused targets
=> src: Makefile developer accessibility

test/_e2e/trigger_http_test.go, test/_e2e/update_templates/typescript/http/package-lock.json, test/_e2e/update_templates/typescript/http/package.json, test/_e2e/update_templates/typescript/http/src/index.ts, test/_e2e/update_templates/typescript/http/tsconfig.json
- :gift: Adding minimal e2e test support for typescript runtime
=> ci: Added minimal e2e test support for typescript runtime

README.md, docs/DEVELOPMENT.md, docs/README.md
Creates a few docs updates, primarily the addition of `DEVELOPMENT.md` which includes the basics for developers to build and test.
Fixes #427
=> doc: DEVELOPMENT.md

README.md
- :broom: Update Build status README.md badge to query CI action
- :broom: Update all badges in README.md to knative-sandbox/kn-plugin-func
/kind chore
=> doc: status badges

client.go, cmd/deploy.go, docker/pusher.go
:bug: fix bug where progress indicator breaks user input when asking for credentials
resolves #364 #354
=> fix: hide progress indicator if asking for creds

.github/workflows/ci.yaml, .github/workflows/pull_requests.yaml, Makefile, config.go, go.mod, go.sum, schema/func_yaml-schema.json, schema/generator/main.go
- :gift: Generate json schema for func.yaml
Relates: #336 
We can generate json schema for `func.yaml`, the schema could be added to https://www.schemastore.org/json/ -> most of IDEs uses schemastore to enable code completion & validation  of certain files for users out of the box:
https://user-images.githubusercontent.com/726523/128372953-6f58bea0-d8f0-4407-a86e-180cf207be7a.mp4
I wasn't able to add validation to `Envs` and `Labels`, because they internally share the same type `Pairs`, but the validation of values is different for each type: https://github.com/knative-sandbox/kn-plugin-func/blob/818ec572aa52f12a35bb6b022c2e727ce6ebbfd3/config.go#L120-L123
A solution would be to re-introduce separate Go types for each …
=> feat: generate json schema for func.yaml

buildpacks/builder.go
- :broom: Use our mirror of lifecycle image
=> chore: use mirror for lifecycle image

Makefile
🎁 integrates new schema generator into core build targets
Invokes schema generation on `make` when:
- config.go modified
- after a `make clean`
Also includes an explicit target for the exact file as well via `make schema/func_yaml-schema.json`
=> feat: make func schema if config updated

docker/pusher.go, docker/pusher_test.go
- Support nested image paths
/kind bug
Fixes #398
=> Support nested image paths

Makefile, cmd/config.go, cmd/config_envs.go, cmd/config_labels.go, cmd/config_labels_test.go, cmd/config_volumes.go, go.mod, go.sum
:test_tube: added test for label config
this adds tests for interactive wizard for label addition and deletion using `func config labels [add|remove]`
=> Tests config labels

.gitignore
=> chore: ignore IDE files

cmd/create.go
- :broom: Fix help message description (quarkus sample) for create command
=> doc: fix create command help message description

README.md
- added `func` Task Force meeting time to README
=> add meeting time to README

OWNERS
Adding myself as an Owner so I can start using labels
=> Add Omer to OWNERS

Makefile, client.go, client_test.go, repositories.go, repositories_test.go, repository.go, repository_test.go, templates.go, templates_test.go
- :gift: Templates management api
- :gift: Repositories management api expansion
Prerequisites for #453 and #451
=> feat: repository and templates client api

cmd/deploy.go
=> chore: minor fix in the help doc

cmd/build.go
=> chore: fix typo in `build` help message

function.go
- :bug: `build` should honor registry specified in `-r`
Fixes #506
=> fix: `build` should honor registry specified in `-r`

client.go
Fixing typo brought in https://github.com/knative-sandbox/kn-plugin-func/pull/490
=> chore: properly access repositories

function_test.go
=> test: add test for DerivedImage

cmd/deploy.go, docker/credentials_helper.go, docker/pusher.go, docker/pusher_test.go
* If config file does contain credentials but they are incorrect then user will be prompted to enter correct ones.
* If user enters incorrect credentials then the user will be prompted again.
=> Better credentials handling

client.go
Some feedback from the user interviews indicated that people sometimes
get confused by how long it takes to  build a function the first time
and are tempted to kill the process. This change updates the progress
message every five seconds for twenty seconds, and if a build takes longer
than that the message remains "Still building".
Not sure if this is really needed, but it was a fun and easy fix. Happy to
use better/funnier/pithier text if you have suggestions.
=> feat: periodically update progress during build

client.go
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/542
=> fix: stop the progress ticker after build completes

cmd/build.go
- :bug: Apply registry change only when specified by command line flag (viper merges registry command line flag and env variable)
Fixes #527
=> avoid unintentional image/registry overwrite

.codecov.yaml
- :broom: setup CodeCov report (codecov.io) upload and bot
=> test: setup CodeCov report (codecov.io) upload and bot

.github/workflows/ci.yaml
The CI workflow is failing because we now depend on at least 1.16.
-
-
-
/kind chore
Fixes #
```release-note
```
**Docs**
```docs
```
=> chore: bump go to 1.16 in ci workflow

test/_e2e/cmd_config_volumes_test.go
- :broom: Adding e2e test for func config volumes
=> test: add e2e test for config volumes

.github/workflows/ci.yaml
This reverts commit b9d6d07b98f0fe8304b922faf379f3bb2265a23b.
-
-
-
/kind chore
Fixes #
```release-note
```
**Docs**
```docs
```
=> Revert "chore: use release-please fork for release branches (#609)"

.github/workflows/ci.yaml
-
-
-
/kind chore
Fixes #
```release-note
```
**Docs**
```docs
```
=> chore: bump go version to 1.16 in ci build

.codecov.yaml, buildpacks/builder.go, docker/docker_client.go, docker/docker_client_generated.go, docker/docker_client_linux_test.go, docker/docker_client_test.go, docker/pusher.go, docker/runner.go, go.mod, vendor/modules.txt
If following conditions are met:
* the DOCKER_HOST environment variable  is empty
* socket doesn't exist at default location
* `podman` is on `$PATH`
*  we are on Linux
Then temporary start `podman` service and `func` uses the service.
=> feat: automatically start podman service

Makefile
- :broom: Update golangci-lint to latest version
/kind chore
=> chore: makefile-initiated golangci-lint to v1.43.0

client.go, cmd/build.go, cmd/build_test.go, cmd/root.go
- First approach for #676 
Currently have some debug statements in the code because I'm having an issue where the `push` flag is available to the command but it's not getting picked up by viper
=> feat: add flag to push image at the end of a successful build

k8s/dialer_test.go
=> Fix dialer test

client.go, cmd/run.go, cmd/run_test.go, docker/runner.go, docker/runner_test.go
- :broom: A prompt will ask users if they want to build the current function when an image has not been found
- :broom: Build error messages are shown to the user
Fixes #577
=> feat: allow build to be triggered from run when fn.Image is missing

pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
-  :gift: add definition for `func-deploy` Tekton Task
Relates: #620
=> feat: add definition for `func-deploy` Tekton Task

cmd/deploy.go, docker/pusher.go, docker/pusher_test.go, pipelines/init.go, pipelines/registry_credentials.go, pipelines/tekton/pipeplines_provider.go
=> src:  use common functionality for docker cred retrieval

pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
=> fix: use correct --build flag value for `func-deploy` Tekton Task

cmd/run.go
- :bug: Fix the build flag not properly binding to viper
/kind bug
=> ensure build flag binds for run command

docs/guides/podman.md
=> fixup: document minimum podman version

http/transport.go, http/transport_test.go, k8s/dialer.go, k8s/dialer_test.go
Allow usage of custom Certification Authority for specified host names.
=> Enable custom CA for specified server names

hack/allocate.sh, hack/delete.sh
- :bug: fix default cluster name collision
local Kind cluster now named "func"
/kind bug
Fixes #778
=> fix: local cluster name collision

client.go, client_int_test.go, client_test.go, cmd/delete.go, k8s/persistent_volumes.go, k8s/role_bidings.go, k8s/secrets.go, k8s/service_accounts.go, knative/remover.go, mock/pipelines_provider.go, pipelines/tekton/pipeplines_provider.go, pipelines/tekton/resources.go
- 🎁 On cluster build: delete pipeline and all created resources with func delete
Fixes: #754
=> feat: delete pipeline and resources with `func delete`

docs/guides/on-cluster-build.md
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> doc: `git add` before `commit` and `push` for on cluster builds

test/presubmit-tests.sh
Pushing this to the latest release branch.
=> chore: skip integration tests for now (#780)

docker/creds/credentials.go, docker/creds/credentials_test.go
Cherry picked from `main` 6c282e77c2ffc6c6485fd4760b1738b11a2189eb
=> fix: authentication check failure for gcr.io

Makefile, hack/release.sh
=> chore: change TAG to ETAG to avoid stepping on toes

function.go, schema/func_yaml-schema.json
- :bug: fix `func.yaml` schema
/kind bug
Fixes #804
=> src: fix `func.yaml` schema

cmd/create.go
- :bug: Setting the default for language selector correctly
/kind bug
Fixes #814 
```release-note
Fixes a bug during func create when confirm option is used with the go language runtime
```
=> Setting the default for language selector

docs/guides/podman.md
```release-note
Clarify podman requirements on Linux vs. MacOS and Linux in podman.md guide
```
=> Fix podman guide

cmd/build.go, cmd/client.go, cmd/deploy.go, cmd/root.go, http/transport.go, openshift/openshift.go, openshift/openshift_test.go
:gift: add initial framework for cluster flavor detection/actions
```release-note
Detects when deploying to OpenShift and use internal registry
```
=> Custom improvements for OpenShift

docs/guides/commands.md, docs/guides/golang.md, docs/guides/language-packs.md, docs/guides/nodejs.md, docs/guides/on-cluster-build.md, docs/guides/python.md, docs/guides/quarkus.md, docs/guides/typescript.md, templates/node/http/index.js, templates/typescript/http/src/index.ts
=> fix: minor typos in docs

test/_e2e/cmd_invoke_test.go
- :broom: Update logic on invoke e2e test, in order to resolve the service url from the running 
These changes allow to run Invoke e2e test against any cluster
=> test: url for invoke test

openshift/openshift.go, openshift/openshift_test.go
* Make OpenShift test an integration test
* Fix OpenShift detection
=> Mark OpenShift test as an integration test

cmd/create.go
- :gift: Printing helpful shorthand command when confirm option is chosen
Fixes #768
```release-note
printing helpful shorthand command when confirm option is chosen
```
=> printing helpful shorthand command

openshift/openshift.go
=> Fix OpenShift credential loader

client.go, client_test.go, cmd/invoke.go, invoke.go
- :gift: Make `func invoke` print any response it receives
```release-note
`func invoke` now prints any response it receives from the invoked function
```
=> Make `func invoke` print any response it receives.

cmd/root.go
- :bug: Fix verbose flag not bound on root
/kind bug
=> fix: bind verbose flag to root

docs/DEVELOPMENT.md
Update template generation documentation.
=> Update developer documentation.

docs/DEVELOPMENT.md
=> docs: parameter `-P` is not needed in grep in pre-commit hook

buildpacks/builder.go, client.go, client_test.go, cmd/build.go, cmd/config.go, cmd/config_envs.go, cmd/create.go, docker/pusher.go, docker/pusher_test.go, k8s/client.go, pipelines/tekton/client.go, ssh/terminal.go
* replaced some plain `==` by `error.Is()`
* wrapping some more errors using `fmt.Errorf()`
=> Improve error handling

.github/workflows/knative-go-build.yaml, .github/workflows/knative-go-test.yaml, .github/workflows/knative-releasability.yaml, .github/workflows/knative-release-notes.yaml, .github/workflows/knative-security.yaml, .github/workflows/knative-stale.yaml, .github/workflows/knative-style.yaml, .github/workflows/knative-verify.yaml
This reverts commit 8312b5c56010b06e867cbd92c5983d2c4be61310.
- :bug: revert workflow update
Workflows are failing with error:
This reverts that commit until permissions can be sorted out.
/kind bug
Fixes #928
=> fix: revert cross-org workflow update

filesystem_test.go, generate/templates/main.go
* Improve test error output: better diff if embedded/actual FS content differs
* Close file after use
=> Template generation improvements

test/_e2e/update_templates/python/http/Procfile
- :broom: Update python e2e test
/kind cleanup
=> test: update python e2e tests (new revision test)

docker/creds/credentials.go, docker/creds/credentials_test.go
- :bug: Allow push to registry not protected by password.
Useful when using localhost unsecured registry.
```release-note
fix: allow push to registry not protected by password
```
=> Allow empty credentials registry

cmd/build.go, cmd/completion_util.go
- :broom: Improve help for the `build` sub-command
=> Improve help for the `build` sub-command

hack/test.sh
* Increase readiness wait timeout values
=> chore: fix timeout in test

docs/reference/func_yaml.md
Addresses recent changes in func.yaml processing. Not all fields for the file are documented. I'm not sure if they all should be.
=> doc: fix some func.yaml fields

s2i/builder.go
* Close opened file
* Better handling for symlinks in code
=> fix: minor improvements for s2i build

docs/reference/commands.md
- 🐛 Without this the following section is unintentionally included in the code quote.
=> doc: add closing mark

docs/getting_started_kubernetes.md
Signed-off-by: jiang wei <jwcesign@gmail.com>
- update knative-serving version for getting started
- update knative-eventing version for getting started
- update cert-manager version for getting started
Fixes docs
```release-note
none
```
**Docs**
```docs
none
```
=> Update to the latest knative version

docker/creds/credentials.go, docker/creds/credentials_test.go, docker/pusher.go, pipelines/tekton/pipeplines_provider.go
- :bug: Verify write/push authorization before push, up until now we just checked if login into registry works.
/kind bug
```release-note
fix: verify write/push authorization before push, before we only check if login works
```
resolves #1094
=> fix: image push authorization check

test/_e2e/update_templates/node/cloudevents/package-lock.json, test/_e2e/update_templates/node/http/package-lock.json, test/_e2e/update_templates/typescript/http/package-lock.json
Addresses dependabot alerts for the Node.js and TypeScript e2e tests.
/kind chore
=> chore(deps): update node/typescript deps in e2e tests

.github/workflows/ci.yaml, Makefile, hack/release.sh
- :gift: Add build for Linux/arm64
=> feat: build for Linux ARM64

buildpacks/builder.go, cmd/build.go, cmd/completion_util.go, cmd/deploy.go, function.go, function_builder.go, function_builder_unit_test.go, s2i/builder.go, schema/func_yaml-schema.json
- :broom: add validation for `builder`
- :gift: add supported types (pack, s2i) to json schema
=> chore: add validation for `builder`

.github/workflows/update-quarkus-platform.yaml, hack/update-quarkus-platform.sh
- :gift: Added periodic task that checks Quarkus platform version in templates and creates PR with update if needed.
=> Quarkus platform auto-updater

cmd/root.go
- :bug: remove duplicate cmd.AddCommand(NewLanguagesCmd) at root.go
/kind bug
=> remove duplicate cmd.AddCommand(NewLanguagesCmd) at root.go

function_envs.go, function_envs_unit_test.go, pipelines/tekton/resources.go, pipelines/tekton/tasks.go
- :gift: On cluster build: support Build Envs
Fixes #1173
=> On cluster build: support Build Envs

.codecov.yaml
- :broom: update codecov configuration to be explicit about coverage thresholds
/kind chore
=> chore: adjust codecov configuration

repository.go
- :bug: Optimise template loading: use locally checked out files, i.e. do not re-clone content from `.git/` dir.
resolves: #1186
=> fix: performance of template loading

.gitignore
As requested by @lance, this update to the .gitignore should be put in a separate PR.
=> chore: update .gitignore (#215)

s2i/builder.go
=> fix: s2i build on Windows

docs/reference/podman.md
=> docs: update podman docs

buildpacks/builder.go, go.mod
- :bug: Fix broken output of pack build on Windows (there were issues with coloured output).
=> fix: pack build outpout on Windows

.github/workflows/build.yaml, .github/workflows/check.yaml, .github/workflows/ci.yaml, .github/workflows/schema.yaml, .github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, .github/workflows/test-e2e-runtime.yaml, .github/workflows/test-e2e.yaml, .github/workflows/test-embedded-fs.yaml, .github/workflows/test-integration.yaml, .github/workflows/test-podman.yaml, .github/workflows/test-unit.yaml, Makefile
- Update Go in actions to 1.18
/cc @matejvasek @salaboy
=> Update Go in actions to 1.18

cmd/deploy.go
- :bug: squelch invalid initial warning
- :bug: fix warning message text's last parameter
/kind bug
Fixes #1256
=> fix: incorrect deploy namespace warnings

docs/reference/func.md, docs/reference/func_build.md, docs/reference/func_deploy.md
- :broom: sync docs with the source code
=> chore: sync docs with the source code

cmd/client.go, cmd/invoke.go, docs/reference/func_invoke.md, http/transport.go
- :gift: `invoke` - Adding option allowing insecure connections over SSL
```release-note
`invoke` - Adding option allowing insecure connections over SSL
```
=> feat: `invoke` - Adding option allowing insecure connections over SSL

README.md
- :gift: Add codecov badge to readme
No issue needed as this is a requirement for the maturity level of the project
```release-note
```
**Docs**
```docs
```
=> [chore] Adding Codecov badge to readme

.codecov.yaml
Updating Codecov configs following kn/client, ignoring `tests` and `hack` dir
- :broom: clean up config and add ignores
/kind cleanup
```release-note
```
**Docs**
```docs
```
=> [chore] updating codecov configs

function_envs_unit_test.go, function_labels_unit_test.go, function_volumes_unit_test.go
Adding test coverage for labels and envs. 
- :gift: labels to string and edge case test coverage
- :gift: envs to string and edge case test coverage
- :gift: voumes to string and edge case test coverage
Related to #1275
```release-note
```
**Docs**
```docs
```
=> [chore] increase labels, envs and volumes test coverage

client_test.go, cmd/delete_test.go, cmd/invoke.go, config/config.go, docker/creds/credentials.go, docker/creds/credentials_test.go, docker/docker_client_ssh_test.go, docs/generator/main.go, filesystem_test.go, function.go, function_volumes.go, invoke.go, repository.go, s2i/builder_test.go, schema/generator/main.go, ssh/ssh_dialer.go, test/_e2e/trigger_events_test.go, test/_e2e/trigger_http_test.go, test/_e2e/update_test.go, testing/testing.go
A follow-up to my previous modules update PR. It isn't necessarily broken yet, but I've got it ready in stash already. :)
-  :broom: chore: Refactor use of deprecated `io/ioutil` package
/kind cleanup
Fixes #
```release-note
```
**Docs**
```docs
```
=> chore: Refactor use of deprecated `io/ioutil` package

go.mod, knative/deployer.go, knative/logs.go
- :gift: Display ksvc ouput on deploy for better debugging.
=> feat: ksvc log on deploy

repository.go
Add missing manifest file closures
=> fix: missing close of manifests

docs/README.md
Removed a lingering reference to Boson and accepted Grammarly reccomendations.
/kind chore
=> chore: update docs README.md

hack/release.sh
Correcting an oversight after the move from knative-sandbox.
/kind chore
=> chore: update release script to use knative org

buildpacks/builder_test.go, test/README.md
- 🧹 Adding small tests to see project general coverage changes
/kind chore
=> Func unit testing first approach

cmd/client.go, docker/runner.go, docker/runner_int_test.go, docker/runner_test.go
- :test_tube: Test for docker runner.
=> test: test for docker runner

.codecov.yaml
=> chore: fix codecov.yaml

k8s/logs_test.go
- :test_tube: Test get pod's logs.
/kind test
=> test: added test for get pod's logs

.github/workflows/build.yaml, .github/workflows/check.yaml, .github/workflows/ci.yaml, .github/workflows/schema.yaml, .github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, .github/workflows/test-e2e-runtime.yaml, .github/workflows/test-e2e.yaml, .github/workflows/test-embedded-fs.yaml, .github/workflows/test-integration.yaml, .github/workflows/test-podman.yaml, .github/workflows/test-unit.yaml, .github/workflows/update-quarkus-platform.yaml
See: https://github.com/knative/func/actions/runs/3242685285
/kind chore
=> chore: bump node and golang actions to latest

knative/integration_test.go
- :test_tube: Initial integration tests for `knative` related functionality.
Related: https://github.com/knative/func/issues/1278
=> test: initial integration test for knative related functionality

cmd/deploy.go, docs/reference/func_deploy.md
Update the 'deploy' subcommand's help text.
/kind chore
=> chore: update deploy help text

knative/deployer.go, knative/integration_test.go, knative/logs.go
- :test_tube: Extended knative deployment integration test: added more tests for envvars and volumes.
- :bug: Fixed race-condition.
=> test: extended integration test for deployment

client.go, client_test.go, cmd/build.go, cmd/client.go, cmd/create.go, cmd/create_test.go, cmd/delete.go, cmd/deploy.go, cmd/invoke.go, cmd/languages.go, cmd/repository.go, cmd/templates.go, config/config.go, config/config_test.go, docker/creds/credentials.go, docker/creds/credentials_test.go, go.mod, job.go, repositories.go
- :bug: config paths on disk only created when necessary
- :gift: Adds FUNC_CONFIG_PATH environment variable
Related: #901
=> chore: global config file paths

function.go, function_test.go, instances_test.go
:bug: NewFunction errors on valid path
The NewFunction constructor should only error on invalid paths; not when the given path has not yet been initialized.
Fixes #1371 
```release-notes
fixes an issue where the NewFunction constructor could error if the path has not yet been initialized as a function
```
=> fix: function constructor errors on valid path

docker/pusher.go, s2i/builder.go
- :gift: Improved output of s2i build and push.
```release-note
feat: improved output of s2i build and push
```
=> feat: improve output of s2i build and push

hack/allocate.sh, hack/binaries.sh
- :broom: upgrade ci resources version (kubectl, kind, knative)
/kind cleanup
=> upgrade ci resources version

knative/integration_test.go
- :test_tube: Knative integration test improvements:
* Test tries to invoke the function.
* The testing image is multi-arch.
* Some `Fatal()`'s changed to `Error()`'s.
=> test: improve knative tests

cmd/build.go, cmd/deploy.go, config/config.go
:gift:  adds builder to global config
=> feat: builder globally configurable

buildpacks/builder.go
=> chore: update lifecycle

filesystem.go, filesystem_test.go, generate/templates/main.go
- :bug: Added support for symlinks in templates.
/kind bug
```release-note
fix: support for symlinks in templates 
```
resolves #1368
=> fix: allow symlinks in templates

pipelines/tekton/pipeplines_provider.go, pipelines/tekton/pipeplines_provider_test.go, pipelines/tekton/testData/fn-src/hello.txt.lnk
- :bug: Fix uploading of project containing symlink for on-cluster-build.
/kind bug
```release-note
fix: uploading of project containing symlink for on-cluster-build
```
=> fix: uploading of project containing symlink for on-cluster-build

filesystem.go, filesystem_test.go, generate/templates/main.go
* Improved error messages.
* Replaced `if`s with `switch`.
=> refactor: clean up

pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml, pipelines/tekton/resources.go, pipelines/tekton/tasks.go
- :gift: Cache maven repository for Java builds.
/kind enhancement, performance
```release-note
feat: caching for on-cluster s2i build
```
=> feat: caching for on cluster s2i build

cmd/deploy.go, cmd/deploy_test.go, docs/reference/func_deploy.md, function.go, schema/func_yaml-schema.json
- 🎁 Persist the value of `--remote` flag in func.yaml and use the persisted value when the flag hasn't changed
Partly addresses #1176 
```release-note
Persist the value of "remote" field in func.yaml and use it as default
```
=> feat: Persist remote value in func.yaml

docs/generator/main.go
:bug: docs generator is affected by environment's global config
When adding the global config system, the docs generator needed to also be updated such that it does not encode the current environment's global settings in the generated docs (flag defaults).
=> fix: ignore global config on docs gen

cmd/build.go, docs/reference/func.md, docs/reference/func_build.md
- :broom:  Update build command help text a bit
=> src: update build command help text

pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
- Fix CI on-cluster-build failures.
=> fix: on cluster build

docs/building-functions/on_cluster_build.md
- :broom: docs: update on cluster build guide to explicitly mention `--remote` flag
/kind  documentation
=> docs: update on cluster build guide to explicitly mention `--remote` flag

pipelines/tekton/defaults.go, pipelines/tekton/pipeplines_provider.go, pipelines/tekton/pipeplines_provider_test.go
Quick fix according to reported problem (pvc size too small) and small refactoring for #851; second part (new flag `--pvc-size`) follows as an independent PR.
=> feat: change default pvc size to 256Mi (#851)

buildpacks/builder.go
- :broom: Update BP lifecycle image to 0.15.3
=> chore: update BP lifecycle image to 0.15.3

cmd/create.go
- :bug: fixes an error running create command help
/kind bug
Fixes #1498
Fixes #1499
=> fix: create command help text

docs/reference/func_build.md, docs/reference/func_create.md
- :broom: rebuild docs
In a recent commit I must have forgotten to rebuild docs with a `make`.  This PR corrects that oversight.
/kind cleanup
=> rebuild docs

pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml, pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml, pipelines/tekton/pipeplines_provider.go, pipelines/tekton/resources.go, pipelines/tekton/tasks.go
- :bug: Fix oncluster builds registry error
Fixes #1541
=> fix: oncluster builds registry mismatch error

pkg/config/config.go, pkg/config/config_test.go
- :gift: adds accessors to the global config package
To enable the manipulation of global config settings via the CLI, this PR adds static accessors to the config package which operate based on the key name as it would exist in `~/.config/func/config.yaml`
Related: #901
=> feat: global config accessors

pkg/builders/buildpacks/builder.go
- :bug: Ban `podman` 4.3 for pack build. The 4.3 version contains bug causing infinite wait.
=> fix: ban podman 4.3 for pack build

pkg/knative/deployer.go
Fixes #1568
Add initialization to service.Spec.Template.ObjectMeta.Annotations
:bug: Fix bug
=> fix initialization of service.Spec.Template.ObjectMeta.Annotations

Makefile, pkg/functions/client_int_test.go, pkg/knative/deployer.go
- :broom: deploy annotations & labels correctly
- :broom: set timeout for integration test to 30mins
Fixes: https://github.com/knative/func/issues/1571
=> fix: deploy annotations & labels correctly

Makefile, generate/templates/main.go, hack/update-quarkus-platform.js, hack/verify-codegen.sh
Some places were missed in the repo restructuring. This should fix test_infra build failures.
See: https://prow.knative.dev/?job=nightly_func_main_periodic
/kind chore
=> chore: update references to zz_filesystem_generated.go

pkg/filesystem/filesystem_test.go
=> cleanup: FS test

hack/verify-codegen.sh
- :bug: Do not store/restore the zz_filesystem_generated.go file.
=> chore: verify-codegen.sh

pkg/pipelines/tekton/pipelines_pac_provider.go
- :broom: better output for PaC
Relates:  https://github.com/knative/func/issues/1323
=> chore: better output for PaC

cmd/create.go, docs/reference/func_create.md
- :bug: Change 'create' help text to indicate mandatory language option
Fixes #1508
=> Change 'create' help text to indicate mandatory language option

docs/function-templates/golang.md, docs/function-templates/nodejs.md, docs/function-templates/python.md, docs/function-templates/quarkus.md, docs/function-templates/typescript.md, docs/language-packs/language-pack-contract.md, docs/reference/func_yaml.md
- :bug: Fix broken links in docs
/kind bug
Fixes #1295
=> docs: update broken links in docs to command.txt and command.md

cmd/config_git_set.go
- :broom: properly implement `--config*` flags for `func config git`
Relates https://github.com/knative/func/issues/1323
=> chore: properly implement `--config*` flags for `func config git set`

s2i/builder.go
- :bug:  s2i python build on Windows
```release-note
fix: s2i python build on Windows
```
=> Pick s2i build fix

cmd/config_git_set.go, pkg/git/git.go, pkg/git/git_test.go, pkg/pipelines/metadata.go, pkg/pipelines/tekton/pipelines_pac_provider.go, pkg/pipelines/tekton/resources_pac.go
- 🎁 PAC - add possibility to specify a Git provider, though only GitHub provider is supported at the moment
Relates: https://github.com/knative/func/issues/1323
=> feat: PAC - add possibility to specify a Git provider

pkg/docker/creds/credentials.go
- :broom: Style, fix lint error.
=> style: fix lint error

pkg/functions/function.go, pkg/functions/function_envs.go, pkg/functions/function_volumes.go, schema/func_yaml-schema.json
- :gift: Add `omitempty` flag to fields in Function structure in order to create a minimal func.yaml. This change doesn't address `buildpacks` that should be dealt with in a separate PR.
Fixes #1279
=> feat: Minimal initial func.yaml

pkg/builders/buildpacks/builder.go
- :broom: Update lifecycle image to v0.16.1.
```docs
chore: update lifecycle image to v0.16.1
```
=> chore: update lifecycle image to v0.16.1

hack/release.sh
Minor adjustment per @dsimansk here https://github.com/knative/func/pull/1652#pullrequestreview-1362565056
/kind chore
/assign @dsimansk
=> chore: adjust shell script quotes

test/oncluster/scenario_github_test.go, test/oncluster/testdata/simplefunc/.gitignore, test/oncluster/testdata/simplefunc/func.yaml, test/oncluster/testdata/simplefunc/index.js, test/oncluster/testdata/simplefunc/package-lock.json, test/oncluster/testdata/simplefunc/package.json
- :gift: Add e2e github oncluster test scenario
It covers #856 item 
/kind cleanup
=> test: adding e2e github oncluster test scenario

cmd/completion_util.go
- :bug: Fix the `--template` flag completion.
=> fix: template flag completion

pkg/functions/invoke.go, pkg/http/transport.go
- :bug: Increase connection timeouts.
=> fix: increase connection timeouts

pkg/functions/repository.go, pkg/functions/template.go
- :broom: move template struct definition to template.go 
/kind cleanup
=> src: move template struct definition

.github/workflows/update-quarkus-platform.yaml, hack/update-quarkus-platform.js
- :broom: Quarkus auto-update action runs smoke test.
=> chore: Quarkus auto-update action runs smoke test

docs/reference/func_deploy.md
- :broom: regenerate docs to get domain option
/kind cleanup
=> docs: regen for domain option

.github/workflows/test-integration.yaml, hack/install-gitlab.sh, hack/install-pac.sh, pkg/pipelines/tekton/gitlab_test.go
- :broom: Clean up PaC GitLab test.
=> chore: clean up PaC GitLab test

pkg/pipelines/tekton/gitlab_test.go
- :broom: Run test operations in dedicated namespace.
=> cleanup: run test operations in dedicated ns

.github/workflows/test-integration.yaml, hack/allocate.sh, hack/patch-s2i-task.sh, pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml, pkg/pipelines/tekton/pipelines_integration_test.go
- :broom: Integration test for tekton on cluster build.
=> test: integration test for tekton on cluster build

pkg/functions/runner.go
Fixes https://github.com/knative/func/issues/1801
=> Check error before defer body close, include timeout in error message

hack/allocate.sh
- :broom:  Use ghcr.io for dapr components in GH Action.
resolves: #1806
=> src: use ghcr.io for dapr components in GH Action

.github/workflows/test-integration.yaml, hack/binaries.sh
- :broom:  Log cluster events and cluster containers logs in GH Action. This will be useful for debugging of failed actions.
=> src: more verbose output

Makefile
Also automatically rebuild embedded templates on `make update-runtimes`
/kind cleanup
=> src: rebuild templates on make update-runtimes

pkg/knative/deployer.go
=> fix: deploy warning about insecure defaults (#1851)

.github/workflows/test-e2e-oncluster-runtime.yaml
Dump cluster logs in On Cluster RT test.
=> chore: dump cluster logs in tests

.github/workflows/ci.yaml
- :gift: Make `func` image multiarch.
=> Make func image multiarch

.github/workflows/test-e2e-oncluster-runtime.yaml, test/oncluster/scenario_runtime_test.go
- :broom: User FUNC_BUILDER environment variable when available for on-cluster e2e tests.
/kind cleanup
=> test: consider FUNC_BUILDER env var for e2e oncluter tests

test/e2e/scenario_no_container_test.go
- :broom: adding test for run without container
/kind cleanup
=> adding test for run without container

hack/allocate.sh
- fix: Fix missing bash function in allocate.sh script
/cc @lkingland 
```release-note
NONE
```
=> fix: Fix missing bash function in allocate.sh script

test/gitserver.sh
- :broom: Update test gitserver image
/kind cleanup
=> test: update gitserver test image

cmd/config_git.go, cmd/config_git_remove.go, cmd/config_git_set.go, cmd/config_labels.go, cmd/deploy_test.go, cmd/invoke.go, cmd/languages.go, cmd/repository.go, cmd/run.go, cmd/subscribe.go, cmd/templates.go, cmd/version.go
:broom: remove unused args
/kind cleanup
=> src: remove unused args

pkg/functions/client.go
:broom: Remove unreachable condition
/kind cleanup
=> src: remove unrechable condition

test/common/gitserver.go, test/oncluster/scenario_basic_test.go, test/oncluster/scenario_context-dir_test.go, test/oncluster/scenario_from-cli_test.go, test/oncluster/scenario_revision_test.go, test/oncluster/scenario_runtime_test.go
- :broom: Clean up e2e oncluster test
/kind cleanup
=> Clean up e2e oncluster test

pkg/knative/deployer_test.go
- fix: Disable flaky unit test Test_deployerNamespace
/cc @lkingland @gauron99 @matejvasek
=> fix: Disable flaky unit test Test_deployerNamespace

pkg/builders/s2i/builder.go
```release-note
chore: update images ubi8 => ubi9
```
=> chore: update images ubi8 => ubi9

pkg/pipelines/tekton/gitlab_test.go
* Fixed the issue where gitlab setting modification returned error for no good reason. It appears that gitlab returns field `container_registry_import_created_before` as an empty string `""` and JSON deserializer rejects such a value for date/time. I fixed this by injecting custom `RoundTripper` that removes that field in case it's has value of empty string.
* Remove hardcoded sleep in favor of active condition checking.
Related:
https://github.com/xanzy/go-gitlab/issues/1952
https://gitlab.com/gitlab-org/gitlab/-/issues/466132
=> fix: error when setting gitlab settings in test

pkg/pipelines/tekton/gitlab_test.go
Increased wait period for Gitlab settings change to kick in.
=> test: increased wait period

pkg/pipelines/resources/tekton/task/func-buildpacks/0.2/func-buildpacks.yaml, pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml, pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml, pkg/pipelines/tekton/client.go, pkg/pipelines/tekton/pipelines_provider.go
Updated tekton API `v1beta1` => `v1`.
=> chore: updated tekton api verison

pkg/builders/buildpacks/builder.go
-
-
-
/kind <kind>
Fixes #2483
```release-note
```
**Docs**
```docs
```
=> Use latest buildpack builder images

Dockerfile.utils
bumping because of https://github.com/knative/func/pull/2578
=> bump builder image

.github/workflows/ci.yaml, .github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, .github/workflows/test-e2e-runtime.yaml, .github/workflows/test-e2e.yaml, .github/workflows/test-integration.yaml, .github/workflows/test-unit.yaml, .github/workflows/update-knative-hack.yaml
bump codecov to v5 in workflows
=> bump: update codecov to v5 in workflows

.github/workflows/test-podman-next.yaml
- :gift: Test against Podman nigthly build
/kind cleanup
Fixes #2022
=> Adding workflow to test against podman nightly build

pkg/builders/builders_int_test.go, pkg/builders/s2i/builder.go
- :gift: Added host binds for S2I build
=> S2I (source-to-image) host binds

hack/cmd/update-builder/main.go
Check if the image index exist and proceed with build only if it  does not.
=> Do not run builder build unnecessary

test/e2e/main_test.go
fix e2e errorf formatting for 1.24
=> fix e2e errorf formatting for 1.24

cmd/environment.go
- :broom:  add tasks related images to func environment
=> Add tasks related images to func environment

pkg/mcp/mcp.go
- This PR adds additional flags support to the MCP server `func mcp` tools making it a perfect mapping of the CLI commands.
=> mcp: extends flags support for existing tools

pkg/oci/builder.go
- :gift: Adds FUNC_GIT env support to the Host builder
Allow specifying the path to git when using the Host builder via the FUNC_GIT environment variable.
```release-note
The path to git can be altered from that in PATH by using the FUNC_GIT environment variable when using the host builder.
```
**Docs**
```docs
```
=> feat: support FUNC_GIT env in Host builder

Makefile
- :broom: Adds missing .PHONY to Makefile
/kind cleanup
=> chore: add missing .PHONY statements to Makefile

.github/workflows/test-embedded-fs.yaml, Makefile
Creates a target in the makefile as a convenience target for running the embedded FS test.
/kind cleanup
=> chore: adds makefile target for embedded FS check

cmd/invoke.go, docs/reference/func_invoke.md, pkg/functions/invoke.go
- :gift: GET requests with `func invoke --request-type=GET`
```release-note
feat: run 'func invoke --request-type=GET' for invoking GET request
```
=> feat: func invoke get requests

cmd/root.go
https://github.com/knative/func/actions/runs/17790625765/job/50566627258
=> fix: update deprecated function by linter
