knative/func

client/client.go, client/client_test.go, client/mock/lister.go, cmd/list.go, cmd/version.go, go.mod, knative/lister.go
Adding the new list command to the client library, and creating a new knative concrete implementation package!
=> pull list into client library

client.go, cmd/create.go, cmd/delete.go, cmd/describe.go, cmd/root.go, cmd/version.go, config.go, function.go, go.mod, kubectl/deployer.go, prompt/prompt.go, prompt/prompt_test.go
Adds interactive prompts to the create command, with default values either calculated or provided via flags and environment variables.  This interactivity is disabled if the attached terminal is non-interactive.
This also fixes a problem with flags where they would silently fail to attach due to being initialized on multiple subcommands.  This was fixed by moving the registration into PreRun from the static initializer.  Fixes #8
=> Interactive prompts

.github/workflows/releases.yaml, Makefile
This PR configures the system to update the container `latest` tag on release.
All image builds create a `latest` tag locally, but the specific make target `release` must be run to push it to the repository, such that we can continue to use the other targets for development builds (which use the `tip` tag).
This new target is invoked only by the release workflow, when there is a commit to `main` with a semver tag (release).
Closes #43
=> build: utilize docker latest tag for releases only

cmd/root.go, cmd/version.go
Set command's .Version after build metadata is populated, and place semver first.  Fixes Issue #46.
=> Version flag

cmd/root.go, cmd/version.go
Only print the date and git commit hash on version when `--verbose`, and default version to `v0.0.0` if not populated by `make` (i.e. built from source)
=> chore: improve version subcommand

README.md, docs/README.md, docs/architecture.md, docs/contributors_guide.md, docs/developers_guide.md, docs/eks/config-cluster.yaml, docs/eks/users.yaml, docs/functions_cookbook.md, docs/getting_started_kubernetes.md, docs/getting_started_localhost.md, docs/getting_started_openshift.md, docs/getting_started_screencast.md, docs/installing_cli.md, docs/installing_emacs.md, docs/installing_vim.md, docs/installing_vscode.md, docs/integrators_guide.md, docs/kind/config-local.yaml, docs/kind/config-remote.yaml, docs/kind/config.yaml, docs/knative/config-domain.yaml, docs/knative/config-kourier-nodeport.yaml, docs/knative/config-network.yaml, docs/provision_eks.md, docs/provision_kind.md, docs/provision_minikube.md, docs/tls/cloudflare-secret.yaml, docs/tls/letsencrypt-issuer.yaml
Adds documentation for configuring a Kind cluster, locally and remote (#59).  Imports a reformatted version of docs from `boson-project/faas-config` (#58), and stubs out other sections.
=> doc: add docs for configuring a Kind cluster and getting started

.gitignore, Makefile
This commit adds Makefile targets for go and quarkus, and includes these in the regular `make test` target. I've also added a couple of entries to .gitignore.
Fixes: https://github.com/boson-project/faas/issues/70
=> test: add test targets for go and quarkus templates

.github/workflows/releases.yaml
Updates the secrets to use those provided at the organization-level rather than in-repo.  Once confirmed as functional (after this PR is merged and all the workflows fire correctly), the repository-level secrets should be removed.  (Fixes #27)
=> chore: use organization-level secrets for image deployment

.github/workflows/releases.yaml
This PR modifies the release adds a restriction to the release workflow to only fire off the main branch per the[ workflow docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on).
=> fix: build releases from main branch only

.github/workflows/develop.yaml
This will enable non-developers who are interested in trying out the latest builds to easily get a copy pre-release.
=> chore(actions): add binary uploads to develop branch CI

knative/describer.go
`faas describe` fails when Knative Eventing is not present (in particular if the trigger CRD is not installed). While user should have Eventing installed the `faas describe` don't have to fail because of its absence.
=> fix: describe works without Eventing

client.go, cmd/build.go, cmd/create.go, cmd/delete.go, cmd/deploy.go, cmd/init.go, cmd/root.go, cmd/update.go
The CLI commands all printed confirmation prompts for the various flags
they exposed. This commit modifies that logic, so that there is no longer
a `-y` flag, but instead a `--confirm` or `-c` flag for each command, and
prompts are only displayed if using this flag. In most cases, the derived
values are printed even if not prompted for.
In all cases where the user is prompted, I have removed the "Verbose"
prompt, as that seems less like a configuration option that needs to be
confirmed, and more like just a CLI option for the current run which we
can just accept as-is.
The text for the prompts has also been reduced to one or two words.
Also added are some checks around image naming and repositories, short
circuiting failures that could occur if these are not specified or are
unknown. For …
=> feat: default to no confirmation prompts for CLI commands

cmd/build.go, cmd/create.go, cmd/describe.go, cmd/init.go, cmd/list.go, cmd/update.go
The cobra package, magically appends "[flags]" to the usage string if a command has flags. By adding "[options]" to the usage string, we end up with help text that looks like this.
```
faas init <name> [options] [flags]
```
This commit fixes that.
=> chore: remove [options] from usage string

docs/commands.md
I've added some documentation for the CLI commands here and called out some odd behavior with the options in a couple of places. I wrote this as I was trying to sort out how I felt about https://github.com/boson-project/faas/pull/125 and https://github.com/boson-project/faas/issues/126 and thought that it would be a good document to use when trying to rationalize any usability changes. For the most part, I have changed my mind about #125 and #126. I'm still on the fence about `faas delete`, but as I wrote in the doc here, there are valid reasons to have the commands that we do and I'll just eat crow. :bird: 
Also - note that for all commands except `init` and `create`, I have documented them as they are today. For the `init` and `create` commands, I documented them as intended for …
=> docs: add documentation for CLI commands

cmd/create.go, cmd/init.go, cmd/root.go
The hardcoded, initial value for the configuration path was set to `.faas/config`. But `configPath()` immediately sets this to the correct value of ~/.config. Both the create and init commands use `configPath()` to search for additional templates, if they exist, and were each doing `filepath.Join(configPath(), "faas", "templates")`. This commit also changes `configPath()` so that it is `~/.config/faas` and does so in a cross platform friendly way. If the `$HOME` directory cannot be determined, the config is assumed to be at `./.config/faas`.
=> fix: correct value for config path and robustify

go.mod
Is there a specific reason for us to stay on `go 1.13`? `go 1.15` is already out. So updating to `1.14` for now.
=> src: use go 1.14

.github/workflows/ci.yaml
There was a typo in the upload part of the CI. Also, there was a section
that (thankfully) did not run, which would have created a second release.
Moved the release-please action later in CI so less time elapses between
the creation of the release, and the upload of the binaries.
=> chore(ci): fix release binary uploads

.github/workflows/ci.yaml
There was a bug that surfaced in 2.2.0, which we discovered in the faas-js-runtime repo. I thought it would be good to update it everywhere.
=> chore(actions): update release-please-action to latest 2.4.1

client.go, client_test.go, cmd/build.go, cmd/create.go, cmd/deploy.go, cmd/root.go, docs/commands.md, docs/integrators_guide.md, function.go, templates.go
When dealing with images, instead of referring to an image repository,
let's use the more correct term "registry", even though we're actually
using "registry/namespace" in most cases.
Fixes: https://github.com/boson-project/faas/issues/154
=> src!: change all references of "repository" to "registry" for images

cmd/root.go, plugin/plugin.go
Changes:
- Add plugin package to enable faas to be consumed as plugin
- Fix cyclic dependency issue on pkg/kn/root package 
- Optional: changed output to display standard output of `service create` command
- I'll understand if it isn't desired or needs further discussion :)
Example:
```
➜  test-project kn faas deploy             
Creating service 'test--project' in namespace 'default':
0.036s The Configuration is still working to reflect the latest desired specification.
0.059s The Route is still working to reflect the latest desired specification.
0.109s Configuration "test--project" is waiting for a Revision to become ready.
10.192s ...
10.221s Ingress has not yet been reconciled.
10.273s Waiting for load balancer to be ready
10.884s Ready to serve.
Service 'test--project' created to …
```
=> feat(kn): Enable faas to be integrated as plugin to kn

cmd/root.go, plugin/plugin.go
As @matejvasek pointed out I shouldn't change `init()` and rather benefit from it's intended build-in behaviour in `plugin.go`, otherwise standalone faas binary is broken.
=> fix: Fix root cmd init

go.mod, go.sum
from a fork of knative.dev/client
Its a temp workaround until we've the required landed in the correct dep.
=> chore: Carry WithLabel listConfig feat

.github/workflows/ci.yaml
This commit modifies the CI action so that it should bump minor versions until we explicitly have a 1.0.0 release. I've also bumped the version of release-please-action to the latest 2.5.5.
I'm not certain, but we will  probably need to close the [existing release PR](https://github.com/boson-project/faas/pull/158) after this lands in order to get a new 0.8.0 PR created.
=> chore(ci): tweak release-please-action to bump minor pre major.

cmd/delete.go, cmd/deploy.go, knative/client.go, knative/deployer.go, knative/describer.go, knative/lister.go, knative/remover.go
Using Knative Client lib for manipulation with Knative (Serving/Eventing) objects
Fixes: https://github.com/boson-project/faas/issues/160
=> src: use Knative Client libraries

client.go, cmd/build.go, knative/deployer.go, knative/remover.go
Discussed this with @lkingland, Implementing the spinner properly (so it is not eating the output) may take some time. So I'll proceed with printing some basic info messages, since we are under such a tight deadline.
And we will revisit the Spinner properly for all the commands as a post Dev Preview task.
**Build**
```
./faas build -p func                                        
Building function image
Function image has been built, image: docker.io/zroubalik/func:latest
```
**Deploy**
```
./faas deploy -p func                                           
Building function image
Function image has been built, image: docker.io/zroubalik/func:latest
Pushing function image to the registry
Deploying function to the cluster
Function deployed …
```
=> feat: Better output of build/deploy/delete commands

cmd/build.go, cmd/completion.go, cmd/create.go, cmd/delete.go, cmd/deploy.go, cmd/describe.go, cmd/list.go, cmd/root.go, cmd/run.go, cmd/version.go
This commit introduces fixes for the top-level help message as described in #187.
It does not address:
* #216 - Use `kn function` in help message when run as a plugin to kn
* #215 - Group main help message to put important commands to the top
* #214 - Make examples in usage message parameterizable
It also reworked the "build" and "create" commands, but not yet the others.
(this will happen in a follow commit)
=> chore: Update help messages and adding examples.

plugin/plugin.go
@lance @rhuss 
The following code should retrieve and set the actual plugin's version based on go.mod definition. The required change/enhancement on kn's midstream is to use `require` correctly.
It seems a bit cleaner than setting another set of compile flags. Anyway the current set of flags is set through `main` package, so we'd need to change that to pass flags during kn's build.
E.g. from my hacks:
```go
require (
github.com/boson-project/faas v0.9.0
)
replace (
github.com/boson-project/faas => /home/dsimansk/Git/boson-project/faas
)
```
```bash
➜  client git:(release-v0.17.3) ✗ kn func version
v0.9.0
```
=> fix: Fix plugin version output

cmd/describe.go
That must have been a copy/paste error.
=> fix: fix the help text for the describe function

.github/workflows/ci.yaml, .github/workflows/pull_requests.yaml, Makefile
This commit adds `pkger` to the Makefile, ensuring that when any changes are
made in the `templates` directory it runs. For CI, I've added a download of the
`pkger` binary.
Fixes: https://github.com/boson-project/faas/issues/230
=> chore: ensure that pkger is run when templates change

templates/go/events/handle.go
Used signature from Cloudevents Go SDK: https://github.com/cloudevents/sdk-go/blob/e35f432ede703309a1bd4c77a06f4910b3b23582/v2/client/receiver.go#L40-L55
(ust replaced `transport.Result` return value to `error` as `transport.Result` is just [wrapper](https://github.com/cloudevents/sdk-go/blob/5eff2b826cd8f26255f9f6963df66b5a6163a932/v2/protocol/result.go#L9) around `error` type and this is imho more obvious for function developers)
Fixes: #237
=> fix: correct fn signatures in Go Events template

.github/workflows/ci.yaml
I started this by trying to run a build matrix, but it got complicated pretty
quickly, since this build actually does `make cross-platform`. If we want to
also run a platform matrix when things land on `main`, I think it would be best
if we modified `pull_requests.yaml` to also run on `main` as well as on pull
requests (and be renamed).
=> chore: pull and run pkger on main branch CI

cmd/list.go
When there are no functions deployed, the `kn func list` command now says so.
Fixes: https://github.com/boson-project/faas/issues/228
=> fix: print "No functions found in [ns] namespace" for kn func list

Makefile
This will ensure that package-lock.json is not updated with patch releases
unintentionally - that should be done with intent.
=> chore: use 'npm ci' instead of 'npm install' for Node.js tests

CODEOWNERS
Introducing CODEOWNERS file, this way we are implicitly assigned for code review and approved for merging.
WDYT?
=> chore: introduce CODEOWNERS file

knative/deployer.go
Removing the name so the k8s server can fill it in with generated name, this prevents conflicts in Revision name when updating the KService from multiple places.
Fixes: #270
=> fix: server-side generated Revision name during the update

.github/workflows/pull_requests.yaml, Makefile, client.go, client_int_test.go, client_test.go, docker/runner_test.go, function_test.go, hack/allocate.sh, hack/configure.sh, hack/delete.sh, k8s/names_test.go, knative/remover.go, prompt/prompt_test.go, templates.go, templates/README.md, templates_test.go, testdata/cluster.yaml
This PR adds the scaffolding necessary to run integration tests in GitHub using a local cluster and container registry.  Also includes scripts necessary to run them locally.
Fixes #138
=> integration tests

client.go, client_test.go, cmd/deploy.go, docs/commands.md, function.go
Per Issue #272 , this PR adds the option to `deploy --build=false` such that a prebuilt image can be used and building bypassed.
=> deploy --build option

.github/workflows/ci.yaml
In an attempt to fix the missing version on CI-built binaries, the repository is now checked out for the workflow after running the release action. This should ensure that the release action has fully completed, potentially adding any version tags to the codebase, prior to build's run which utilizes this version tag to populate the resultant binary's version number.
=> ci: run release action prior to checkout

.github/workflows/ci.yaml, Makefile
For unknown reasons, the git tag for a release CI build via release-please
seems to happen after the build completes. It's a bit uncleear, but the
result is that we get v0.0.0 versions for released builds.
This commit modifies the Makefile to allow for an environment override of
the $VERS variable. Since the release-please-action documents `tag_name`
as output from the action, we can use this in CI to set the environment
variable.
=> chore: fix versioning in CI builds

docs/guides/func_yaml.md
This adds a simple explanation of each of the fields in the `func.yaml`
configuration file.
=> docs: add func.yaml field documentation

docs/README.md, docs/guides/developers_guide.md
Minor:
* adding links to the existing language guides to the Function developer guide
* adding link to the `func.yaml` guide which is coming in https://github.com/boson-project/func/pull/312
=> chore: adding references to guides

knative/deployer.go, knative/deployer_test.go
User now can use syntax like:
```yaml
envVars:
SOME_SECRET: {{env.API_KEY}}
```
=> feat: usage of local evnvvar in func cfg file

cmd/deploy.go, cmd/root.go, cmd/run.go, config.go, docker/runner.go, function.go, knative/deployer.go
There are some places where I've changed variable and function names
where it wasn't strictly necessary. If you don't mind the bit of churn
that results, changing these makes `rg -i envvars` a nice way to check
for anything that could be overlooked.
=> refactor!: change envVars to env in func.yaml

.github/workflows/ci.yaml, Makefile
After digging into the missing version tag issue a bit more, the digression did confirm that the release-please action is creating the tag asynchronously (at the octocat library level it seems, so a bit deep), as we surmised.  So no surprise there.  However, the process did turn up a couple somewhat interesting opportunities for improvement (or at least discussion) wherein we can ignore this asynchronicity by creating the tag, and in so doing enable draft releases.
First, this fixes a small bug introduced from passing the VERS as an environment variable.  While this did fix our acute issue of missing version in the released binaries caused by release-please's asynchronous tagging, it had the side-effect of removing verbose build information from our "interstitial" binaries (built between …
=> Draft releases through synchronous tagging

cmd/delete.go, cmd/delete_test.go, docs/guides/commands.md
Allows function to be delete when passing explicity name
```
$ func list | grep gofunc
gofunc            test-function  go          http://gofunc-test-function.apps-crc.testing            True
$ cd ~
$ ls -l func.yaml
ls: cannot access 'func.yaml': No such file or directory
$ func delete gofunc
Removing Knative Service: gofunc
$ func list | grep gofunc
$ 
```
=> fix: func delete with explicity name as argument (#323)

client.go, client_test.go, cloudevents/emitter.go, cloudevents/emitter_test.go, cmd/emit.go, docs/guides/commands.md, go.mod, mock/emitter.go
Adds the `kn func emit` command. Usage is:
```console
Emit event
Emits a CloudEvent, sending it to the deployed function.
Usage:
func emit [flags]
Examples:
kn func emit
kn func emit --file ./test.json
kn func emit --data "Hello World!" --content-type "text/plain" -s local
kn func emit --type my.event --sink local
kn func emit --path /path/to/fn -i fn.test
kn func emit --sink "http://my.event.broker.com"
Flags:
-c, --content-type string   The MIME Content-Type for the CloudEvent data  (Env: $FUNC_CONTENT_TYPE) (default "application/json")
-d, --data string           Any arbitrary string to be sent as the CloudEvent data. Ignored if --file is provided  (Env: $FUNC_DATA)
-f, --file string           Path to a local file containing CloudEvent data to be sent  (Env: $FUNC_FILE)
-h, --help …
```
=> Add 'kn func emit' command

go.mod
Is there a particular reason why we are still at 1.14? Knative Client is using 1.15 - we should sync that.
=> chore: bump to Go 1.15

cmd/delete_test.go, cmd/deploy.go, cmd/root.go, cmd/root_test.go, cmd/run.go, config.go, config_test.go, docker/runner.go, docs/guides/func_yaml.md, function.go, knative/client.go, knative/deployer.go, knative/deployer_test.go
Users can reference Kubernetes Secrets in the `func.yaml`, in `envs` and `volumes` sections, see the example:
```yaml
name: test
namespace: ""
runtime: go
...
volumes:
- secret: mysecret3
path: /workspace/secret
envs:
- name: EXAMPLE1
value: myvalue
- name: EXAMPLE2
value: '{{ env.LOCAL_ENV_VALUE }}'
- name: EXAMPLE3
value: '{{ secret.mysecret2.EXAMPLE3 }}'
- value: '{{ secret.mysecret }}'
```
If some Secret is not present in the cluster, function is not being deployed:
```bash
$ ./func deploy -p test                                                                                                                                           
🕒 Pushing function image to the registry
🕖 Deploying function to the cluster
Error: knative deployer …
```
=> feat: reference Secrets in `envs` and `volumes` sections in config

.github/workflows/pull_requests.yaml, hack/allocate.sh
The rest of the codebase is using Knative 0.22.0.
=> chore: e2e tests should run against Knative 0.22.0

config.go, config_test.go, docs/guides/func_yaml.md, knative/deployer.go
Follow up on #369, users can reference Kubernetes ConfigMaps in the `func.yaml`, in `envs` and `volumes` sections the same way it is done for Secrets, see the example:
```yaml
name: test
namespace: ""
runtime: go
...
volumes:
- configMap: mycm3
path: /workspace/configmap
envs:
- name: EXAMPLE1
value: myvalue
- name: EXAMPLE2
value: '{{ env.LOCAL_ENV_VALUE }}'
- name: EXAMPLE3
value: '{{ configMap.mycm2.EXAMPLE3 }}'
- value: '{{ configMap.mycm }}'
```
Relates: #362
=> feat: reference ConfigMaps in `envs` and `volumes` sections in config

docs/guides/developers_guide.md
* The link from the developers guide to the cli command reference guide was missing the file extension
=> chore: fix dead link on the developers guide.

client.go, client_test.go, cmd/create.go, cmd/delete_test.go, config.go, docs/guides/commands.md, docs/guides/func_yaml.md, docs/guides/golang.md, docs/guides/integrators_guide.md, docs/guides/nodejs.md, docs/guides/python.md, docs/guides/quarkus.md, docs/guides/typescript.md, function.go, templates.go, templates_test.go, test/_e2e/cmd_create_test.go, test/_e2e/cmd_emit_test.go, test/_e2e/func_test_proj.go, test/_e2e/trigger_events_test.go, test/_e2e/trigger_http_test.go, test/_e2e/update_test.go
This PR contains the updates from PR #378 and PR #379.  There were substantive differences between the two, but contained a very high level of overlap, so the process was:  Apply the changes from 378, then apply 379, rebasing and resolving conflicts.
I found nothing during the merge that I think would be contentious, but since they were not identical in their approach, this PR gives us a chance to thumb through the summation of the changes before... committing (pun intended).
=> refactor!: trigger to template, templates to packages

config.go, config_test.go, docs/guides/func_yaml.md, function.go, knative/deployer.go
Users can specify (autoscaling) options in `func.yaml`. The options are added/update/removed based on the content in `func.yaml` file.
If there's a demand, we can add these options as flags to `func deploy` command (same way they are exposed in `kn service create/update` -> with removal option), but I think that specification in config file is enough.
```yaml
name: test
namespace: ""
runtime: go
...
options:
scale:
min: 0
max: 10
metric: rps
target: 75
utilization: 75
```
`concurrency.limit` will be added in the following PR, which will handle resource limits/requests as proposed here: https://github.com/boson-project/func/pull/374#discussion_r649070413
Relates: #164
Fixes: #264
=> feat: allow setting autoscaling options to deployed KService

docs/guides/commands.md
Fixing typo and adding link to the project for reference.
=> chore: fix typo in commands guide

cmd/config.go, cmd/config_volumes.go, config.go, docs/guides/commands.md, go.mod, go.sum, k8s/client.go, k8s/configmaps.go, k8s/secrets.go, knative/client.go, knative/deployer.go, knative/describer.go, knative/lister.go, knative/remover.go
Interactive prompt for managing function configuration - this PR adds Volumes (Envs will be in a separate PR).
`func config` - starts interactive prompt, wizard that let's you select resource and the requested operation
`func config volumes` - list configured Volumes
`func config volumes add` - starts interactive prompt, wizard that let's you add Volume mount to the configuration. It does a lookup for existing Secrets and ConfigMaps in the cluster and namespace.
`func config volumes remove` - starts interactive prompt, wizard that let's you remove Volume mount from the configuration.
Relates: #362
=> feat: `func config volumes` - interactive prompt

buildpacks/utils.go, cmd/create.go, config.go, config_test.go, utils/names.go, utils/names_test.go
Minor improvement, let's check that the input k8s Env Variable name is valid:
```terminal
./func deploy                                                                                                  
Error: 'func.yaml' config file is not valid:
env entry #1 has invalid name set to "in,valid"; a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')
```
I have moved the buildpacks related utils to buildpacks package to prevent circular dependencies.
Relates: #362
=> src: validate Env Var name

cmd/describe.go, cmd/format.go, cmd/list.go
=> feat: add a URL output type for `func describe`

cmd/config.go, cmd/config_envs.go, cmd/config_volumes.go, config.go, docs/guides/commands.md
Interactive prompt for managing function configuration - this PR adds Environment variables
`func config envs` - list configured Environment variables
`func config envs add`- starts interactive prompt, wizard that let's you add Environment variable to the configuration. It does a lookup for existing Secrets and ConfigMaps in the cluster and namespace.
`func config envs remove`
- starts interactive prompt, wizard that let's you remove Environment variable from the configuration.
Relates: #362
https://user-images.githubusercontent.com/726523/122539154-90687980-d027-11eb-97a8-0d794897ee0a.mp4
=> feat: `func config envs` - interactive prompt

config.go, config_test.go, docs/guides/func_yaml.md, knative/deployer.go
Follow up on https://github.com/boson-project/func/pull/374
Users can specify resource requests/limits (cpu&memory) and concurrency limit, which are applied on deployed KService.
```yaml
name: test
namespace: ""
runtime: go
...
options:
scale:
min: 2
...
resources:
requests:
cpu: 100m
memory: 128Mi
limits:
cpu: 1000m
memory: 256Mi
concurrency: 100
```
Fixes: #383
=> feat: allow setting resource requests/limits

buildpacks/utils.go, cmd/create.go
Minor improvement, because we know all the runtimes, we can use Select instead of Input when interactive mode is selected in `func create`
=> src: `create`- use Select for specifying runtime in interactive mode

client_test.go, templates_test.go
Small PR updating the client unit tests to use the same test directory helper as the others.
=> src: test temp dir helper standardization

cmd/create.go, cmd/create_test.go, utils/names.go
Refactors the create command to be testable, and adds a test which utilizes this structure.
Commands (cobra.Command instances) are created with a reference to a fn.Client creator (factory-ish pattern).  This reference is used in a closure for the RunE delegate.  In this way, the effective instance of fn.Client can be swapped out for testing.
If this looks acceptable to folks, I'll use the pattern to test the remaining CLI-centric features of the Extensible Templates FT.
=> Testable Commands

buildpacks/builder.go, client_int_test.go
If you pass `io.WriteCloser` as loggin output for `pack` it will close it, `os.Stdout` does implement `io.WriteCloser` so it ended up closed which is not really good. I added wrapping struct that implements only `io.Writer` to fix the issue.
=> fix: closing stdout

.github/workflows/pull_requests.yaml
I noticed during the frenzy to get integration and e2e tests working in CI that one of our jobs was still using @lkingland's fork. The upstream has those changes now.
=> chore(CI): use container-tools/kind for integration tests

.github/workflows/pull_requests.yaml, client.go, cmd/build.go, cmd/create.go, cmd/create_test.go, cmd/delete.go, cmd/delete_test.go, cmd/deploy.go, cmd/describe.go, cmd/emit.go, cmd/list.go, cmd/run.go, knative/client.go, progress/progress.go
Restructures commands to accept a fn.Client constructor on command instantiation.  This allows the concrete implementations, or entire client, to be mocked for testing.  Also includes some minor refactoring as necessary to shoehorn into the pattern.
=> src: testable commands

docs/guides/golang.md, docs/guides/nodejs.md, docs/guides/python.md, docs/guides/quarkus.md, docs/guides/typescript.md
=> docs: fix link to func.yaml docs in language guides

buildpacks/builder.go
=> fix: do not trust builder when using podman

cmd/create_test.go, cmd/root.go
The default location of a user's Functions config location is $XDG_CONFIG_HOME/func.  This PR ensures that this is respected by adding a test which verifies the correct functioning of its only current usage:  the location of local non-core (extensible) template repositories.
:broom:  Cleans up current configPath derivation function
:broom:  Adds unit test confirming default value and respect of XDG_CONFIG_HOME
=> test: confirm config search path

.chglog/config.yml, CHANGELOG.md, README.md, docs/getting_started_kubernetes.md, docs/guides/developers_tutorial.md, docs/installing_cli.md, templates/go/events/README.md, templates/go/http/README.md
As the title says, pretty much a replace of `github.com/boson-project/[func|faas]` with the new coordinates.
=> Change github.com links to the new home

.github/workflows/ci.yaml
:bug: Fixes CI on `main`. In a recent refactoring, some copy paste resulted in `./pkger` being
undefined in CI. This change fixes that.
/kind bug
=> chore(ci): fix main CI reference to downloaded pkger

cloudevents/emitter.go
* :gift: if `func emit` gets a CloudEvent in response, print it for the user
The CloudEvent SDK will provide any event included in the response as a
return value from `Request()`. If it does, print it out. It makes the
experience nicer.
For example, if I run the default TypeScript event function locally, this
is what `kn emit...` looks like.
```
❯ ./func emit --sink local --data '{"hello": "world"}'
Context Attributes,
specversion: 1.0
type: echo
source: function.eventViewer
id: d7d81ccc-a365-4433-be6b-7edfa43ca360
time: 2021-07-27T18:57:03.147Z
datacontenttype: application/json; charset=utf-8
Data,
{
"hello": "world"
}
```
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/388
```release-note …
```
=> feat: print emit response output if it's a cloudevent

CODEOWNERS
:broom:  remove CODEOWNERS
It is my understanding that CODEOWNERS is deprecated in favor of OWNERS due to Prow integration.
/kind cleanup
=> chore: removes deprecated CODEOWNERS file

Makefile
:wastebasket:  remove `rm pkged.go` from `make clean`
This was an incorrect addition on my part.  Clearing this generated file results in overlapping the developer use cases of updating templates with that of modifying core source.   In particular, if I am modifying core source, and want to `make clean && make` for any reason, it does not feel right to have that trigger a rebuild of pkged.go.  The two development loops should be kept separate such that modifications to the core source code should not require the installation and running of pkger in any circumstance.  This should only be required if mutating embedded templates.
/kind chore
=> build: remove pkged.go from make clean

OWNERS
Add @jcrossley3 @jrangelramos and @dsimansk as reviewers in the OWNERS file.
- Jim has made several nice contributions with the Rust templates and buildpacks, and his insight when reviewing these is very helpful!
- Jefferson has helped immensely with e2e, integration and other tests/validation
- David has been essential to our `kn` integration
Happy also to discuss adding these three as approvers as well, if that's a better course.
=> chore: add some collaborators to the OWNERS file

progress/progress.go
- :bug: Fix bug of progress indicator on windows (there were troubles with unicode chars)
resolves #352 #354
=> fix: use ascii chars in progress indicator on win

docs/guides/nodejs.md
- :book: adding some documentation around how to set logging levels in Node.js
Note that these documents will likely need to move out of this repo.
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/328
=> docs: add section about Node.js log levels

cmd/config_envs.go, cmd/config_labels.go, cmd/root.go, cmd/root_test.go, config.go, config_test.go, docs/guides/func_yaml.md, function.go, knative/deployer.go, schema/func_yaml-schema.json, utils/names.go, utils/names_test.go
- :broom: use `key&value` for Labels instead of `name&value` so we are aligned with Kuberentes https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
- :gift:  added `envs` and `labels` validation to the func.yaml schema
Fixes #336
=> feat!: use key&value for Labels

client.go, cmd/emit.go, cmd/info.go, docs/guides/commands.md, knative/describer.go, test/_e2e/cmd_describe_test.go, test/_e2e/e2e_functions_test.go
- :broom: Change the `describe` command to `info`
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/337
The describe command conflicts sematically with kubectl describe.
```release-note
The `describe` command has been renamed to `info` to reduce conflict with the `kubectl` and `kn` commands of the same name. The behavior is otherwise identical.
```
**Docs**
Documentation changes are included in this PR.
=> feat!: change `describe` command to `info`

client_test.go, function.go, repositories.go, templates_test.go
:broom:  template tests use public api
The code structure is now such that the template test suite can reach all code paths via the public client API (the desired state), and as such the tests can be moved out of the `function` package into `function_test`; a change which ensures that tests never become overly dependent on implementation details as they are unable to access private package structures.
/kind techdebt
=> src: template tests use public api

templates.go
- :bug: explicitly set template directory file mode to 0755
For some reason when a node in the git in-memory file system is
Stat()ed, if it's a directory the mode bits are 0644 which is not
correct, and causes a failure when trying to write the templates.
This commit explicitly sets the file mode for all directories to
0755.
/kind bug
=> fix: support nested subdirs in remote templates

docs/guides/podman.md
Using systemctl is a better idea because users can utilize other subcommands like `status` or `stop` to further manage the podman service.
- :broom: Clean up commands to better follow standards and docs
/kind cleanup
=> Using systemctl to manage podman user owned service

client_int_test.go, templates.go
- :broom: Remote templates integration test
Adds an integration test which confirms remote repo directory and file modes retained
=> Remote file modes integration test

cmd/create.go
- :broom: fix identation of create command output when specifying a repository
/kind cleanup
=> style: create command output formatting for repository option

cmd/config_labels.go
- :bug: Fix `func config label` panic due to unregistered flag.
=> fix: `config labels` panic

client.go, client_test.go
- :gift: Recognize Builders, Builder and Buildpack in Client API function configuration when creating a new project
We have provided support for modifiying the builders and buildpacksin `func.yaml` but until now there has not been a way to set these values when creating a new function with `client.Create(cfg)`. Any values provided in `cfg` for the builders and buildpacks were ignored and the builtin defaults were used.
=> feat: builders/buildpacks configured in client

client.go, progress/progress.go
- :broom: Cleaning spinner for build and deploy commands for Windows platform
/kind cleanup
Fixes #352
=> fix: control chars on progress listener for Windows OS

client.go
- :broom: fix typo in deploy command output
/kind chore
=> chore: fix typo in deploy command output

test/_e2e/cmd_build_test.go, test/_e2e/cmd_deploy_test.go, test/_e2e/config.go, test/_e2e/e2e_remote_repository_test.go, test/_e2e/func_test_proj.go
- :broom: Additional e2e test for remote repository
Added a scenario for extended tests that creates and deploy a function initiated from a remote repository (in this case https://github.com/boson-project/test-templates)
=> test: adding e2e test for remote repository

cmd/root.go, cmd/root_test.go, plugin/plugin.go
- The example message changes depending on the command being executed as standalone or as a plugin for the `kn` executable
Fixes #214
=> chore: example message changes between standalone and plugin

.github/workflows/knative-style.yaml
- :bug: fix CI error in the Go Lint step of the Lint action.
This is a workaround to [an open issue in golangci-lint-action](https://github.com/golangci/golangci-lint-action/issues/244).
An [example of the error](https://github.com/knative-sandbox/kn-plugin-func/pull/490/checks?check_run_id=3551662472):
```
Error: /usr/bin/tar: ../../../go/pkg/mod/github.com/client9/misspell@v0.3.4/legal.go: Cannot open: File exists
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 2
```
/kind bug
=> ci: avert tar error in lint action

client.go, client_test.go, repositories.go, repositories_test.go, repository.go
- :gift: Adds effective runtimes list to client API
Prerequisite for #451 
=> feat: client effective runtimes list

cmd/repository.go, repositories.go
- :bug: removal of repositories
Removes the default value from prompt options and adds a backup assertion on removal.
Works around a strange (bug?) behavior in the Prompt library where, if a default value for a set of Prompt options is set to the empty member, no value is permitted to pass through even though it is set as required _and_ the UI shows the first option as selected.  This bug is equivalent to a set of radio buttons showing in the UI the first element selected by default, but instead behaving as though no radios were selected on hitting submit (no initially selected radios).  This issue is an edge case and only seemed to rear its head when not interacting with the prompt in any way other than hitting enter for defaults.
The fix (workaround, really) is to remove the explicit …
=> fix: prompt default options

.github/workflows/knative-style.yaml, .golangci.yaml
As per title, this reverts the golangci-lint action to the default to unblock automatic action updates. The timeout argument is added to golangci-lint's config.
=> Revert linting action to the canonical version

knative/deployer.go
There was a `fmt.Println()` statement not wrapped by the verbose flag that resulted in deployments looking like this:
```
> kn func deploy
Deploying function
🕕 Deploying function to the cluster
Function deployed at URL: http://tscript-default.lball-cluster-0c576f1
Function deployed at URL: http://tscript-default.lball-cluster-0c576f1a70d464f092d8591997631748-0000.us-east.containers.appdomain.cloud
```
=> fix: hide a fmt.Println behind verbose flag

hack/update-pkger.sh
The script depends on GNU-sed command syntax, which is not installed on OS X by default (OSX uses BSD).  This update changes the solution to using a touched file rather than sed. 
A concern was raised that this solution may interfere with other automated tasks, such as the license checker, so we should watch carefully and either back it out, or propose a different solution, if that does indeed happen.
/kind bug
=> fix: update-pkger.sh sed error on osX

cmd/config.go
fix: Environment values -> Environment variables
I've just recently noticed that if you run `func config` it will give you option to configure `Environment values` not `Environment variables` as it should be and it is being used in the rest of the commands. 
So fixing this typo which happened I don't know why 🤷‍♂️
=> fix: Environment values -> Environment variables

cmd/config_envs.go, config.go, config_test.go, utils/names.go, utils/names_test.go
As per: https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object
> Each key under the data or the binaryData field must consist of alphanumeric characters, -, _ or .
Our validation only allowed alphanumeric and underscore before, fixing this.
=> fix: ConfigMap/Secret key validation

cmd/list.go
`func list` prints the header when it gets `No functions found`.
This patch stops displaying the header.
ASIS
```
$ func list
No functions found
NAME  NAMESPACE  RUNTIME  URL  READY
```
The header `NAME  NAMESPACE  RUNTIME  URL  READY` should not be printed.
TOBE (by this patch)
```
$ func list
No functions found
```
/kind cleanup
=> Do not print header when `func list` does not find any functions

client.go, client_test.go, cmd/delete_test.go, config.go, function.go, schema/func_yaml-schema.json
- :gift: function creation timestamp
It is becoming clear that a timestamp of when a Function successfully completed the creation process will be valuable.  In particular this will help with a few forthcoming PRs currently WIP, I'm separating this into its own PR to solicit feedback such as consequences unanticipated.
=> feat: function creation timestamp

cloudevents/emitter_test.go, docker/credentials_helper_test.go, docker/pusher_test.go, knative/deployer_test.go, repository_test.go
- :broom: adds missing build tag to some unit test files
The integration tests and unit tests are currently expected to be disjunct sets.  While we may change to being additive in the future, this change makes us consistent by adding the integration exclusion tag to a few non-integration test files where it was currently missing.
=> chore: build tag consistency

config.go
- :broom: extract config validation error text formatter
Minor cleanup to address config validation which is quite user friendly, but whose code was a little bit unwieldy.  
In particular the code now fails fast on errors reading func.yaml, extracts the unmarshaling error formatter, extracts logical validator, collapses validation string formatting logic a bit and switches to a string builder for clarity.
=> chore: extract config validate

knative/deployer.go, knative/deployer_test.go
:gift: This change adds POD_NAME as an environment variable for a deployed
function using the Kubernetes downward API. An alternative means of exposing
this information would be through the filesystem. For example, a file at
`/etc/func/pod_name` would contain the pod's name. I chose to use the env
as the place to surface this because it was easier to implement, and likely
easier to consume for a function developer.
The motivation for this change is that the Node.js and TypeScript invocation
runtime will be exposing telemetry/metrics through Prometheus at a `/metrics`
endpoint (see: https://github.com/boson-project/faas-js-runtime/pull/109).
The OpenTelemetry specification has some experimental labels for function
runtime environments which don't specifically mention pod name (the spec
is …
=> feat: add POD_NAME as an environment variable

knative/deployer.go, knative/deployer_test.go
This reverts commit 64473b7197bb5a821b6724a8b914784891b1a828.
The `/lgtm` arrived before integration tests completed, and unfortunately, setting this value in the container spec is prohibited by knative, it seems.
```
client_int_test.go:134: knative deployer failed to deploy the Knative Service: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: must not set the field(s): spec.template.spec.containers[0].env[1].valueFrom.fieldRef
```
=> Revert "feat: add POD_NAME as an environment variable (#660)"

docker/docker_client.go, docker/docker_client_test.go
- :bug: Fix issues with TCP TLS connection.
resolves: #668
=> fix: use default socket path for TCP connections

function_migrations_unit_test.go, function_test.go, function_volumes_unit_test.go, repositories_test.go, repository_test.go, templates_test.go
I started trying to forward-port #591 and got sidetracked by migrating to `sigs.k8s.io/yaml`, which was causing a test to fail. So I cleaned up the tests, and will send the `sigs.k8s.io/yaml` change next.
- switch `reflect.DeepEqual` to `cmp.Diff` for better readability
- some `cmp.Diff` arguments were reversed(!)
- coverted one test into a table test
- cleaned up some misleading error messages
- preferred `testing.Error` to `testing.Fatal` to enable collecting more errors at once
/kind cleanup
=> Clean up tests

Makefile
func.yaml config is now being generated from `function.go` and not `config.go` as it was before. Therefore we need to change the target for schema generation.
=> fix: schema-generate should point to `function.go`

client.go, client_test.go, cmd/create.go, cmd/repository.go, cmd/root.go, docker/pusher.go
- :gift: Ensure config and repos paths exist on client instantiation
- :broom: Cleanup existing creation logic invoked by cli
Finalizes the move of config and repositories-path evaluation and creation into the core by creating the directories on instantiation (previously required the CLI), including tests.
Fixes #682
=> feat: ensure config fs structure

test/_e2e/cmd_config_envs_test.go, test/_e2e/cmd_config_volumes_test.go
- :broom: revert usage of a fork of the test-templates repository
/kind chore
Depends on https://github.com/boson-project/test-templates/pull/5
=> chore: revert using a fork of boson-project/test-templates

.github/workflows/ci.yaml
Since we are moving towards using the Knative tooling for releases, and because release-please-action will not work in the repository due to knative branch protection rules, I'm removing this from CI entirely as we work towards an alternative solution.
- :broom: remove release-please-action from CI
/kind chore
=> chore: remove release-please from ci

cmd/build.go, cmd/build_test.go
In https://github.com/knative-sandbox/kn-plugin-func/commit/ccf00152be0ceba1794267f8e03a09cb32fee514
the behavior of `NewFunction()` changed slightly, such that it no longer actually
works without a provided and valid path. This was not caught in any of the
tests, because it's the CLI code that was making this call, and the end to end
tests that exercise the build command, use the `--registry` flag, causing
the repository validation code path to be slightly different.
:broom: This commit just adds the path so that `func build` without a `--registry` flag will work again.
EDIT: Converting to a draft, because really, any registry should be validated even if it's provided as a CLI flag. I will add that validation and a test.
/kind fix
=> fix: make registry validation work again

client.go, client_int_test.go, cmd/create.go, docker/pusher.go, repositories.go
Cleans up instantiation logic and config/repo path accessors/creators, fixing a bug or two along the way.
- :broom:  Enables separate paths: when repositories path is outside config path
- :broom:  Removes need to use a client to trigger creation of paths by re-enabling static path accessors
- :broom: Cleans up instantiation logic
- :broom: Removes some unused accessors
/kind techdebt
=> refactor: config path accessors with instantiation cleanup

cmd/build.go, cmd/config.go, cmd/config_envs.go, cmd/config_labels.go, cmd/config_volumes.go, cmd/delete.go, cmd/deploy.go, cmd/emit.go, cmd/info.go, cmd/list.go, cmd/root.go, cmd/run.go
:broom: refactor path and namespace CLI flags for consistency across commands
These flags are used by multiple commands, and explicitly setting them for
each command risks errors that may not be easily detected (see the deleted
flag text for `namespace` in deploy.go). The downside to this is that wording
is not sligtly tweaked for the command - see again some of the removed text
for `namespace` that was slightly different for each command, but usefully so.
I'm not 100% convinced this change is needed, since it does reduce the flexibility
of the user facing text. But if it had existed before we wouldn't have had
incorrect text for `deploy`.
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/221
/kind chore
=> chore: refactor CLI flags for consistency across commands

client_int_test.go, docker/credentials_helper_test.go, docs/DEVELOPMENT.md, function_unit_test.go, hack/allocate.sh, hack/registry.sh, hack/test-integration-podman.sh, test/_e2e/config.go, test/_e2e/main_test.go, testdata/cluster.yaml
:bug: default integraiton port conflict with Mac OS Monteray's new AirPlay listener
Moves the integration testing port into the unregistered range (above
49151) to minimize potential future conflicts.
/kind bug
Fixes #700
=> fix: move integration port to unregistered range

client_int_test.go, hack/allocate.sh, hack/test-integration-podman.sh, test/_e2e/config.go, test/_e2e/main_test.go
The localhost alias was causing problems with new approach for registry access.
The new access is done directly not via daemon.
This renders any insecure registry exception in daemon config irrelevant.
The library facilitating registry access seems to allow insecure registry on localhost only.
=> fix: revert hostname alias

cmd/build.go, cmd/deploy.go, docker/credentials_helper.go, docker/pusher.go, docker/pusher_test.go
Allow to set custom credential loader.
This might be useful if the registry shares credentials with some other system, e.g. OpenShift builtin registry has the same credentials as the k8s cluster.
=> Refactor credential provider

cmd/func/main.go, http/transport.go, k8s/dialer.go
- :gift: use in cluster dialer by default:
This sets http.DefaultTransport to our specialized RoundTripper.
The RoundTripper first tries dial in standard way.
If dial operation fails due to hostname resolution error the in cluster dialer will be used.
- :broom: dialer pod auto-exit:
The pod should exit (be Completed) when func exits (even in case of SIGKILL).
=> feat: custom default HTTP transport

cloudevents/emitter.go, cmd/emit.go, cmd/func/main.go
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/715
=> src: revert global dialer

hack/update-pkger.sh
:bug: adds the missing build stanza to pkged.go by running gofmt which includes the migration in 1.17
Fixes #725
=> fix: ensure pkged.go is migrated

knative/deployer.go, knative/lister.go
Proposal:
We should change labels that are applied to Functions from `boson.dev` -> `function.knative.dev` (or `func.knative.dev`).
I am not sure which components are dependent on this, so we should be careful about the change.
=> feat!: use `function.knative.dev` for Functions related labels

.ko.yaml
- :gift: Adding `ko` manifest to produce `func` container. 
You can produce a container by running:
```
ko publish ./cmd/func
```
Fixes #691
=> Adding ko to produce image with func command

.github/workflows/ci.yaml, .ko.yaml
- :gift: Adding `ko` manifest to produce image with `func` command. 
- :gift: `ghcr.io/knative-sandbox/kn-plugin-func/func:latest` image is being produced for each commit on `main` branch
You can produce a container by running:
```
ko publish ./cmd/func
```
Fixes #691
=> src: add `ko` to produce image with `func` command in CI

client.go, cmd/build.go, cmd/build_test.go, cmd/deploy.go
This is needed to have standalone `deploy` Tekton task.
Basically implementing the same functionality that has been done in https://github.com/knative-sandbox/kn-plugin-func/pull/681 for `build`.
- :gift: add possibility to disable pushing of image in `deploy` command
Relates: #620
=> feat: add possibility to disable pushing of image in `deploy` command

client.go, cmd/build.go, cmd/build_test.go, cmd/deploy.go
Reverts knative-sandbox/kn-plugin-func#736
This change hasn't been ready yet/
=> Revert "feat: add possibility to disable pushing of image in `deploy` command"

k8s/labels/labels.go, k8s/persistent_volumes.go, k8s/role_bidings.go, k8s/secrets.go, k8s/service_accounts.go, knative/deployer.go, knative/lister.go, pipelines/tekton/pipeplines_provider.go, pipelines/tekton/resources.go
Adding a label `function.knative.dev/name: functionName` to every resouce created for a Function, so we can easily identify them.
- :gift: add a label to every resouce created for a Function
Fixes: #753
=> feat: add a label to every resouce created for a Function

buildpacks/builder.go
Bumps lifecycle mirror to version 0.13.2 (the latest), and adds `docker.io/paketobuildpacks` as a trusted builder prefix.
=> chore: bump lifecycle version to 0.13.2

hack/allocate.sh, hack/delete.sh, hack/registry.sh
- :broom: remove need for hosts entry for local clusters
We can now simply refer to localhost throughout.  This PR reflects that in the local allocation system.
/kind techdebt
=> src: remove need for hosts entry for local clusters

http/transport_test.go
On CI machines the image registry is present and reachable.
That causes the actual registry, not mock server, is accessed by the test.
=> test: fix URL

test/presubmit-tests.sh
- :broom: skip integration tests in upstream knative release infra
This is temporary to see if we can actually get releases going without having the additional burden of ensuring that a cluster and docker are available for tests.
/kind chore
=> chore: skip integration tests in upstream release scripts for now

Makefile, hack/release.sh
The upstream release pipeline does not tag the source until the build and
tests have successfully completed. This should allow for our release builds
to pick up the knative infra TAG environment variable when building releases.
=> chore: update Makefile and hack/release.sh to accept TAG

cmd/build.go, cmd/completion.go, cmd/config.go, cmd/config_envs.go, cmd/config_volumes.go, cmd/create.go, cmd/delete.go, cmd/deploy.go, cmd/func/main.go, cmd/info.go, cmd/invoke.go, cmd/list.go, cmd/repository.go, cmd/root.go, cmd/root_test.go, cmd/run.go, cmd/version.go, plugin/plugin.go
* Command tree is build from root, not by ad hoc attaching in `init()` blocks.
* Getting rid of `FUNC_PARENT_COMMAND` and `prefix` stuff in favor of `cmd.Root().Name()`.
=> Cleanup commands

client_int_test.go, cmd/build.go, cmd/completion_util.go, cmd/delete.go, cmd/deploy.go, cmd/info.go, cmd/invoke.go, cmd/list.go, docker/pusher.go, docker/pusher_test.go, knative/deployer.go, knative/describer.go, knative/lister.go, knative/remover.go, pipelines/tekton/pipeplines_provider.go
Constructors do only necessary initialization with no possible error.
Errors are deferred until some actual operation is being done.
This allows to initialize all parts of `fn.Client` at once with no error.
We need this to be able to create a shared factory function of `fn.Client` for multiple commands.
Without this such a factory is not possible because the function could fail while initializing something that won't be actually used.
For example: `func create` doesn't need `k8s` configuration set up, but the command would still fail because of it.
=> src: error-less ctors

knative/describer.go
If eventing is not installed, the user should still be able to get info and use
`kn invoke`. Don't fail, if `describe` finds eventing missing.
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/822
/kind fix
=> fix: don't fail info/invoke if eventing missing

cmd/build.go, cmd/build_test.go, cmd/client.go, cmd/create.go, cmd/create_test.go, cmd/delete.go, cmd/delete_test.go, cmd/deploy.go, cmd/info.go, cmd/invoke.go, cmd/list.go, cmd/root.go
Added single common factory function of `fn.Client` for all commands.
This allows to set all important settings at one place.
=> Single common `fn.Client` factory for all commands

cmd/create.go, cmd/invoke.go, cmd/root.go
- :bug: select prompt option based on flag or default
Fixes #819
Fixes #820 
Related issue #814
/kind bug
=> fix: defaults for prompt from flags then options

docs/guides/podman.md
In the newer versions of `func` there is no need for starting the service and setting the `DOCKER_HOST` envvar.
It should be handled automatically.
=> Update guide for podman

cmd/root_test.go
- :broom: check the possible error returned from `cmd.Execute()` in root_test.go in order to satisfy linting and fix CI
/kind cleanup
=> chore: accommodate knative's go linter

go.sum
- :bug: Fix checkum for github.com/tektoncd/cli
/cc @lance @matejvasek
=> Fix checkum for github.com/tektoncd/cli

Makefile, docker/creds/credentials.go, docker/creds/credentials_test.go, docker/docker_client_test.go, repositories.go, repositories_test.go, repository.go, templates_test.go, testing/testing.go
* force unit test run by using `.PHONY` in `Makefile`
* fixed issues related to using back slash in path part of URI
* disabled few tests on Windows since I am not able to debug it
=> Windows unit test fixes

client.go, cmd/deploy.go, cmd/deploy_test.go, go.mod, vendor/modules.txt
- New flags added as counter part to `func.yaml` git configuration
- Git flags are no longer saved to `func.yaml`
/kind <kind>
Fixes #765
```release-note
`--git-url` `--git-branch` and `--git-dir` flags added for remote builds
```
**Docs**
```docs
```
=> added git related flags for remote builds

.gitignore, templates/go/cloudevents/README.md, templates/go/cloudevents/handle.go, templates/go/cloudevents/handle_test.go
Fixes #839 
- :broom: function template uses signature which expects a CloudEvent and returns a CloudEvent
- :broom: add example function to go template, this function uses the same events as the spring-boot template
- :broom: test added to check correct events and payloads
=> Adding sample function in go template

cmd/create.go, cmd/invoke.go, cmd/root.go
Small change to use `cmd.Root().Use` for subcommand help text because `.Name()` is truncated, leading to incorrect values when run in plugin mode (see #872)
- :bug: fix help text subcommand prefixes when a plugin
/kind bug
Fixes #872
=> fix: use full root name for cmd help prefixes

cmd/build.go, cmd/config.go, cmd/config_envs.go, cmd/config_labels.go, cmd/config_volumes.go, cmd/delete.go, cmd/deploy.go, cmd/info.go, cmd/invoke.go, cmd/list.go, cmd/repository.go, cmd/root.go, cmd/run.go, cmd/version.go
- :gift: all command help text template preprocessed
In preparation for a complete update of all command help text, this PR updates all commands to have their help text passed through a template preprocessor which, by default, provides the effective command name.
Fixes #216
=> feat: command help text template preprocessing

cmd/root.go, cmd/root_test.go, cmd/version.go
The root and version commands were far out of sync with more recent command structures.  This minor PR updates them to the more recent format, updates their help text, and explicity references verbosity level in the version command.
- :broom: Update root command structure to match updated command structure
- :broom: Update root help text to match recent structure and deemphasize explicit Function name
- :broom: Update Version command to match updated command structure
- :broom: Adds an explicit check for verbosity in Version to fix what appears to be a bug
- :broom: Cleans up Version verbosity logic to be more clear about defaults
/kind cleanup
=> src: update root and version structure and help text

filesystem_test.go
Make test more permissive since only that really matters is that whether the file is executable for owner.
=> Relax permission check only to owner exec perm

buildpacks/builder.go, client_int_test.go, cmd/client.go, cmd/completion_util.go, cmd/root.go, cmd/run.go, cmd/version.go, docker/pusher.go, docker/pusher_test.go, docker/runner.go, docker/runner_test.go, knative/deployer.go, knative/describer.go, knative/lister.go, knative/remover.go, openshift/openshift.go, pipelines/tekton/pipeplines_provider.go, progress/progress.go
**tl;dr** Probably best to use _either_ constructor args _or_ struct member initialization and not mix.  We have chosen constructors for package public API and struct members for package internal implementations.  This enforces that choice with regards to the oft-ignored verbosity flag.
- :broom: Moves verbosity flag to constructor arg
This rectifies a long-standing inconsistency where, early in the system's evolution all subsystems were initialized as simple structs.  When we moved to using proper constructors, the Verbosity flag was left as a struct member.  This is a bit confusing and awkward because it mixes constructor-based configuration with the direct setting of struct members.  The former is often best for external package APIs, the latter is often best for internal.  This …
=> src: promote verbosity to constructor arg

.github/workflows/ci.yaml, Makefile, generate/templates/main.go
Changes:
* Generate templates zip unconditionally (i.e. no `make` prerequisites).
Rationale:
* The way we create prerequisites (the `find` command) we cannot detect deleted files.
* The generation is fast (around 500ms) so we can afford that.
* Some tiny performance tweaks.
* Test embedded templates content on push to `main`.
The test has to run prior to `make test` because the `test` recipe enforces generation of the templates zip.
It would prevent test from being run against git committed template.
=> Generate templates zip unconditionally

generate/templates/main.go
The `goByteArrayWriter.Write()` shall return number of dumped bytes (hex literals) not number of bytes written to underlying writer (which is approximately 5x more).
=> Fix return value of goByteArrayWriter.Write()

ssh/terminal.go
Tell user what to put into ssh config file so the server key is trusted.
=> Hint to user when ssh server key is not known

repositories_test.go, repository.go
- :bug: Repositories missing .git
Repositories added via `func repo add ...` were missing the .git directory when installed locally.  The intent of `func repo add` was to be functionally equivalent to a `git clone`, so missing the .git directory is a bug.  This is evidenced by the downstream bug that reading metadata, such as the source URL, failed due to the missing metadata directory.
Note that existing (installed) repositories will need to be removed and re-added to be correctly installed.
This fixes the aforementioned problem of a missing remote URL when listing repositories in verbose mode (#891)
/kind bug
Fixes #891
=> fix: full clone of template repos on add

client.go, client_test.go, cmd/client.go, cmd/create.go, cmd/create_test.go, cmd/repository.go, cmd/repository_test.go, docs/guides/commands.md, repositories_test.go, repository_test.go, templates_test.go
:broom: Rename Repositories to RepositoriesPath
:broom: Relegates RepositoriesPath to an environment-varible-only setting
/kind cleanup
Fixes #896
=> src: differentiate repository from repositories

docs/guides/podman.md
- 📖   This commit adds more documentation for using podman, specifically in this case, connecting to and using a remote podman service from a Mac computer.
=> doc: add documentation for using podman remotely

.github/workflows/ci.yaml, Makefile
This commit adds a `make` target for `darwin-arm64` and changes the original `darwin` target to `darwin-amd64`.
Might fix: https://github.com/knative-sandbox/kn-plugin-func/issues/377
/kind chore
```release-note
Added support for Apple M1 native binary
```
=> chore: add Apple M1 build in cross-platform target

openshift/openshift.go
The user name from the config is invalid sometimes.
We can use `openshift` user name with user's token (it could be almost any other non-empty uname without colons in it).
```release-note
Fix issues with pushing to OpenShift's integrated registry when uname `kube:admin`
```
=> Use "openshift" uname for OpenShift image registry

docs/guides/on-cluster-build.md, k8s/secrets.go, pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml, pipelines/tekton/client.go, pipelines/tekton/pipeplines_provider.go, pipelines/tekton/resources.go, pipelines/tekton/tasks.go
- 🎁 on cluster build doesn't require privileged cluster permissions
- 🎁 uses custom version of `buildpacks` Tekton task -> there is added section in `results` step, that stores produced image name and sha to `func.yaml`.
Fixes #848
=> feat: on cluster build doesn't require privileged cluster permissions

k8s/logs.go, pipelines/tekton/pipeplines_provider.go
Return log message for a failed PipelineRun, returns log from a container where the failing TaskRun is running, if available.
eg:
```
./func deploy -p test-function
🕛 Creating Pipeline resources
🕒 Running Pipeline: Fetching git repository with the function source code
Error: failed to run pipeline: function pipeline run has failed with message: 
+ '[' false '=' true ]
+ '[' false '=' true ]
+ CHECKOUT_DIR=/workspace/output/
+ '[' true '=' true ]
+ cleandir
+ '[' -d /workspace/output/ ]
+ rm -rf '/workspace/output//*'
+ rm -rf '/workspace/output//.[!.]*'
+ rm -rf '/workspace/output//..?*'
+ test -z 
+ test -z 
+ test -z 
+ /ko-app/git-init '-url=https://github.com/zroubalik/testx-function.git' '-revision=' '-refspec=' …
```
=> Print logs if Pipeline Run fails

client.go, client_test.go, cmd/invoke.go, invoke.go
- :gift: `invoke -v` prints metadata
HTTP headers or CloudEvent fields are printed on invoke with verbose enabled.
```shell
$ func invoke --verbose
"Content-Type":text/plain; charset=utf-8
"Date":Tue, 05 Apr 2022 14:02:10 GMT
"Content-Length":3
OK
```
Fixes #922
=> feat: invoke verbose metadata

.gitattributes
🧹  The Knative style check uses linguist to determine if a given file is a generated file. If so, it excludes that file from the check. This change should prevent Knative's style check from complaining about no newline on version.txt
/kind chore
=> chore: add version.txt to .gitattributes for style

.unicode-control-characters.config.py
With recent update to security action. The following file should be used to exclude false positive reports.
- :bug: Add unicode control chars exclude
PTAL
/cc @pierDipi @cardil
=> Add unicode control chars exclude

hack/allocate.sh
🧹  Use the latest Knative release in the hack/allocate.sh script. In addition, there is a small change to how the munged yaml files are piped through `yq`, adding a final pass through `yq` itself essentially sanitizing the data.
/kind chore
=> chore: update allocate script with latest knative

client.go, filesystem.go, repository.go, repository_test.go, template.go, templates.go, templates_test.go
Make `fn.Template` an interface instead of a concrete struct.
=> Refactor: templates

function.go, repository.go, template.go
* moved `HealthEndpoints` and `BuildConfig` structs to `function.go`
* moved `Template` to `repository.go` so `Repository`, `Runtime` and `Template` are together.
* removed fields that were leaking details from `Repository` and `Runtime`
=> Refactor: clean Repository and Runtimes structs

docs/function-developers/developers_guide.md
Signed-off-by: Bryan Tong <tongb@vmware.com>
- Fix typo of "Knaive" -> "Knative>
No issue exists since it's a small typo
Fix typo in developer's docs
```release-note
Fix typo in documentation
```
**Docs**
```docs
```
=> [fix] Docs typo: "Knaive" -> "Knative"

README.md, docs/README.md
There were a few links in the documentation that did not get updated in the most recent docs restructuring. This addresses those issues that I could find.
- :broom: cleaning up broken links
/kind fix
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/976
=> fix: update various doc links

k8s/dialer.go
Rationale: avoid docker.io pull limit.
=> Use socat image from quay.io

pipelines/tekton/pipeplines_provider.go
=> fix: ignore `is forbidden` errors when deleting function and resources

buildpacks/builder.go, function.go, function_test.go, s2i/builder.go
- :gift: S2I Builder Env Interpolation
More specifically:
* Extracts env var interpolation logic from buildpack builder to shared package static `fn.Interpolate`
* Refactors implementation slightly to pass-through unmatched values (previously a bit ambiguous, presuming permissive).
* Adds interpolation tests, including explicit tests for asserting both unmatched strings pass through and nil value pointers indicate env var should be omitted from the final interpolated map.
* Integrates interpolated build envs into S2I builder.
Fixes #990
=> feat: s2i builder env var interpolation

docker/runner.go, function_test.go
- :broom: update the Docker Runner to use shared env var interpolation logic from `fn.Interpolate`
/kind cleanup
=> src: update runner with shared env var interpolation

cmd/client.go, cmd/deploy.go, cmd/prompt_test.go
- :bug: docker credentials can be now read from non-tty stdin (e.g. from piped input).
/kind bug
```release-note
fix: docker credentials can be now read from non-tty stdin (e.g. from piped input)
```
=> Fix read pwd from non-tty input

s2i/builder.go, s2i/docker_client_wrapper.go
Workaround a bug in podman:
https://github.com/containers/podman/issues/13770
- :bug: Fix s2i build with podman
```release-note
fix: s2i build with podman
```
=> Fix S2I build with podman

s2i/builder.go
- :gift: Exclude certain directories form S2I build tar know to be either unnecessary or error-prone
- :bug:  Error running Node Functions which unecessarily had node_modules sent to the build daemon
Exclude various files and cache directories from S2I builds.  This list may need to be expanded in the future.
/kind bug
Fixes #1018
=> fix: ignore node_modules for s2i builds

buildpacks/builder.go, buildpacks/builder_test.go, client_int_test.go, cmd/build.go, cmd/client.go, pipelines/tekton/resources.go
- :gift: configurable pack builder images via `builderImages` member
- :gift: refactor to enable fuller testing
- :gift: tests
Pack builder can now have its builder image defined in func.yaml (on the Function structure) alongside S2I without interfering with each other.   Previously it was a shared setting, which meant defining a builder image other than the default would peg the Function to only work with one builder or the other.  Also enables per-builder settings, which along with the update to the S2I builder and the [associated func.yaml migration](https://github.com/knative-sandbox/kn-plugin-func/pull/1033), will address #1022. 
=> feat: pack builder images individually configurable

hack/test.sh
- :bug: fix frequent test timeouts
Of late the "Verify Configuration" step of the integrations tests has been failing.  This appears to be because the cluster made available in GitHub actions simply doesn't stand up the test `echo` service within the 30s default wait timeout.
Until such time as Kubernetes gets faster, or the GitHub VMs are more highly specced... this PR just increases the timeout from the default 30s to 120.  Also increased is the time between attempts to create the service, as it appears to always try 5 or more times before the endpoint is available.
/kind bug
=> fix: increase timeout when testing int cluster availability

client.go, client_test.go, cmd/build.go, cmd/completion_util.go, cmd/root.go, function.go, function_migrations.go, function_migrations_unit_test.go, schema/func_yaml-schema.json, template.go, testdata/migrations/v0.23.0-customized/func.yaml, testdata/migrations/v0.23.0/func.yaml
:gift: Function auto-migration to `builderImages` map
func.yaml now includes a `builderImages` map which allows Functions to specify builder-specific images to use when building.  This deprecates the non-specific `builder` and `builders` attiributes.  This PR migrates Functions which were created prior to this deprecation by either removing the attributes if unused, or carrying them over if the user had customized the value.  This (along with #1024 and #1028) Fixes #1022
=> feat: builder images map migration

invoke.go
Use JSON object as default message for the invoke sub-command
```release-note
Use JSON object (instead of plain text) as default message for the invoke sub-command
```
=> feat: use JSON object as default message for the invoke sub-command

docker/docker_client.go, docker/docker_client_linux_test.go
:broom: Better error message for `podman` auto service.
Now we are checking exit code and propagating std[err,out] of the service if something went wrong.
=> Better error message for podman auto service

pipelines/tekton/pipeplines_provider.go
If Tekton Task consists of multiple Steps and there is a failure in one of the steps, the `ExitCode` on this step Step is set to `number != 0`.  `ExitCode == 1` is set on the last failed Step.
So if there are for example 3 steps and the 2nd step fails, this causes failure in the 3rd step as well. In this case the ExitCodes are set this way:
```
step1: ExitCode: 0
step2: ExitCode: 145 (and maybe random? number != 0)
step3: ExitCode: 1
```
The previous implementation printed logs for step3, but we are more interested in the step2 logs.  This PR fixes this problem.
=> chore: print correct logs for failed PipelineRun

cmd/invoke.go
:bug: fix unrespected invoke format flag
Fixes ignored flag `func invoke --format [http|cloudevent]`
Fixes #1037 
/kind bug
=> fix: map invoke format flag

.github/workflows/test-integration.yaml
:bug: remove flaky third-party echo step from CI
Despite having its timeout increased twice, the third-party-dependent echo server test continues to time out regularly in CI.  While still useful when testing locally or in less resource-constrained environments, I propose simply removing this step from GitHub actions.  The E2E tests succeed often even when this validation step does not, indicating the problem is not the cluster itself.
It is perhaps worth noting that, even after repeatedly re-running tests after increasing the timeout, pr #1031 refused to complete.  After removing this test script, everything worked fine.  I suggest that it is useful to retain in the repository for validating local configuration but is too flaky and ultimately redundant when running a full suite of test in …
=> remove third-party echo test from CI

s2i/builder.go
* Fix premature Close() of docker client
/kind bug
```release-note
fix: s2i+podman "Cannot connect to the Docker daemon" error
```
=> Fix premature Close() of docker client

client.go, client_test.go, cmd/deploy.go, cmd/root.go, cmd/root_test.go, cmd/run.go, cmd/run_test.go, function.go, job.go
:gift: client detects Function build staleness via `.Built(path)`
:gift: `run` command accepts `auto|true|false` for `--build`
Upon build, a hash of the filesystem at time of build is stored in the Function runtime directory `.func`.  This stamp is exposed via a new `.Built` function on the client.
This function is utilized to implement more intelligent build logic on the `run` command as initial acceptance testing, and will be integrated into the `deploy` command in a subsequent PR if acceptable.
```release-notes
On `run`, functions are only built when something on the filesystem changes
```
=> feat: on run, build only when filesystem changed

client.go, cmd/deploy.go, test/e2e_lifecycle_tests.sh
:gift: add remaining build options to deploy
:broom: increases e2e test timeout to 45m
Adds `builder` and `builder-image` flags to the `deploy` subcommand such that deploying is a full superset of building.
=> feat: add all build flags to deploy

.codecov.yaml, .gitattributes, buildpacks/builder.go, docker/close_guarding_client.go, docker/docker_client.go, docker/zz_close_guarding_client_generated.go, go.mod, s2i/builder.go, vendor/modules.txt
* Fix docker client "use after close" issues (this is issue for podman-auto-svc and ssh connections).
* Added guard for use after close (by introducing wrapper that panics if used after close).
```release-note
fix: pack+[podman-auto-svc|ssh] build errors: "use of closed network connection" and "Cannot connect to the Docker daemon at unix:///tmp/func-podman-3934646889/podman.sock. Is the docker daemon running?"
```
=> fix: premature Close() of docker client

pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
- :bug: Workaround for missing func.yaml on tekton step result of task buildpack
/kind bug
=> fix: workaround for missing func.yaml on tekton step result

cmd/deploy.go
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/693
/kind fix
```release-notes
no longer prompts for image/registry info if `--build disabled` when running `func deploy`
```
=> fix: do not prompt user if --build diabled

test/_e2e/cmd_build_test.go, test/_e2e/cmd_config_envs_test.go, test/_e2e/cmd_config_labels_test.go, test/_e2e/cmd_config_volumes_test.go, test/_e2e/config.go, test/_e2e/e2e_remote_repository_test.go, test/_e2e/func_test_proj.go
- :broom: Defines builder for e2e tests tied to GoLang functions such a Test Remote Repository, Config Envs, Labels and Volumes
kind <kind>
/kind cleanup
=> Explicit define builder for Remote and Config e2e tests

pipelines/tekton/pipeplines_provider.go, pipelines/tekton/validate.go, pipelines/tekton/validate_test.go
Until we resolve issue with additional Buildpacks, a few runtimes are not supported for on cluster build. So it is better to fail before executing the actual Pipeline.
=> feat: check valid runtimes for on cluster build

cmd/deploy.go, docker/creds/credentials.go
- :gift: Better input handling for non terminal stdio. Useful for scripting with `func`.
- :gift: Make `not implemented` error of cred-helper non fatal error.
```release-note
feat: better input handling for non terminal stdio. Useful for scripting with `func`.
```
=> Improve usability of `func` CLI for IDE plugins

client.go, client_test.go, knative/deployer.go, mock/deployer.go, pipelines/tekton/pipeplines_provider.go, test/_e2e/cmd_deploy_test.go
- Added the function's namespace to the success message after deploy
- If the namespace in function obj is blank, display current context namespace
Fixes #1083
```release-note
Prints the namespace when a function is deployed
```
=> feat: deploy success message also displays the namespace

docker/creds/credentials.go
- :bug: Fix using empty credentials for docker.io, the issue is that docker.io recognizes empty credentials (as opposed to for instance quay.io), but only for read operations. So authentication passes but not authorization.
/kind bug
```release-note
bugfix: using empty credentials for docker.io
```
=> Fix: try empty credentials as last option

cmd/deploy.go, cmd/deploy_test.go
*changes for func deploy*
- --image allows image digest for func deploy as [registry]/[namespace]/[name]:[tag]@[digest]
- if digest is given, push and build have to be disabled and image with digest is saved in func.yaml file
- few tests in deploy_test.go included
Fixes #1058
=> feat: func deploy accepts image digest in --image

pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
- :broom: use 0 group id for func-buildpacks Task
Previous setting caused problems on some restricted setups (OpenShift in non default namespace). Now the resulting image produced on cluster via Buildpacks Task has the same guid set like image produced locally.
Node function build with the original setup might not be deployed, because of this error:
```
2022/07/11 21:16:18 unlinkat /workspace/source/node_modules: permission denied
[31;1mERROR: [0mfailed to launch: exec.d: failed to execute exec.d file at path '/layers/paketo-buildpacks_npm-install/launch-modules/exec.d/0-setup-symlinks': exit status 1
```
=> fix: use 0 group id for func-buildpacks Task

client_int_test.go, cmd/client.go, knative/deployer.go, openshift/metadata.go, pipelines/tekton/pipeplines_provider.go
- :gift: add OpenShift related Annotations & Labels
This should enable some OpenShift Developer Console UX features (Pipeline and Git Repo references) for on cluster builds:
=> feat: add OpenShift related Annotations & Labels

cmd/languages.go, cmd/root.go
This command does not get surfaced to the user without adding it to the root.
Also add a little more information to the short description.
=> fix: add languages command to cmd root

cmd/build_test.go, cmd/deploy.go, cmd/deploy_test.go, cmd/testdata/kubeconfig_deploy_namespace
*changes to `func deploy`*
- store namespace to func.yaml on first deployment (from current namespace)
- if namespace is not specified via CLI and is different from func.yaml print warning explaining this 
(ex: `func.yaml->namespace = default` &&  `oc->namespace = myns` -> print warning where func is deployed)
- if namespace is specified via CLI, assume user knows what hes doing, do nothing
*update*
- add fake KUBECONFIG to all the tests in deploy_test.go
- replace `context.TODO` with `context.Background` in deploy_test.go
- print warning to stderr
Fixes #1084
=> feat: always store namespace in func.yaml and warn if current ns & func.yaml ns is different

test/_e2e/cmd_invoke_test.go
:broom: Just removing `--verbose` from `create` and `deploy` commands on `invoke` e2e tests  just to make e2e logs a bit cleaner. Verbose option is kept on `invoke` command since it is the target command being tested
/kind cleanup
=> test: remove verbose from test invoke create/deploy commands

client.go
This change prevents the incremental build messages that loop while
building from continuing during subsequent deploy phases by providing a
cancelable context to the `printBuildActivity()` function parameters.
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/974
-->
```release-note
Fixes a bug where build output overwrites user-facing credentials prompts.
```
/kind fix
=> fix: stop build progress loop when build completes

pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
This is required to enable S2I driven on cluster builds.
- :gift: deploy Tekton task supports optional `image` parameter
Relates to #989
=> feat: deploy Tekton task supports optional `image` parameter

client.go, test/_e2e/cmd_deploy_test.go
- 🐛  change deploy output text so that it is prefixed with a space, lining up with other text output on the left-hand column, and hopefully fixing the problem where the spinner icon overwrites part of the URL for Windows users.
I also added a couple of emoji to make the output a little friendlier.
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/1138
=> fix: use space prefix for deploy output text

cmd/languages.go, cmd/root.go, cmd/templates.go, cmd/templates_test.go
- :gift: adds the templates command
Exports the list of available templates in either plain text or JSON.  By default lists all templates grouped by language runtime.  Accepts an additional optional argument which will list only templates for the given runtime.
Along with #1114 this Fixes #874
```shell
❯ func templates
LANGUAGE     TEMPLATE
go           cloudevents
go           http
node         cloudevents
node         http
python       cloudevents
python       http
quarkus      cloudevents
quarkus      http
rust         cloudevents
rust         http
springboot   cloudevents
springboot   http
typescript   cloudevents
typescript   http
```
```shell
❯ func templates go
cloudevents
http
```
```shell
❯ func templates --json
{
"go": [
"cloudevents",
"http"
],
"node": [ …
```
=> feat: templates list command

.github/workflows/ci.yaml, Makefile, hack/release.sh
This PR adds the binaries for platforms ppc64le and s390x to the list of release artifacts. Although at this point function support on these platforms is limited (thanks to paketo.io only supporting x86_64) this is the first step in properly suppporting functions on ppc64le and s390x (possibly via the s2i feature).
=> Added binary builds for platforms ppc64le and s390x

docs/function-developers/developers_guide.md, docs/function-developers/golang.md, docs/function-developers/nodejs.md, docs/function-developers/python.md, docs/function-developers/quarkus.md, docs/function-developers/typescript.md
- :bug: fix link to docs/reference/command.txt
=> fix link to reference/command.txt

cmd/build.go, cmd/build_test.go
:bug: If the user has a value specified in func.yaml for the image registry, that value should be used by the build command, if not otherwise specified as a flag or via the environment.
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/1159
/kind bug
```release-note
Fixes function builds when a registry exists in func.yaml but an image has not yet been built
```
=> fix: ensure registry in func.yaml is respected

test/_e2e/update_templates/quarkus/http/src/main/resources/application.properties
:broom: Removing package.type property from quarkus template used on e2e test to align with default quarkus template.
/kind cleanup
=> quarkus test template change to remove package type property

client_test.go
The client test which checks for rebuilds based on timestamps is consistently failing in CI. This change may alleviate that problem.
Opening this as a separate PR because it's completely unrelated to the PR where this is occurring.
See: https://github.com/knative-sandbox/kn-plugin-func/pull/1169#issuecomment-1220210569
=> chore: add some milliseconds in client tests

cmd/build.go, cmd/config.go, cmd/delete.go, cmd/deploy.go, cmd/format.go, cmd/info.go, cmd/invoke.go, cmd/root.go, cmd/run.go, docs/reference/commands.txt
:broom: use `.` as default path
Flags and generated help text show `"."` as default for `--path`.  The value is converted into the absolute path when a config command struct is generated from the flags.
This is related to #1169
=> chore: use dot as path default rather than absolute path

docs/function-developers/golang.md, docs/function-developers/nodejs.md, docs/function-developers/python.md, docs/function-developers/quarkus.md, docs/function-developers/typescript.md
- :bug: Fix a broken link in docs
=> Fix a broken link in docs

docs/generator/main.go, docs/reference/func_create.md, docs/reference/func_templates.md
- :bug: Trim white spaces before EOL in generated markdown files.
=> fix: trailing white spaces in genrated docs

pipelines/tekton/resources.go
- :bug: Fix on cluster build, deployment issues when buildEnv has only one env var, example:
/kind bug
Fixes #1199
=> fix: on cluster builds when buildEnvs contains only one build environment

cmd/deploy.go
- :bug: The short flag `-b` now means the same in `build` and `deploy`. 
/kind bug
```release-note
fix: the short `-b` flag now means the same thing for `build` and `deploy`
```
=> fix: flags more consistent between build/deploy

docs/reference/func_deploy.md
- :broom: Update generated docs for `func deploy`
A recent PR made changes to the flags for `func deploy`. See: https://github.com/knative-sandbox/kn-plugin-func/pull/1202
/assign @matejvasek
=> doc: update generated docs for 'deploy'

cmd/languages.go, cmd/templates.go, docs/reference/func_languages.md, docs/reference/func_templates.md
Since `boson-project/func-templates` doesn't exist now, replace it with the correct link `boson-project/templates`.
- :bug: use the correct sample repository link in command usage
/kind bug
=> use the correct sample repository link in command usage

cmd/build.go, cmd/build_test.go
- :bug: check for `--image` flag in build command
If the user provides an `--image` flag on the command line, it should be used. This commit modifies the image resolving code to check whether or not the image name was provided on the command line.
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/1125
/kind bug
```release-note
Fixes a regression where the `--image` flag on `func build` was not being used
```
=> fix: check for `--image` flag in build command

.github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, Makefile, hack/tekton.sh, hack/test-integration-podman.sh, test/README.md, test/_common/cmd.go, test/_common/gitserver.go, test/_common/knfunc.go, test/_common/shell.go, test/_e2e/cleaner.go, test/_e2e/cmd_deploy_test.go, test/_e2e/knative.go, test/_e2e/ready_check.go, test/_e2e/update_test.go, test/_oncluster/asserts.go, test/_oncluster/git_helper.go, test/_oncluster/nodejs_helper.go, test/_oncluster/scenario_basic_test.go, test/_oncluster/scenario_context-dir_test.go, test/_oncluster/scenario_from-cli-local_test.go, test/_oncluster/scenario_from-cli_test.go, test/_oncluster/scenario_revision_test.go, test/_oncluster/scenario_runtime_test.go, test/_oncluster/tekton.go, test/e2e_oncluster_tests.sh, test/gitserver.sh
This PR contains an intial set of tests for On Cluster builds according to #856 
- :gift: E2E on cluster build tests
The following is covered by this PR
=> Oncluster build initial e2e set of tests

client.go, client_test.go, pipelines/tekton/pipeplines_provider.go
The recent changes in function image generation brought regression in on cluster build. If we tried to run a pipeline without image specified, it wasn't able to generate the correct image name.
ie. following `func.yaml` 
```yaml
specVersion: 0.25.0
name: test-function
namespace: default
runtime: node
registry: docker.io/zroubalik
image: ""
imageDigest: ""
build: git
...
```
fails with: 
```
🕐 Creating Pipeline resources
Error: failed to run pipeline: could not parse reference: 
```
This PR improves the error message as well.
- :bug: on cluster build - populate image name if not set
/kind bug
=> fix: on cluster build - populate image name if not set

k8s/dialer.go
- :bug: In-cluster-dialer pod security context is non-privileged now.
=> fix: in cluster dialer security context is non-privileged

test/_e2e/cmd_invoke_test.go
Downstream changes default builder to S2I, which currently has no
default Go builder image.  This PR pins the use of pack for the invocation test, which has support for all our core runtimes.
/kind bug
=> fix: downstream e2e fails with unknown default builder image

docs/function-developers/python.md
- :bug: variable `body` was misspelled to data
=> fixed a variable name error in docs

pipelines/tekton/resources.go
Need to hack empty BuildEnvs array on Tekton v0.39.0+  untill https://github.com/tektoncd/pipeline/issues/5149 is resolved and released.
Withouth this change on-cluster-builds fail on Tekton v0.39.0+ if there is not any Build Env specifed.
- :bug: on cluster build - workaround for Tekton issue with empty array
/kind bug
=> fix: on cluster build - workaround for Tekton issue with empty array

cmd/build.go, cmd/deploy.go
- :bug: fixes an error seen downstream when IsOpenShift results in non-zero flag default, causing tests to fail
- :broom: updates other affected commands/flags (the registry and builder flag on both deploy and build subcommands)
Updates the `deploy` and `build` commands to more selectively use the value of flags whose default is a non-zero value and whose value maps to an attribute on the function being operated upon.
In particular, the flag default will only be used when the function has no value yet defined (as a default), or when the value has been provided by the user (an override).
Note that this logic is a bit janky, and will be refined with the upcoming Global Config PR, which will provide a default value to the flag which will already take into account both the static default and …
=> fix: use flag value as default or when changed only

filesystem_test.go
Fixes a small typo in filesystem tests, so errors output correctly
=> fix: correct error handling in filesystem tests

cmd/func/main.go, docker/docker_client.go, docker/docker_client_ssh_test.go
- :gift: Better error message if docker/podman not present.
- :gift: Auto detect podman machine's socket on mac/win, so user doesn't have to set `DOCKER_HOST`.
=> feat: UX improvements for docker/podman usage

k8s/dialer.go, k8s/dialer_test.go
- :gift: Independence of `socat` image entrypoint.
- :gift: The `socat` image is configurable via environment variable.
- :test_tube: Make test assert less strict.
=> chore: dialer improvements

pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml, pipelines/tekton/resources.go, pipelines/tekton/tasks.go
Java related S2I builder images have S2I build scripts in `/usr/local/s2i`, default location for other languages is `/usr/libexec/s2i`.
- :bug: s2i on cluster build of Quarkus functions
/kind bug
=> fix: s2i on cluster build of Quarkus functions

docker/docker_client.go, docker/docker_client_linux.go, docker/docker_client_nonlinux.go
- :bug: The `podman` auto-svc has own control group now.
This prevents `podman` process termination on SIGKILL/SIGTERM sent to `func`.
We must keep `podman` alive for cleanup (e.g. container removal).
=> fix: cleanup of auto-podman-service when receiving SIGINT/SIGTERM

pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
- :bug:  updated func-deploy tekton task to alingh with to new deploy flags
/kind bug
`func deploy` command now uses `--build false` instead of `--build disabled`, so changing `func-deploy` tekton task to reflect this change
=> fix: updated func-deploy tekton task to aling with the new deploy command build flag options

cmd/client.go, cmd/templates.go, cmd/templates_test.go
Fixes: https://github.com/knative-sandbox/kn-plugin-func/issues/1206
```release-notes
fixes a bug in the display of repository urls in the event of an error
```
=> fix: wrong-error-message-reported-in-command-func-templates-repository

utils/names.go, utils/names_test.go
- :bug: Fixed validation: function name must be DNS 1123 Label.
/kind bug
```release-note
fix: validation of function name -- it must be DNS 1123 Label.
```
resolves: #1259
=> fix: validation of function name

cmd/build.go
- :bug: Fix bug when registry prompt answer is ignored on `func build`.
/kind bug
```release-note
fix: bug when registry prompt answer is ignored on `func build`.
```
=> fix: registry prompt result being ignored

k8s/dialer.go
A `var` can be set at build (link) time as opposed to a `const`.
=> chore: linkage assignable socatImage

function.go
- :bug: Fix nil deref when custom builder image.
/kind bug
```release-note
fix: nil deref when custom builder image
```
=> fix: nil deref when custom builder image

cmd/root.go
- :bug: Fix `stdin` interactivity check -- it didn't work on Windows.
This caused interactive prompt not being used.
/kind bug
```release-note
fix: stdin interactivity check for Windows, this caused interactive prompt not being used
```
=> fix: stdin interactivity check

cmd/invoke.go, cmd/invoke_test.go
- :bug: `invoke` should always use the function's current namespace
- :broom: remove unnecessary client instance from config constructor and prompt method signature
- :gift: adds a general invoke command test
/kind bug
Fixes #1167
=> fix: always use function's namespace when invoking remote

client.go, cmd/build.go, cmd/create.go, cmd/create_test.go, cmd/delete.go, cmd/deploy.go, cmd/deploy_test.go, cmd/invoke.go, cmd/repository.go, config.go, config/config.go, config/config_test.go, config/testdata/func/config.yaml, docker/creds/credentials.go, docker/creds/credentials_test.go, testing/testing.go
- :gift:  adds initial support for a global config in `~/.config/func/config.yaml`
- :gift: default for `func create --language` can now be defined in global config
- :gift: defaulting to confirm prompts can be enabled in the global config
- :gift: modifed defaults are visible in help text.
Example  `~/.config/func/config.yaml`:
```
language: go
confirm: true
```
The config location is mutable using `XDG_CONFIG_HOME`.  A config file is not required for normal operation.  Values are accurately reflected in command help text.
This is the first part of a general-purpose Global Config (#901) which is prerequisite to, and will also partially  address the interrelated issues #573 #636 and #1097. 
=> feat: readonly global config

repository.go
- :bug: fix: default readiness endpoint
This bug is not expressed, because the correct values are currently read from template manifests rather than static defaults, but once that bug/decision is changed per #1281; this incorrect default would have manifested in incorrect initial functions.
=> fix: default readiness endpoint

s2i/builder.go
- :gift: Always pull base image for `s2i` builds. This should ensure we do build with up-to-date image including security patches.
=> feat: always pull base image for s2i builds

cmd/build_test.go, cmd/config_test.go, cmd/create_test.go, cmd/delete_test.go, cmd/deploy_test.go, cmd/invoke_test.go, cmd/languages_test.go, cmd/repository_test.go, cmd/root_test.go, cmd/run_test.go, cmd/templates_test.go, repositories_test.go, templates_test.go, testing/testing.go
- :broom: reset viper on most tests
- :broom: use t.Cleanup throughout
- :broom: use t.TempDir throughout
- :broom: use a clean XDG_CONFIG_HOME by default
- :broom: specify explicit name in create tests (t.TempDir yields dir name invalid for funtions)
- :broom: moves helpers to root_test
- :broom: git server helper expects `.git` suffix and returns full http url
General cleanup of tests, the impetus being that a temp directory for HOME for all tests is prerequisite to the forthcoming Global Config: Function Context.
/kind cleanup
=> chore: cmd test cleanup

.github/workflows/test-integration.yaml, .github/workflows/test-unit.yaml, .gitignore, Makefile
Added coverage output for integration test, and added codecov uploads for both integration and unit tests.
This commit changes the output file to coverage.txt as well, in order to be consistent with knative test infrastructure.
/kind chore
=> chore: add coverage for integration tests

docker/creds/credentials_test.go, docker/docker_client_pm_test.go, docker/docker_client_ssh_test.go, docker/docker_client_test.go, docker/docker_client_windows_test.go
- :broom: Use `t.Cleanup()` more.
/kind cleanup
=> chore: use t.Cleanup() more

instances.go, instances_test.go
- 🧹 adds some tests checking expected error states for function instances, local and remote
/kind chore
Related: https://github.com/knative/func/issues/1275
=> chore: add unit test cases for instances

.github/workflows/ci.yaml
This commit modifies the Ci jobs that run when commits land on `main`, splitting the one job into three: check, test-unit and test-integration. Code coverage stats are included for both test runs.
- 🧹 ensure integration tests run in CI on the `main` branch
- 🧹 add code coverage steps to both unit and integration test runs on `main`
/kind chore
=> chore: update CI to run unit+integration on main

.github/workflows/ci.yaml
The `needs` contexts were pointing to old job steps.
```
Invalid workflow file: .github/workflows/ci.yaml#L58](https://github.com/knative/func/actions/runs/3237468662/workflow)
The workflow is not valid. .github/workflows/ci.yaml (Line: 58, Col: 12): Job 'build-and-publish' depends on unknown job 'test'. .github/workflows/ci.yaml (Line: 98, Col: 12): Job 'publish-image' depends on unknown job 'test'.
```
/kind bug
=> chore: fix ci.yaml

.github/workflows/ci.yaml
Still trying to get CI on `main` right. Thanks.
- 🧹 Set up the cluster and such for integration tests. Move template tests to the Unit Test section. Hopefully this works now.
=> chore: more changes to CI workflow

docker/appease_coverage_gods_test.go
The file in question should be ignored by coverage since it is generated, but it is not.
=> test: appease coverage gods

pipelines/tekton/pipeplines_provider.go
- :gift: Cancel pipeline run on `SIGINT`/`SIGTERM` (without this `func deploy --remove` was uncancellable).
```release-note
feat: cancel pipeline run on SIGINT/SIGTERM
```
=> feat: cancel pipeline run on SIGINT/SIGTERM

README.md
Based on our discussion on TOC adding link to the Roadmap to project's Readme for better visibility.
- :broom: add link to the roadmap in the Readme
=> chore: add link to the roadmap in the Readme

pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
- 🧹 reference the `func` image at `ghcr.io/knative/func:latest` in tekton pipelines
We are now producing `func` images in the knative org.
/kind chore
```release-note
Uses `func` image from `ghcr.io/knative/func:latest` in tekton on-cluster build pipeline
```
=> chore: update image tag in tekton pipeline

test/_e2e/e2e_functions_test.go, test/_e2e/func_test_proj.go, test/_e2e/update_test.go
- :broom: Use proper temporary directory for function instances in end to end testing.
/kind cleanup
=> fix: use proper temp dir for funs in e2e tests

test/_oncluster/scenario_basic_test.go, test/_oncluster/scenario_context-dir_test.go, test/_oncluster/scenario_from-cli-local_test.go, test/_oncluster/scenario_from-cli_test.go, test/_oncluster/scenario_revision_test.go, test/_oncluster/scenario_runtime_test.go
- :broom: Fix tmp dir for oncluster e2e test
/kind cleanup
=> fix: use proper tmp dir for oncluster e2e tests

Makefile
Removes ldflags from docs generation make command as they are not used.
Their existence causes a conflict with the related PR which moves --path flag processing into init, causing a (nonfatal but anoying) error that ldflags were used but not defined.
=> fix: remove ldflags from docs generation make target

pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml, test/_oncluster/scenario_runtime_test.go
- :gift: Oncluster builds tests for s2i supported runtimes
- :bug: Fix s2i task when build env array is empty for node functions (#1363)
/kind cleanup
=> test: adding oncluster builds e2e tests for s2i supported runtimes

buildpacks/builder.go, s2i/builder.go
The https://github.com/knative-sandbox/func-tastic repo uses "nodejs" instead of "node" as the language runtime. This change makes it possible for templates in the func-tastic language pack to work out of the box.
/kind chore
```release-notes
adds support for "nodejs" as a runtime designation in addition to the default "node"
```
=> chore: add nodejs as a builder key

hack/tekton.sh
- :broom: Waiting for tekton webhook to be ready before applying tekton tasks (improve ci)
/kind cleanup
=> Fix Tekton tasks install failures on CI

config/config.go, docker/creds/credentials_test.go
:bug: fix incorrect default config directory
:bug: add a clean home setup to a test
When the system can not automatically determine a determine a config directory path, it should communicate this by returning the zero value, letting the caller handle the situation accordingly (skip usage, or create a temporary home directory)
=> fix: config dir default empty

README.md
Adds links to the knative.dev website in place of local docs, and corrects the time for the WG meeting.
=> chore: update README.md with proper links

cmd/build.go, cmd/client.go, cmd/deploy.go, cmd/run.go, openshift/openshift.go
- :gift: Defer OpenShift detection until necessary, thus not blocking unrelated functionality.
```release-note
feat: defer OpenShift detection until necessary
```
=> feat: defer OpenShift detection

k8s/dialer.go
- :broom: make socat image linker public
- :broom: remove option set socat image using env var
/kind cleanup
=> fix: make socat image public and remove socat image env

cmd/build_test.go, cmd/config_labels_test.go, cmd/delete_test.go, cmd/deploy_test.go, cmd/invoke_test.go, cmd/languages_test.go, cmd/templates_test.go
- Ensures all tests execute with initially clear args
- Minor refactor/cleanup to make this reset more obvious
=> chore: ensure all tests clear cmd args

client_test.go, cmd/deploy_test.go, mock/deployer.go
- :broom: updates the mock deployer's delegate to match the `Deployer` it is mocking.
Expected usage is illustrated within a refactored implementation of `mock.NewDeployerWithResult`.
/kind techdebt
=> chore: mock deployer method signature

cmd/build.go, cmd/deploy.go, cmd/root.go, config/config.go
:gift: registry globally configurable
Deferred evaluation of cluster type is preserved by making registry a helper in the `cmd` package and a calculated field of the global config struct.
```release-notes
Image registry is now globally configurable
```
=> feat: registry globally configurable

client.go, cmd/delete_test.go, cmd/describe.go, cmd/describe_test.go, cmd/root.go, docs/reference/func.md, docs/reference/func_build.md, docs/reference/func_describe.md
- :gift: describe function in given namespace
- :bug: describe function by name _or_ at path
- :broom: fix inconsistency with `client.Describer`
- :broom: add tests
Added ability to specify a namespace in the same manner as `list` and `delete`.
In order to be more consistent with `kubectl describe` and the client's `Describer` interface, the command was renamed `describe` with aliases for both `desc` and `info`.
/kind techdebt
=> feat: describe command namespace

cmd/delete.go, cmd/delete_test.go, docs/reference/func_delete.md
- :bug: Fixes bug where deleting by name fails if current path has no initialized function.
- :gift: Adds namespace test to delete command
- :broom: Moves namespace flag into delete command for
- Better help text
- Easier testing
- :broom: Sets static default namespace for flag to "default"
/kind techdebt
```release-notes
- Fixes bug where deleting by name fails if current path has no initialized function.
- Sets static default namespace for flag to "default"
```
=> chore: delete command namespace

cmd/deploy.go, cmd/deploy_test.go
- :broom: separates namespace warnings from derivation logic
- :broom: tests cleanup and simplification
- :broom: integrates deploy namespace value derivation with flag init flow
Prepratory cleanup for switch to use Global Config namespace value when available.
=> chore: deploy cmd namespace

cmd/list.go, cmd/list_test.go, docs/reference/func_list.md
- Adds namespace test to list command
- Moves namespace flag into list command for
- Better help text
- Easier testing
- Sets static default namespace for flag to "default"
/kind techdebt
=> chore: list command namespace

OWNERS
When we moved to knative org, the groups changed. This addresses that.
/kind chore
=> chore(OWNERS): update to new org

cmd/delete_test.go, cmd/describe_test.go, config/config_test.go
- :test_tube: Resetting `KUBECONFIG` environment variable is not sufficient if test runs in cluster.
We also must unset `KUBERNETES_SERVICE_HOST` environment variable, so in-cluster-config won't kick in.
=> test: fix tests when running in cluster

client.go, function.go, function_unit_test.go, instances.go, repository.go, templates.go
:bug: validate function on write
:broom: adds typed errors for required name, registry and runtime
:broom: defers member requirements until needed
In the spirit of "Be permissive on what is accepted, and strict on what is emitted", function validation now happens on write rather than load, defers as much as possible until needed, and moves closer towards validating syntax, not state.
This fixes a bug where a function missing members was unable to be loaded (and thus fixed), forcing a manual edit of func.yaml
/kind bug
```release-notes
Fixes a scenario where the CLI is unable to load invalid func.yaml files and repair them in memory before rewriting
```
=> fix: error instantiating empty function

buildpacks/builder.go, cmd/build.go, cmd/config.go, cmd/delete.go, cmd/describe.go, cmd/invoke.go, cmd/root.go, cmd/run.go, docs/reference/func_build.md, docs/reference/func_config.md, docs/reference/func_config_envs.md, docs/reference/func_config_envs_add.md, docs/reference/func_config_envs_remove.md, docs/reference/func_config_labels.md, docs/reference/func_config_labels_add.md, docs/reference/func_config_labels_remove.md, docs/reference/func_config_volumes.md, docs/reference/func_config_volumes_add.md, docs/reference/func_config_volumes_remove.md, docs/reference/func_delete.md, docs/reference/func_deploy.md, docs/reference/func_describe.md, docs/reference/func_invoke.md, docs/reference/func_run.md, function.go, function_test.go
:broom: default path is current working directory
Cleans up logic to correctly treat the current working directory as the default effective function path unless a value for path is provided.  Removes all references to "." because the shell is responsible for path expansion.
```release-notes
Ensures current working directory is always the default effective function path
```
=> fix: path default is current working directory

client.go, cmd/build_test.go, cmd/client.go, cmd/client_test.go, cmd/delete_test.go, cmd/deploy_test.go, cmd/describe_test.go, cmd/languages_test.go, cmd/run_test.go, cmd/templates_test.go, docs/generator/main.go, docs/reference/func_deploy.md, mock/remover.go
:bug: fixes missing default remover function implementation in the remover mock
:bug: fixes incorrect error in noop describer impl
:broom: cmd tests simplification via `NewTestClient`
:broom: simplify docs generator's client instantiation
:broom: regen docs
Test cleanup and a few minor testing-related bugs
/kind bug
=> fix: mock and noop inconsistency

cmd/build.go, cmd/deploy.go, cmd/root.go, cmd/run.go
:broom: rename config local variable
Use `cfg` as the local variable name for `config` in preparation for use of the `config` pacakge throughout
/kind cleanup
=> src: rename config local variable cfg

cmd/build.go, cmd/build_test.go, cmd/deploy.go, cmd/deploy_test.go
:broom: build prompts cleanup
Fixes a few small bugs with build prompts by embracing the system:  there is a dedicated method for prompting a user: a command config's `.Prompt()` method.  Its use results in overall reduction in complexity and removal of some small bugs when combining with --confirm.
This primary purpose of this cleanup, however, is to assists in the integration of global config's function context (PR 1416) into the runBuild method by reducing the logic handled therein
/kind cleanup
=> fix: build prompts

buildpacks/builder.go
Adding VMware function builders as trusted.
Fixes https://github.com/knative/func/issues/1379
```release-notes
adds VMWare function builder as trusted
```
=> Add VMware builder as trusted

buildpacks/builder.go, buildpacks/builder_test.go
The trusted builder prefixes should end with a slash in order to prevent malicious parties from using a builder such as `quay.io/bosonhacks/rootkit`. Should be cherry-picked to `release-1.8`
/kind fix
```release-note
❗ Fixes: https://github.com/knative/func/security/advisories/GHSA-5336-2g3f-9g3m
```
=> fix(GHSA-5336-2g3f-9g3m): Fixes GSA GHSA-5336-2g3f-9g3m

buildpacks/builder.go, buildpacks/builder_test.go
The trusted builder prefixes should end with a slash in order to prevent malicious parties from using a builder such as `quay.io/bosonhacks/rootkit`. Should be cherry-picked to `release-1.8`
/kind fix
```release-note
❗ Fixes: https://github.com/knative/func/security/advisories/GHSA-5336-2g3f-9g3m
```
=> [release-1.8]: Fixes GHSA-5336-2g3f-9g3m

buildpacks/builder.go, buildpacks/builder_test.go
We have been relying on a closure to validate the builder prefix in the builder image name provided to `pack`. This change ensures that we use the builder image which `pack` is using, whether it's what we provided in options or not.
/kind cleanup
=> cleanup(buildpacks): tweak TrustedBuilder()

cmd/build.go, cmd/build_test.go, cmd/root.go, cmd/root_test.go, cmd/testdata/TestBuild_ConfigApplied/func/config.yaml, cmd/testdata/TestBuild_ConfigPrecidence/func/config.yaml, config/config.go, config/config_test.go, docs/reference/func_build.md
:gift: commands integrate with contextually active function
The `build` command illustrates the flow of config values, which has the following precidence and order of evaluation: 1. static defaults in `config.Global` < 2. user settings in an optional `~/.config/func/config.yaml` < 3. contextually relevant function (`./func.yaml`) < 4. environment variables < 5. Flags
The function with context is considered when determining flag defaults such that:
- No special logic is required to determine "if changed"
- help text correctly reflects the actual values which will be used
- Global config can be a direct parent of command-specific config via embed
Also, as part of this PR it was necessary to:
- CLI tests clear environment of FUNC_* variables via a `clearEnvs` function
- Commands' `bindEnv` …
=> feat: command function context

buildpacks/builder.go, buildpacks/builder_test.go, cmd/root.go, cmd/root_test.go, k8s/dialer.go
This is a cherry-pick of  98001dc3512af45782f95bf836078da0b0c27a69 and 1ca662557714736c2f1d11607f90de69e54d66af to the `release-1.8` branch. Small improvements to UX.
* make socat image public and remove socat image env
* improve output for `func version`
=> [releaese-1.8] include image sha in `func version`

k8s/dialer.go, k8s/persistent_volumes.go, k8s/security_context.go
- :bug:  Set `seccomp` of auxiliary pods on k8s 1.24+
This is for OpenShift 4.11+
/kind bug
=> Set seccomp of auxiliary pods on k8s 1.24+

go.mod, k8s/dialer.go, k8s/persistent_volumes.go, k8s/security_context.go
Adds `PodSecurityContext` with defined non-root `uid` and `gid` and `fsGroup`, so that the ownership of a volume is changed and the non-cluster user can operate on the volume without "permission denied" error (see #1432 for more).
=> fix: add default PodSecurityContext to the uploader (#1432)

test/_common/gitserver.go, test/_e2e/config.go, test/_oncluster/git_helper.go, test/_oncluster/scenario_basic_test.go, test/_oncluster/scenario_context-dir_test.go, test/_oncluster/scenario_from-cli-local_test.go, test/_oncluster/scenario_from-cli_test.go, test/_oncluster/scenario_revision_test.go, test/_oncluster/scenario_runtime_test.go
Some refinements on e2e on cluster tests:
- :broom: Making function name unique per run (to avoid name conflict on subsequent tests)
- :broom: resolving default test registry name according to the target cluster
/kind cleanup
=> Cleanup e2e on cluster tests

client_int_test.go, knative/deployer.go
- :bug: fix `deploy` with autoscaling options specified
/kind bug
Fixes #1481 
```release-notes
Fixes a bug preventing autoscaling options from being applied
```
=> fix: `deploy` with autoscaling options specified

cmd/build.go, cmd/config.go, cmd/config_envs.go, cmd/config_labels.go, cmd/config_volumes.go, cmd/create.go, cmd/delete.go, cmd/deploy.go, cmd/describe.go, cmd/invoke.go, cmd/languages.go, cmd/list.go, cmd/repository.go, cmd/root.go, cmd/run.go, cmd/templates.go, cmd/templates/template_engine.go, cmd/templates/templates.go, cmd/version.go, docs/generator/main.go, docs/reference/func_build.md, docs/reference/func_create.md, docs/reference/func_delete.md, docs/reference/func_describe.md
As part of #215, the definition of the `root` command has changed and uses templating to generate its command line help. However, all subcommands still use `cmd.SetHelpFunc(defaultTemplatedHelp)` or similar for this, so we currently still have the "old approach" in use. 
It should be changed so that all commands use the templating as the `root` command does, and the `cmd.SetHelpFunc(defaultTemplatedHelp)` is gone. 
The generation of the docs must work as before.
=> chore: refactor commands help to use templates

docs/language-packs/language-pack-contract.md
Includes guidance for Language Pack authors creating templates that use runtimes other than those that are built in to the CLI.
See: https://github.com/knative/func/pull/1484
=> docs: update language pack docs for builderImages

client.go
When a user attempts to build, run or deploy a function and it has not been previously built, the `--registry` flag or `FUNC_REGISTRY` environment variable must be set so that the image name can be calculated. The current error message, `registry required` is not very helpful, and requires the user to divine what needs to happen next to fix the problem. This change updates the error message text to indicate that the user should set the `--registry` flag or `FUNC_REGISTRY` environment variable.
New behavior (https://app.warp.dev/block/YhpjkGod6HI8r2FbaBTeWz):
```
FUNC_REGISTRY='' ./func run -p viewer
Building function image
Error: registry required to build function, please set with `--registry` or the FUNC_REGISTRY environment variable
```
Fixes: …
=> fix: improve error message for missing registry name

pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml
- :bug: Fix envvar parsing for pack tekton task when envvar contains the `=` char
/kind bug
```release-note
fix: envvar parsing for pack tekton task when envvar contains the `=` char
```
=> fix: envvar parsing for pack tekton task

pipelines/tekton/pipeplines_provider.go
Fixing output, from:
```
$ func deploy --remote
Function updated in namespace "demo" and exposed at URL:
🕘 ps://test-function-demo.apps.mycluster.com
```
to:
```
$ func deploy --remote
✅ Function updated in namespace "demo" and exposed at URL:
🕐 https://test-function-demo.apps.mycluster.com
```
Probably caused by: #1513 
- 🐛 fix: on cluster build - fix url in the output msg
=> fix: on cluster build - fix url in the output msg

cmd/root.go, cmd/root_test.go
- :bug: fixes a bug where the --path flag would be ignored if provided after a subcommand
Updates the early-stage `effectivePath` method, which directly evaluates `--path` to use the `pflag` library, which implements a more permissive model for parsing flags (POSIX/GNU-style), including the ability to define a flag _trailing_ subcommands, and is the library used by the command structs internally.
/kind bug
```release-note
Fixes a bug where --path was sometimes not evaluated.
```
=> fix: allow trailing path flag

test/common/cmd.go, test/common/gitserver.go, test/e2e/cmd_invoke_test.go, test/oncluster/scenario_basic_test.go, test/oncluster/scenario_context-dir_test.go, test/oncluster/scenario_from-cli_test.go, test/oncluster/scenario_revision_test.go
- :gift: E2E tests show all logs
When a test fails, a combined log is dumped rather than just the command's standard error buffer, and when a test is configured to dump logs on success, the combined buffer is dumped.
=> e2e tests log stdout and stderr

.github/workflows/ci.yaml
Updates Java to version 17 in CI
=> chore(ci): update java version

client.go, client_int_test.go, client_test.go, cmd/build_test.go, cmd/create.go, cmd/delete_test.go, cmd/deploy_test.go, cmd/describe_test.go, cmd/invoke_test.go, function_test.go, instances_test.go, templates_test.go
- :gift: adds client.Apply
- :gift: adds client.Update
- :broom: renames client.Create to client.Init
- :broom: adds `func init` as an alias for `func create`
Adds two meta-commands, 'Apply' and 'Update', to the client. Renames 'Create' to 'Init' to avoid confusion with 'Update' (and to be more linguistically similar to git commands), and adds it as an alias to the create CLI command.
The impetus for this change is how much easier it makes a forthcoming update to the inbuilt integration tests which create functions with inline implementations.
=> feat: apply and update client methods

client.go, client_int_test.go, hack/allocate.sh, hack/binaries.sh, knative/deployer.go, knative/labels.go
- :gift: adds preliminary support for the dapr runtime
Adds support for the [Dapr](dapr.io) runtime from within Functions.  Note that the control plane must be installed in the Kubernetes cluster targeted for deployment:
```
dapr init --kubernetes --wait
```
This PR also integrates installation of the Dapr control plane, along with a Redis-backed pub/sub and persistence store, to test/local clusters via `./hack/allocate.sh`.
```release-note
Enables Dapr runtime support from within Functions.  Dapr control plane install required.
```
**Docs**
```docs
TODO
```
=> feat: preliminary dapr runtime support

test/e2e/main_test.go
Remove ioutil for new go version: https://go.dev/doc/go1.16#ioutil
/kind cleanup
=> Cleanup: remove ioutil for new go version

client.go, cmd/deploy.go
- :bug: Fix error on build command `Error: not built` on situation where image is built but user explicity specifies `--build=false`
**Use cases it covers**
- On Cluster builds which image is build and deployed on different steps and build stamp is not generated
- Local builds when a user builds a function, then run locally (i.e `mvn quarkus:dev`) or user modifes a non func related file (i.e. README.md)
/kind bug
Fixes #1535
=> fix: func deploy with explicity `--build=false` bypass isBuilt check

.github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, hack/create-testing-func-image.sh, pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
- Use current (as in PR) version of `func` in Tekton task during integration testing.
Without this change the `func` from `main` is used and changes in PR are not tested for on cluster build.
=> Use current (as in PR) func image in integration tests

cmd/build_test.go, cmd/deploy_test.go
- :broom: synchronize build and deploy command tests
Refactors tests such that all tests which apply to both commands are invoked for each and share implementations.
Homogenization of test names, and orders them alphanumerically.
_**Test implementations were not appreciably modified.**_
/kind cleanup
=> chore: build and deploy test suite cleanup

hack/release.sh
Adds the Tekton tasks for buildpacks, s2i and deployment to the release artifacts.
Note that the `checksums.txt` file will contain references to the full path of the files. I don't think this is a problem, but something to be look out for in case there is an issue.
/kind chore
```release-note
Adds Tekton Tasks to release artifacts.
```
Fixes: https://github.com/knative/func/issues/1550
Related: https://github.com/knative/func/issues/1333
=> chore(release): add tekton artifacts to release

pkg/functions/function.go
- :bug: both function constructors now ensure maps are initialized
The helper Function constructor which uses a passed function as defaults, `NewFunctionWith` was missing map initialization.  This could lead to nil pointer exceptions as it is used by `client.Init`.
/kind bug
=> fix: missing map initializations

pkg/filesystem/filesystem.go, pkg/functions/repository.go
- :bug: fixes `repo add` errors on root-level files
Logical error: repo add was skipping `mkdir` at the beginning.
/kind bug
Fixes #1573
=> fix: repo add no longer skips root

cmd/config_envs.go, cmd/config_labels.go, cmd/config_volumes.go, cmd/repository.go
- :gift: commands which refer to sets ignore plurality
- :gift: aliases added for linux command synonyms
Ensures commands which have subcommands to operate on individual members (list, add, remove etc) have singular and plural as aliases.
Ensures consistent usage of linux-command-style aliases for list,remove and rename operations: "ls", "rm", "mv"
```release-note
Commands such as `envs` can be referred to by their singular form `env` and vice-versa.
Commands with well-known command synonyms were added as aliases, such as`labels delete <name>` now supports `labels rm <name>`
```
=> feat: common command aliases

cmd/client.go, cmd/deploy.go, cmd/prompt/prompt.go, cmd/prompt/prompt_test.go
Code clean up. These prompts were in `cmd/deploy.go` making the file quite long and these haven't been used there at all.
- :broom: move prompts to a separate package
=> chore: move prompts to a separate package

.github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, .github/workflows/test-e2e-runtime.yaml, .github/workflows/test-e2e.yaml, .gitignore, Makefile, test/e2e_extended_tests.sh, test/e2e_lifecycle_tests.sh, test/e2e_oncluster_tests.sh
- :gift: Coverage for the end to end tests. With Go 1.20+ it is possible to instrument final binary to gather coverage.
=> chore: coverage for e2e tests

pkg/functions/client.go
- :bug: Fix build stamp computation.
About the same time that `buildStamp` was computed `.gitignore` was (unnecessary) modified.
This caused timestamp mismatch so function appeared to be not built.
Reason: sometimes (randomly) the `buildStamp` was computed before the `.gitignore` was modified.
/kind bug
```release-note
fix: build stamp computation
```
=> fix: build stamp computation

pkg/builders/s2i/builder.go, pkg/builders/s2i/builder_test.go, pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml, pkg/pipelines/tekton/pipeplines_provider.go
- :bug: Fix NodeJS s2i build when `node_modules` is present on filesystem.
This is workaround for two bug in another components:
* The s2i CLI/library is not honoring the `--exclude` flag when used with the `--as-dockerfile` flag.
https://github.com/openshift/source-to-image/issues/1104
* The node s2i image is not working if project contains `node_modules` directory with NodeJS modules.
https://github.com/sclorg/s2i-nodejs-container/issues/333
If only one of the bugs above were fixed this PR wouldn't be necessary.
/kind bug
```release-note
fix: s2i build when node_modules present
```
=> fix: node s2i build when node_modules present

cmd/config_git_set.go, cmd/deploy.go
- :gift: support flags for `func config git set` command
Relates: https://github.com/knative/func/issues/1323
```release-notes
Adds support for Git-based deploy options to be configured using CLI flags
```
=> feat: support flags for `func config git set` command

cmd/run.go, cmd/run_test.go, docs/reference/func_run.md
- :gift: Include --builder option on func run command
/kind api-change
Fixes #1609
```release-note
A new option "--builder" added to "run" command to be used when building.
Default is "pack"
```
**Docs**
```docs
```
=> Include --builder option on func run command

pkg/docker/docker_client.go
- :bug: Fix TCP+TLS docker daemon connection. If the `DOCKER_TLS_VERIFY` environment variable is set then TLS should be applied to the TCP connection to the docker daemon.
```release-note
fix: TCP+TLS docker daemon connection
```
=> fix: TCP+TLS docker daemon connection

pkg/builders/s2i/builder.go
- :bug: Fix s2i python build on Windows.
/kind bug
```release-note
fix: s2i python build on Windows
```
=> fix: s2i python build on Windows

pkg/pipelines/tekton/templates.go, pkg/pipelines/tekton/templates_pack.go, pkg/pipelines/tekton/templates_s2i.go
- 🎁 PAC - dynamically generate Pipeline target branch based on the Function config
Relates: https://github.com/knative/func/issues/1323
```release-notes
Uses locally configured Git branch for on-cluster builds
```
=> feat: PAC - dynamically generate Pipeline target branch

pkg/testing/testing.go
- :gift: Pre-compile mock binaries instead of using `go run`. The `go run` does internally compile which prolongs perceived run-time. This may lead to timeout in some tests.
=> fix: pre-compile mock binaries instead of 'go run' in tests

hack/release.sh
After the repository reorg, the hack/release.sh script is no longer pointing at the correct task yamls.
Fixes: https://github.com/knative/func/issues/1651
/kind chore
=> chore: fixup release.sh script

test/common/config.go, test/oncluster/scenario_github_test.go
- :broom: No longer using CI env to detect github action for oncluster test. This var is also used by other CI systems (i.e Jenkins) and thus causing the test to fail when executed on other CI systems.
/kind cleanup
=> test: cleanup on e2e github test

cmd/deploy.go, docs/reference/func_deploy.md, pkg/functions/function.go, pkg/pipelines/tekton/defaults.go, pkg/pipelines/tekton/pipelines_pac_provider.go, pkg/pipelines/tekton/pipeplines_provider.go, pkg/pipelines/tekton/pipeplines_provider_test.go, schema/func_yaml-schema.json
Ref: #851
Second try, after recreating the changes on the new project structure (old PR: https://github.com/knative/func/pull/1543)
=> feat: add pvc-size flag to deploy command (#851)

docs/function-templates/lifecycle.md
Not sure if this is the best place to iterate on this document or not, but eventually it will need to live somewhere.
=> docs: add preliminary document for function lifecycles

.gitignore
- :broom:  enable tracking of Go sumfiles in templates
In order for Scaffolding to correctly associate the dependencies of the "embedded" function, we actually do need to track the initial sumfiles for the source function template.  This change should have no effect on "nonscaffolded" functions; and we probably should have been doing this anyway.
/kind cleanup
=> feat: track go template sumfiles

cmd/root.go
- :bug: removes flag preparsing errors
Errors pre-parsing flags to extract --path were incorrectly logging expected parsing errors when other flags are provided.  Squelched.
/kind bug
=> fix: remove preparsing flag error messages

pkg/functions/client.go, pkg/functions/instances.go, pkg/functions/instances_test.go
- :broom: rename Instance Manager Instance References Manager
The scaffolding code created in the func-runtimes go library implements an _actual_ function `struct Instance`, so to avoid confusion, this renames the manager of instances in the client library a manager of instance"references":  metadata about instances, including locally running jobs.
/kind cleanup
=> src: rename Instance to InstanceRefs

cmd/deploy.go
- :bug: fix builds sometimes not caching
Fixes a bug where the image digest was being cleared on a subsequent deploy, resulting in incorrect metadata and a build stamp which was always out-of-date (effectively disabling cached builds).
/kind bug
=> fix: building resets image digest

pkg/functions/templates.go
- :broom: cleans up templates.Get and extracting `splitTemplateFullname`
/kind cleanup
=> src: cleanup templates.Get

cmd/deploy_test.go, pkg/functions/function.go, pkg/functions/function_envs.go, pkg/functions/repository_test.go, pkg/functions/templates_test.go
- :broom: simplify usage of []Env using a type serialization helpers
Creates a type for []Env with a String and Slice method for presenting a set of environment variables in common formats.
/kind cleanup
=> src: Envs type

pkg/git/git.go, pkg/git/git_test.go
- :bug: Fix PaC not working with `.git` suffixed URLs.
/kind bug
fixes #1707
```release-note
fix: PaC not working with dot git suffixed URLs
```
=> fix: PaC not working with dot git suffixed URLs

cmd/client.go, cmd/deploy.go, cmd/root.go, cmd/run.go, pkg/functions/client.go, pkg/functions/function.go, pkg/functions/job.go, test/e2e/scenario_extended_flow_test.go
- :gift: `func run` supports build options and host (non-containerized) build option
Refactors the run command to include all options from build, in the same manner as deploy.
Updates help text to match the other command format, and lays the verbal groundwork for the difference between containerized (currently default) and non-containerized runs.
Adds the --container flag (currently defaults to true) which will, when disabled, invoke the localhost-based runner which, in this commit, is not yet active.
=> feat: func run support all build options

docs/reference/func_build.md, docs/reference/func_deploy.md, docs/reference/func_run.md
The docs were overlooked in the changes to deploy and run in https://github.com/knative/func/pull/1693. This commit just updates the docs so they are consistent with the binary.
=> chore: update docs from changes to deploy/run

Makefile, cmd/config_volumes.go, pkg/functions/function.go, pkg/functions/function_volumes.go, pkg/functions/function_volumes_unit_test.go, pkg/functions/invoke.go, pkg/k8s/persistent_volumes.go, pkg/k8s/persistent_volumes_test.go, pkg/knative/deployer.go, schema/func_yaml-schema.json
- add `persistentVolumeClaim` and `emptyDir` to the allowed function volumes 
- deploy `persistentVolumeClaim` and `emptyDir` volumes
- add `persistentVolumeClaim` and `emptyDir` as options in config 
/kind api-change
Fixes #1647
```release-note
Allow specifying `persistentVolumeClaim` and `emptyDir` as volumes in functions.
```
**Docs**
```docs
- [knative/docs]: TODO
```
=> add pvc and emptyDir to function_volumes

cmd/invoke_test.go, cmd/run.go, pkg/docker/runner.go, pkg/docker/runner_int_test.go, pkg/functions/client_int_test.go, pkg/functions/client_test.go, pkg/functions/job.go, pkg/functions/job_test.go, pkg/mock/runner.go
- :gift: client Jobs support scaffolding (backwards compatibly)
- Local jobs use a directory rather than filename This sets up for upcoming scaffolding to use as a space for job scaffolding code.
- Places all jobs within a 'runs' directory in ./func rather than 'instances' to further differentiate between an instance and a local run task invoked via .Run
- Updates Jobs' stop handler to have an error return.
- Adds tests which ensure creating and stopping a job are reflected in the client's .Instances().Local() accessor.
- Adds verbose logging support to the Job implementation.
- Adds a cleanup task which will remove orphaned jobs by, in addition to previous logic, checking that there is no longer a process listening on the port indicated by the job.
=> feat: job scaffolding

pkg/builders/buildpacks/builder.go
- :broom: Use `full` builder for Rust. This is need to make some libs work (e.g. openssl).
=> fix: use full builder for Rust

cmd/config.go, cmd/delete.go, cmd/describe.go, cmd/invoke.go
- :broom: More clear error message when path does not contain initialized function.
=> chore: improve error message when no func on path

pkg/functions/client.go, pkg/functions/client_test.go, pkg/functions/function.go, pkg/functions/function_test.go
- :bug: .gitignore file path incorrect when creating in a different path that CWD
- :bug: .gitignore /.func was causing the build stamp to update
- :gift: can now force inclusion of .func in source control by commenting the line
- :gift: adds built log journaling via a WithStampJournal option
/kind bug
```release-note
Fixes an issue where .gitignore was not correctly updated when running func with a custom --path
Improves build caching
```
=> fix: .gitignore .func

pkg/pipelines/tekton/pipelines_pac_provider.go
- :broom: improve error msg when PAC is not installed
Fixes #1724
```release-note
improve error msg when PAC is not installed
```
=> chore: improve error msg when PAC is not installed

cmd/build.go, cmd/config.go, cmd/delete.go, cmd/deploy.go, cmd/describe.go, cmd/invoke.go, cmd/run.go, pkg/functions/function.go
- :broom: adds a new error type `UninitializedError` to minimize redundancy across commands, and applies it in all of the commands which need an initialized function to operate.
Fixes: https://github.com/knative/func/issues/1744
/kind cleanup
=> chore: improve error messages for most commands

cmd/config_git_set.go
- :bug: don't require credentials when not configuring webhook
/kind bug
Fixes #1725
```release-note
don't require credentials when not configuring webhook
```
=> fix: don't require credentials when not configuring webhook

hack/allocate.sh
-  Use Contour Ingress instead of Kourier. Contour will be useful for exposing resources other that knative services (e.g. PaC controller for webhooks).
- User LoadBalancer instead of NodePort. This makes services available on the same port (80) on both:  localhost and docker network.
=> Use Contour Ingress instead of Kourier

pkg/pipelines/tekton/templates.go
- :broom: preparing pipelines as code template for midstream customization
With this change downstream builds can customize the task source for pipeline as code template generated by `func config git set`
=> Prepare pipelines as code template for midstream customization

cmd/invoke_test.go, pkg/docker/runner.go, pkg/functions/client.go, pkg/functions/client_test.go, pkg/functions/function_git_unit_test.go, pkg/functions/function_migrations_unit_test.go, pkg/functions/job.go, pkg/functions/job_test.go, pkg/functions/runner.go, pkg/functions/runner_test.go, pkg/functions/signatures_test.go, pkg/functions/template.go, pkg/mock/runner.go
- :gift: host-based scaffolded function runner
=> feat: host-based scaffolded function runner

pkg/pipelines/resources/tekton/task/func-buildpacks/0.1/func-buildpacks.yaml, pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml, pkg/pipelines/tekton/resources.go, pkg/pipelines/tekton/tasks.go, pkg/pipelines/tekton/templates_pack.go
- The `pack` build task result `IMAGE_DIGEST` is passed to the deploy task. Before this was done only for the `s2i` build.
- The deploy task explicitly sets the `--image` flag.
```release-notes
- On-cluster build: The `pack` build task result `IMAGE_DIGEST` is passed to the deploy task.
- On-cluster build: The deploy task explicitly sets the `--image` flag.
```
=> Pass image with digest to the deploy task

pkg/oci/builder.go
- :broom: Reduce default platforms to likely base set
Removes cross-compiles use during testing to a base set most likely to be those of the target cluster.
Note that when the `environment` reporting is complete, we could further reduce this set to only that of the target cluster.
/kind cleanup
=> reduce default build platforms

cmd/delete.go, cmd/list.go
- :gift: add `ls` as an alias for `func list`
- :gift: add `rm` as an alias for `func remove`
=> feat: add common command aliases

cmd/deploy.go, docs/reference/func_deploy.md, pkg/functions/function.go, pkg/pipelines/tekton/pipeplines_provider.go, pkg/pipelines/tekton/pipeplines_provider_test.go
Refactors PVCSize to treat the Function member as a custom setting, and the in-code constant as the default.
- :bug: Fixes a bug where the PVCSize would reset to the default on deploy
- :gift: Allows the default to be changed by future func version, only pinning the value if explicitly requested by the user.
/kind bug
```release-note
- Fixes a bug where volume size for remote builds was sometimes not respected
```
=> fix: PVCSize resets to default with futureproofing

cmd/invoke.go
- :broom: Suppress invocation logging
Reduces output from `func invoke` to only print when `--verbose`.
In particular the text `Received Response:` is confusing as to where it originated, so it has been placed in the "pretty-printed" response yielded when invoking in verbose mode (`func invoke --verbose`)
/kind cleanup
=> src: invoke response cleanup

Makefile, cmd/environment.go, cmd/func/main.go, cmd/root.go, cmd/root_test.go, cmd/version.go, docs/reference/func_version.md
- :broom: removes version from `func version --verbose`
In an effort to move one step closer to reproducible builds, build timestamp is removed from the CLI version subcommand.
=> src: remove datestamp from binary

pkg/functions/function.go, schema/func_yaml-schema.json
- :broom: image and registry missing `omitempty`
The default func.yaml should be as empty as possible, as it is intended as a way to specify overrides to in-code defaults.
By pre-populating the func.yaml with empty strings, it is ambiguous as to the intent:  eg.  Are you requesting I explicitly set the regitry and image to nothing, or do you not care what I set it too? 
In other words, the initial funciton created by `func craete` should have a registry and image `nil`, indicating the user prefers to use whatever is default, not explicitly setting to emtpy string.
This was mostly fixed in PR #1630.  I think these two were just missed.
/kind cleanup
=> src: add missing 'omitempty' annotations

pkg/functions/function.go, pkg/functions/function_unit_test.go
- :bug: Fix appending SHA256 hash to image reference in ImageWithDigest
/kind bug
Fixes #1768
=> Fix appending SHA256 hash to image reference in ImageWithDigest

cmd/build.go, cmd/config.go, cmd/delete.go, cmd/deploy.go, cmd/describe.go, cmd/invoke.go, cmd/run.go, pkg/functions/client.go, pkg/functions/client_test.go, pkg/functions/errors.go, pkg/functions/function.go, pkg/functions/instances.go, pkg/functions/instances_test.go, pkg/functions/runner.go, pkg/functions/runner_test.go, pkg/functions/templates.go
- :broom: cleans up and tests errors
- :broom: cleans up comments
Moves errors into their own file, updates to using typed error responses in a few more places, cleans a few comments and adds a test.
/kind cleanup
=> src: errors cleanup

pkg/builders/s2i/builder.go
- :broom: default s2i builder as var for ldflags
=> chore: default s2i builder as vars

pkg/functions/errors.go, pkg/functions/runner.go
- :broom: cleans up the run timeout loop and error
Adds the timeout reached to a typed error on timeout, and factors out the liveness check to a function to avoid tail-stacking defer statements in the check loop.
=> src: cleanup the run timeout loop and check

cmd/deploy.go, docs/reference/func_deploy.md
Added shorthand -R for `func deploy --remote` flag to allow `func deploy -R` to work according to the Synopsis
```
SYNOPSIS
{{rootCmdUse}} deploy [-R|--remote] [-r|--registry] [-i|--image] [-n|--namespace]
[-e|--env] [-g|--git-url] [-t|--git-branch] [-d|--git-dir]
[-b|--build] [--builder] [--builder-image] [-p|--push]
[--platform] [-c|--confirm] [-v|--verbose] [--build-timestamp]
```
Fixes #1719
```release-notes
Adds `-R` shorthand for `--remote` flag in `func deploy`
```
=> added shorthand -R for --remote flag

cmd/build.go, cmd/deploy.go, cmd/run.go, pkg/builders/buildpacks/builder.go, pkg/builders/buildpacks/builder_test.go, pkg/builders/s2i/builder.go, pkg/builders/s2i/builder_test.go, pkg/functions/client.go, pkg/functions/client_test.go, pkg/mock/builder.go, pkg/oci/builder.go, pkg/oci/builder_test.go, pkg/oci/containerize.go, pkg/oci/containerize_go.go
- :gift: adds platform build options
Plumbs through the platform CLI flag to the individual builders by creating a client-level functional option for `.Build`, and modifies the builder interface to accept an optional set of requested target platforms.
\* Functional options are primarily useful for providing a simplified public API which can expand over time while remaining backwards-compatible.  The Builder interface is used to structure the functions codebase internally, so the complexity of the options pattern is not necessary and a simple argument will suffice.
=> feat: platform build options

cmd/environment.go, docs/reference/func_config_git_set.md, docs/reference/func_environment.md, pkg/builders/buildpacks/builder.go
Added the default builders variables for listing through func environment command
Fixes #1788
```release-notes
Adds default builders for s2i and buildpacks to `func environment`
```
=> adding default builders

.github/workflows/ci.yaml, Makefile
- Added Rust templates linting to assure needed code style quality
```release-note
Added Rust templates linting into CI workflow
```
**Docs**
```docs
```
=> Added Rust templates linting

pkg/k8s/dialer.go, pkg/k8s/dialer_test.go
- :bug: Fix bad connection handling for `in cluster dialer` which caused confusing error messages (although  functionality was not affected). Connections were closed from wrong end of io.Pipe
which resulted in confusing error logs.
- :gift: Better error handling:
- `ContextDial()` returns some errors immediately instead of deferring them on `Read/Write` operation on returned connection.
-  `ContextDial()` tries to parse `socat`'s stderr and translate it to `Go`'s `net.OpError` instead of just creating error with whole stderr embedded in it.
/kind bug
resolves: #1792
```release-note
fix: connection handling for `in cluster dialer` causing confusing error messages #1792
```
=> fix: bad connection handling for in cluster dialer

Makefile, cmd/func/main.go, cmd/root.go, cmd/root_test.go
- :gift: Knative version now included in func verbose output
- :bug: fixes bug where builds without an associated version number showed `v0.0.0`
- :broom: validates version passed by build is a valid semver
Ensures that `func version` remains consistent; always returning an ascending semver of the version, with the associated knative tag being part of the verbose version information.
Replaces the default v0.0.0 version tag when building from a non-tagged commit to the "human readable" form provided by "git describe".  This consists of the most recently tagged version along with a suffix which consists of the number of commits which have been added since the tagged version, and the hash.
The reasoning behind this change is that we must retain the ability to release versions independently …
=> src: improved version output

pkg/oci/containerize_go.go
- :gift:  Host-built function dependencies
Host-built functions can now import third-party dependencies.
In particular scaffolded (host-built) functions now run a go get on the function (treating it as a library).
=> feat: support dependencies in host-built functions

pkg/oci/builder.go, pkg/oci/builder_test.go, pkg/oci/containerize.go, pkg/oci/containerize_go.go
- :broom: refactor build concurrency test
Expands the builder to include an optional notification channel such that temporary test tooling can be removed entirely from the builder core and logic kept in the test only.
/kind cleanup
=> src: refactor builder concurrency test

hack/allocate.sh, hack/binaries.sh
Updates versions used for the test clutser, and includes a change to use a specific kind node version rather than the kubernetes version per Kind's docs.
- knative_serving v1.10.1
- knative_eventing v1.10.1
- contour v1.10.0
- kubectl v1.27.2
- dapr v1.10.0
- helm v3.12.0
- kind v0.19.0
- kind_node v1.27.1
/kind cleanup
=> chore: test cluster versions update

pkg/functions/client_test.go
- :broom: build tests for single platform
Utilize the platforms option to build test for only one platform when multi-arch is unnecessary.  Speeds up tests.
/kind cleanup
=> src: speed up tests by building with a test platform

pkg/functions/runner.go
- :bug: Fix `choosePort()` for host-runner.
=> fix: choosePort for host-runner

test/presubmit-tests.sh
The Knative test infrastructure runs presubmit tests which are defined in vendor/knative.dev/hack/presubmit-tests.sh. This has been running in test and release infrastructure. It is possible to customize the behavior of this script by defining a handful of functions. The function definitions provided here ensure that we are running tasks that are already being run with the default (e.g. verify-codgen.sh) but make use of our existing build and test targets.
(There also seems to be a stray version of this that I committed a couple of years ago. That has been removed as it is in the wrong location for test-infra and was never used anyway.)
Relates to: https://github.com/knative/func/issues/1333
EDIT: This PR focuses entirely on unit tests. A follow-up PR addressing integration tests will …
=> chore: use a custom presubmit_tests.sh script

Makefile
This makes the test output on github actions a little more reasonable. Otherwise, we are approaching 10k lines per test run.
=> chore: quiet template tests for quarkus, springboot & rust

Makefile, test/presubmit-tests.sh
This commit adds a Makefile target that will simulate the Prow presubmit tests that are run for pull requests on GitHub. It makes use of the same image used by Prow, and runs the ./test/presubmit-tests.sh script so that developers can run the same suite of tests that are run in CI/CD.
/kind chore
Related: https://github.com/knative/func/issues/1333
=> chore: add presubmit-unit-tests Makefile target

pkg/builders/buildpacks/builder.go, pkg/builders/buildpacks/builder_test.go, pkg/builders/s2i/builder.go, pkg/builders/s2i/builder_test.go, pkg/functions/client.go
added the support for funcignore file for excluding the data which don't need to be added to image build
Fixes #1463 
```release-note
```
**Docs**
```docs
```
=> adding support for .funcignore file

Makefile, cmd/func/main.go, cmd/root.go, cmd/root_test.go
This is a backport of #1817 to the 1.10 branch.
The Knative version is now included in version command verbose output
Building an unreleased version no longer returns v0.0.0, but instead the value provided by `git describe --tags` which is the most recent tagged release with a suffix consisting of the number of commits since that release and the short hash.
Verbose output now always includes the current commit on a dedicated line.
```release-note
Improved `func --version` output
```
=> [release-1.10]: src: interstitial commit version (#1817)

pkg/knative/deployer.go
- :gift: Requests that deployed functions listen on all interfaces for requests.
Runtimes should, by default, only listen on the loopback interface for security (they may be `func run` locally).
The ADDRESS environment variable added here on deploy requests the runtime to listen on all interfaces (0.0.0.0) when deployed, since they will need to listen for client requests and for health readiness/liveness probes.
Additionally, now a user who wishes to securely open their function to only receive requests on a specific interface, such as a WireGuard-encrypted mesh network which presents as a specific interface; that can be achieved by explicitly setting the ADDRESS on their function.
NOTE this env variable is only a suggestion, and it is up to the runtimes to read and use.  This is …
=> feat: default ADDRESS env var on deploy

pkg/oci/builder.go, pkg/oci/containerize.go, pkg/scaffolding/scaffold.go
- :bug: error retrying failed host builder builds
The host builder was not properly starting a clean build on retry of a failed build.
This is also the last known bug for the [Scaffolding Subsystem](https://github.com/knative/func/discussions/1589) MVP, closing the Issue-epic #1703
/kind bug
/closes #1703
=> fix: host builder retry error

cmd/root.go
:bug: fixes a missing apply of the verbosity default
/kind bug
=> fix: verbose default not applied

go.mod, pkg/pipelines/tekton/templates.go
- Remove Git task resolver and resolve the task specification locally. This is more reliable, git resolver is timing out on some clusters because git-clone is slow operation.
=> fix: resolve tkn task spec locally

cmd/run.go, pkg/functions/runner.go
:gift: host runs (go) pull dependencies
This is the same logic as what happens during a containerized build, but locally on the host.
`func run --builder=host --container=false`
=> feat: support external deps for host runs

.github/workflows/update-builder.yaml, hack/update-builder.go
- :gift: Periodic GH Action that builds latest paketo jammy builder with two additinal buildpacks: `paketo-community/rust` and `dev.knative-sandbox.go`. The result published it as `ghcr.io/knative/builder-jammy-full`.
=> chore: cron task for paketo's jammy builder

.github/workflows/update-springboot-platform.yaml, hack/update-springboot-platform.js
- :bug: Fix spring boot dependency updater.
=> fix: spring boot dependency updater 

hack/update-builder.go
- :gift: Periodic task now builds `tiny`, `base` and `full` version of paketo jammy builder.
=> chore: multiple variants of builder

hack/release.sh
- :broom: The `./hack/release.sh` script builds binaries that refer to correct tekton tasks. Without this changes binaries refer task from `main` branch, not the release branch.
=> chore: released binaries refer correct tekton task yamls

pkg/pipelines/tekton/templates_integration_test.go, pkg/pipelines/tekton/templates_test.go
Mark test as integration test. The test relies on external service: `https://raw.githubusercontent.com/`.
=> chore: mark test as integration test

.github/workflows/test-unit.yaml, Makefile, test/presubmit-tests.sh
- Refer correct tekton task yamls in tests. Without this change tests would refer tekton task yamls from the `main` branch, not from the PR head branch.
-  Fixed some lint issues.
=> chore: refer correct tekton task yamls in tests

test/oncluster/scenario_github_test.go
- :broom: update github ref used on e2e oncluster tests
=> test: update github ref used on e2e oncluster tests

pkg/oci/containerize.go
:gift: Containers built by the Host builder run as a non-root user.
Impetus is PR #1886 which hardens pod security for services deployed by the Knative Deployer, which causes #1913, an error running host-built function containers which were still attempting to run as root.
(_partially_ fixes #1913)
=> feat: run host-built containers as non-root

docs/CONTRIBUTING.md, docs/building-functions/on_cluster_build.md
Update doc: Go and Rust on cluster build is supported.
=> doc: Go and Rust on cluster build is supported

cmd/environment.go, pkg/pipelines/tekton/templates.go
- :gift: Print tekton tasks urls in output of `func environment`.
=> feat: tekton task urls in the `environment` sub-command output

Makefile, hack/release.sh
* Minimize release binaries size by stripping debug information.
* Release latest version of buildpack tekton task.
=> chore: update release generation

cmd/deploy_test.go, pkg/functions/client.go, pkg/functions/client_test.go, pkg/functions/function.go, pkg/functions/function_unit_test.go
- :bug: Fix parsing of registries with more complex hierarchy (sub-paths). Example of such registry: `us-central1-docker.pkg.dev/my-gcpproject/team/user`.
/kind bug
```release-note
fix: parsing of registries with more complex hierarchy (sub-paths)
```
=> fix: docker registry/repository parsing

cmd/environment.go, docs/reference/func_environment.md
=> Improving func environment command 

hack/update-builder.go
- :broom: Added some standard `org.opencontainers.image.*` labels on our paketo jammy builders.
=> chore: added standard labels for our builders

Makefile
- :broom: Faster `make build`.
- :bug: The `zz_filesystem_generated.go` file must be build **after** CA bundle download.
=> chore: faster `make build`

pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
The older image has been deleted. We need this to even function.
=> chore: update buildah image ref

pkg/pipelines/resources/tekton/task/func-s2i/0.1/func-s2i.yaml
- :gift: Use our own s2i image. It is much more recent (the previous one is 2 years old) but more importantly the new image is multi-arch.
=> Use our own s2i image

.github/workflows/ci.yaml, .github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, .github/workflows/test-integration.yaml, hack/allocate.sh, hack/create-testing-func-image.sh
- :gift: Use a different approach to pass current func image to the tests, this approach does not require modification of task yaml nor access to outer internet (ttl.sh). The important thing is that now we are refering tekton tasks from github --  they are not preinstalled meaning any local patches to task have no effect.
=> fix: use current func image in tests

Makefile
* Use ./mvnw not mvn in tests.
=> chore: use ./mvnw not mvn in tests

hack/allocate.sh
Parallelised cluster allocate script.
=> chore: parallelize cluster allocate script

test/e2e/scenario_no_container_test.go
- :broom: chanded timeout from 5sec to 15secs on wait func to get ready on no-container test
=> test: increase timeout to wait func to get ready on no-container test

pkg/builders/s2i/builder.go, test/oncluster/scenario_runtime_test.go
Fix s2i on cluster RT tests.
* Use smaller s2i builder image for nodejs
* Skip python s2i on cluster build when running in GH action
```release-note
chore: using nodejs-16-minimal instead of nodejs-16 as default builder for JS/TS
```
=> fix s2i on cluster RT tests

.github/workflows/build.yaml, .github/workflows/check.yaml, .github/workflows/ci.yaml, .github/workflows/schema.yaml, .github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, .github/workflows/test-e2e-runtime.yaml, .github/workflows/test-e2e.yaml, .github/workflows/test-embedded-fs.yaml, .github/workflows/test-integration.yaml, .github/workflows/test-podman.yaml, .github/workflows/test-unit.yaml, hack/allocate.sh, pkg/functions/client_int_test.go, test/common/readycheck.go, test/e2e/scenario_extended_flow_test.go, test/e2e/scenario_no_container_test.go
- :broom: removing deprecated method calls on test
- :broom: avoiding nils on http calls for test
- :broom: improving match condition for func run test 
/kind cleanup
=> test improvements remove deprecates avoid nils, bump go version 1.20.x

.github/composite/go-setup/action.yaml, .github/workflows/build.yaml, .github/workflows/check.yaml, .github/workflows/ci.yaml, .github/workflows/schema.yaml, .github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, .github/workflows/test-e2e-runtime.yaml, .github/workflows/test-e2e.yaml, .github/workflows/test-embedded-fs.yaml, .github/workflows/test-integration.yaml, .github/workflows/test-podman.yaml, .github/workflows/test-unit.yaml, .github/workflows/update-builder.yaml
- chore: Add go setup as composite action
This is a very opinionated proposal. I can just `sed` all the version otherwise. :)
There are several go version matrix params, but specifying single value only. I wonder if something more centralized could be a bit easier to maintain. 
/cc @lkingland @matejvasek 
/kind <kind>
Fixes #
```release-note
NONE
```
=> chore: Add go setup as composite action

pkg/docker/platform.go
A malicious image can include a high number of manifests and which makes the loop time controllable by an attacker. This can result in a DoS of func through an endless-data attack vector.
This PR sets a limit that is far more than a legitimate image would require, but that would still be fast to loop though.
/kind bug
Fixes #
```release-note
```
**Docs**
```docs
```
=> Add limit to number of manifests

hack/registry.sh
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding simple Podman insecure registry support

hack/allocate.sh
- Follow up on PR #2060 and add a hook for `podman` and `docker` to the `allocate.sh` 
Fixes #2059
=> Differentiate between podman and docker for local registry connection

hack/allocate.sh
- Adding podman as command, instead of docker (like openshift/release repo does it)
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Using `$CONTAINER_ENGINE` variable instead of hard-coded `docker`

Makefile, cmd/root.go, cmd/subscribe.go, cmd/subscribe_test.go, docs/reference/func.md, docs/reference/func_subscribe.md, pkg/functions/client_int_test.go, pkg/functions/function.go, pkg/knative/deployer.go, schema/func_yaml-schema.json
Little demo: https://youtu.be/O6M7mfR6JfM 
- - :gift: Add new `subscribe` command to create Knative Triggers for event routing
/kind <kind>
Fixes #
```release-note
kn func subscribe will allow you to create Knative Eventing Triggers for improved event processing for kn func
```
**Docs**
```docs
```
=> Adding support for `func subscribe` for creating mutiple triggers, based on event filters

test/e2e/scenario_config-volumes_test.go
- :gift: Adding e2e test for PersistenceVolumeClaim and EmptyDir
/kind <kind>
=> test: adding e2e test for config volumes EmptyDir and PersistentVolumeClaim

README.md
Part of https://github.com/knative/community/issues/1403
Adds a link to the CLOTRIBUTOR page for Knative to the README
=> Added clotributor link to readme

go.mod, pkg/builders/s2i/builder.go
Adds a logging statement if the image is referenced by tag to inform the user of the risk.
```release-note
Log if image is referenced by tag in s2i builder.
```
=> Log if image is referenced by tag

hack/binaries.sh, test/e2e/scenario_subscribe_test.go
- :gift: Adding e2e test for func subscribe 
=> test: adding e2e test for func subscribe command

cmd/subscribe.go
- :gift: Added `--path` option to `func subscribe` command in order to align with other commands
=> adding `--path` option to `subscribe` command

docs/reference/func_subscribe.md
- :broom: Update func subscribe DOC
=> doc: update func subscribe doc

cmd/subscribe.go
- :broom: Update syntax and pass on only the slice
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Smooth syntax and pass only in the filters not the entire config

cmd/subscribe.go, cmd/subscribe_test.go
- :broom: Dont duplicate subscriptions
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Dont duplicate subscriptions

cmd/subscribe_test.go
- :broom: Enhancing test coverage of a different scenario
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Testing two sources(brokers) and third invocation for an override on the first

.github/workflows/update-quarkus-platform.yaml, .github/workflows/update-springboot-platform.yaml
Use correct Go version in GH action.
Incorrect Go version was causing failure of auto-updater for Quarkus and Spring templates.
=> fix: use correct Go version in GH action

cmd/deploy.go, cmd/deploy_test.go, pkg/functions/function.go, pkg/functions/function_test.go, pkg/pipelines/tekton/gitlab_test.go, schema/func_yaml-schema.json
Added a `Local` field to represent the local spec (such as `Remote`)
- 🎁 Added a new field `Local.Remote` to the `function` spec
- 🎁 Modified `func.write` to write it only to `.func/local.yaml` so it is not persisted across clones but only locally
- 🎁 Added unit tests to ensure the expected behaviour
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding local field to function for handling transient spec (Local.Remote)

go.mod
- Remove toolchain directive
We need to drop this at least temporarily until release is done, because one of our tools performing auto-update deps is not working with `toolchain` directive yet.
/cc @knative/knative-release-leads 
/cc @matejvasek @lkingland 
/kind <kind>
Fixes #
```release-note
NONE
```
=> Remove toolchain directive

hack/update-builder.go
Newer version of pack does support adding custom labels to the builder so the Dockerfile workaround is not needed anymore.
Also the Dockerfile workaround was failing recently due to high number of layers in full builder.
=> chore: updated BP builder updater

cmd/run.go
-fixes typo in  run command long description
-
-
/kind <kind>
Fixes #2167 
```release-note
```
**Docs**
```docs
```
=> typo in run cmd

docs/reference/func_run.md
- updates after running `make` 
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Updates to MD file

pkg/pipelines/tekton/gitlab_test.go
skip gitlab test because it often fails with unrelated issue to the PR changes
issue https://github.com/knative/func/issues/2185 is opened for tracking
=> unreliable gitlab test skip

hack/allocate.sh, hack/binaries.sh
- :broom: Update or clean up current behavior
/cc @matejvasek 
/wip
Let's see if it works with current dependencies, or we need to bump those first. 
Fixes #
```release-note
NONE
```
=> chore: Update setup E2E to match latest Knative release

pkg/oci/builder_test.go, pkg/oci/containerize.go
- :gift: host builder supports setting static metadata envs on resultant container
For now, this includes FUNC_CREATED and FUNC_VERSION to assist with current debugging and versioning efforts.
Should these prove useful, we should add them to containers built with Pack and S2I as well.
Fixes #
```release-note
Functions built with the experimental "Host" builder include FUNC_CREATED and FUNC_VERSION metadata environment variables.
```
**Docs**
```docs
```
=> feat: host builder metadata envs

hack/allocate.sh
- chore: Refactor cluster allocation script to use latest Knative bits
IMO it could be pushed further to wrap also kn binary version. But for now it seemed to me like a super quick win. Functions are inspired by client and hack scripts. i.e. a bit verified. :)
/cc @matejvasek @lkingland 
```release-note
NONE
```
=> chore: Refactor cluster allocation script to use latest Knative bits

go.mod, go.sum
- :broom: Update to latest of CloudEvents SDK for GO
/kind <kind>
Fixes #
```release-note
- :broom: Update to latest of CloudEvents SDK for GO
```
**Docs**
```docs
```
=> [release-1.13 ]Bump to latest of GO SDK for CE

go.mod, go.sum
- :broom: Update to latest CloudEvents Go-SDK
/kind <kind>
Fixes #
```release-note
- :broom: Update to latest CloudEvents Go-SDK
```
**Docs**
```docs
```
=> [release-1.12] Bump to latest of GO SDK for CE

cmd/build.go, cmd/deploy.go, cmd/root.go, pkg/config/config.go, pkg/config/config_test.go, pkg/oci/pusher.go, pkg/oci/pusher_test.go
- **fix env var casing otherwise flags with hyphens will continue to have hyphens**
- **Introduce an --registry-insecure flag**
=> Introduce a --registry-insecure flag

cmd/build.go, cmd/build_test.go, cmd/deploy.go, cmd/deploy_test.go, go.mod, go.sum, pkg/functions/client.go, pkg/functions/client_test.go, pkg/mock/pusher.go, pkg/oci/mock/registry.go, pkg/oci/pusher.go, pkg/oci/pusher_test.go, third_party/VENDOR-LICENSE/cloud.google.com/go/compute/metadata/LICENSE
This PR adds HTTP basic auth via CLI arguments to the "host" builder.
Because the Host builder is still behind a feature flag as it is experimental, the newly added flags are currently hidden.
The purpose of this addition is to enable a common use-case of using a third-party credentials management system rather than relying on those provided by the respective registries (docker credentials manager, AWS, etc) or the system.  This is especially useful when considering that the "host" builder does not require docker nor podman be installed.
For example the venerable `pass` command line tool, or the recent Bitwarden, 1Password, etc.
Here is an example of how this works using the Bitwarden `bw` command, which will prompt the user for the repository master password on each deploy.
```
func …
```
=> Basic auth

.github/workflows/ci.yaml, .github/workflows/test-podman.yaml, Dockerfile.utils, cmd/func-deployer/main.go, hack/setup-testing-images.sh, pkg/k8s/dialer.go, pkg/k8s/persistent_volumes.go, pkg/k8s/persistent_volumes_test.go, pkg/pipelines/resources/tekton/task/func-deploy/0.1/func-deploy.yaml
* The utility (socat/tar) image is now built in GH Action and stored in GH image registry. Previously it was build completely ad-hoc and stored in some quay.io repository.
* The utility image contains new tiny standalone `deploy` binary. This binary is used in deploy task instead of full-fat `func` binary. The binary is smaller and breaks cyclical dependency where `func` CLI references image with `func` CLI itself.
=> Standalone deploy binary/image 

docs/function-templates/golang.md
- :broom: Update temple doc, based on recent changes around their signature
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Usage of only proper handler API, no longer need for redundant Context

docs/reference/func_build.md, docs/reference/func_deploy.md
- the `make` seems to be forgotten often, running it after 2234 PR
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> make was not called #2234

pkg/functions/invoke.go
- :bug: func invoke sets the data in the event after unmarshalling the string, so that the event does not treat the data as a json string
-
-
/kind bug
Fixes #2241 
```release-note
func invoke now correctly handles data with contenttype application/json
```
=> func invoke handles json properly

pkg/knative/deployer.go, pkg/knative/deployer_test.go, pkg/knative/testdata/test_empty
- fix: Fix Test_deployerNamespace with empty kubeconfig
That's should work for any cluster/no-cluster situation hopefully.
/cc @gauron99
=> fix: Fix Test_deployerNamespace with empty kubeconfig

.github/workflows/update-quarkus-platform.yaml, .github/workflows/update-springboot-platform.yaml
The newer version of `octokit` (v4) uses some different module type and `require()` does not work nice with it.
This is required to fix currently failing periodic quarkus/sprint-boot version update.
=> fix: pin octokit npm module version to 3

.github/workflows/test-unit.yaml
Upload results of unit tests on various operating systems at once as opposed to uploading them individually.
=> chore: upload coverage of unittests together

.gitignore, pkg/builders/s2i/assemblers.go, pkg/builders/s2i/builder.go, pkg/builders/s2i/builder_test.go, pkg/oci/pusher_test.go, pkg/pipelines/tekton/validate_test.go
- :gift: S2I builder now supports Go functions
- :gift: S2I Go functions now include Instance-based method signatures and lifecycle events
```release-note
The S2I builder now supports Go functions.
Go functions built with the S2I builder now support the new instance-based method signatures and lifecycle methods.
```
=> feat: s2i builder go support

pkg/pipelines/tekton/gitlab_test.go, pkg/pipelines/tekton/pac/client.go, pkg/pipelines/tekton/templates.go
```release-note
fix: pipelines as code build -- build via git hook in tekton
```
=> Fix PaC build

pkg/pipelines/tekton/templates.go
Newer versions of PaC do not work without the quotes.
=> fix: pipeline run yaml format for newer PaC

.github/workflows/test-integration.yaml
Save logs as an GH artifact. Print to stdout sometimes freezed.
=> chore: cluster log

cmd/build.go, cmd/deploy.go, cmd/deploy_test.go, pkg/builders/buildpacks/builder.go, pkg/builders/buildpacks/builder_test.go, pkg/docker/creds/credentials.go, pkg/docker/creds/credentials_test.go, pkg/functions/client_int_test.go
Use func without the need for HOME definition or accessible ~/.config with slightly limited functionality (like docker creds or local templates/repos or the pack builder)
When running `func deploy` without `HOME` or `XDG_CONFIG_HOME` specified, deployment is possible if the correct credentials are provided via user prompt (if needed). Additionally, pack builder requires some HOME path for its dot directory where it stores data hence it needs HOME to work. S2i builder is non-problematic. 
/kind bug
Fixes #2150
=> Run func without HOME defined/ unaccessible .config dir

cmd/deploy.go
- :bug: Honor `--registry-insecure` flag in `deploy` command
/kind bug
While playing with `func` in a local environment (with `kind`), I've noticed `certificate signed by unknown authority` issues when trying to connect to my local registry, despite passing the `--registry-insecure` flag:
```shell
$ kn func deploy --path myfunc --remote --registry kind-registry:5000 --registry-insecure
```
> Creating Pipeline resources
> Error: failed to run pipeline: creating push check transport for kind-registry:5000 failed: Get "https://kind-registry:5000/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
Same result with `FUNC_REGISTRY_INSECURE`; after debugging, it turns out that `RegistryInsecure` was simply not forwarded from `deployConfig` to …
=> Honor --registry-insecure flag in deploy command

pkg/pipelines/tekton/pac/pac.go, pkg/pipelines/tekton/pipelines_pac_provider.go
* Fixed the issues where PaC configuration failed under unprivileged user.
```release-note
fix: Pipelines as Code setup failure under unprivileged user
```
=> fix: PaC build

cmd/build.go, cmd/deploy.go
- :broom: Clarify `--registry-insecure` flag description
Related to #2335, where we discovered that the description of `registry-insecure` flag was not really accurate/clear.
After investigation, I've found that enabling this flag just means "skip TLS certificate verification when communicating to the registry", not "allow plain HTTP registries", as the current description ("Disable HTTPS when communicating to the registry") can let users think.
---
Today, the `RegistryInsecure` boolean in the config (filled from the flag) is used at two places:
1) In the `build` command: https://github.com/knative/func/blob/1e7dd33/cmd/build.go#L389
The value is simply forwarded to the `Pusher`, and is used to configure `InsecureSkipVerify`: …
=> Clarify --registry-insecure flag description

.github/workflows/test-integration.yaml, docs/reference/func_build.md, docs/reference/func_deploy.md, pkg/pipelines/tekton/gitlab_test.go
- Optimized disk usage for integration tests in GH Action by deleting unnecessary software (.NET, Haskell, Android SDK). This saves cca 11GB.
- Update generated documentation since it was not updated in PR that modified flags and thus documentation.
- Added timeout in test to wait until gitlab setting modification is in effect.
=> Optimized disk usage in GH Action for integration tests

pkg/docker/docker_client.go, pkg/docker/docker_client_test.go
* Fixed mountpoint of docker socket for `Docker Desktop`.
fixes: #2347
```release-note
fix: buildpack build failure caused by wrong socket mount-point when using Docker Desktop
```
=> fix: mount of Docker API socket from Docker Desktop

hack/update-codegen.sh
Force empty kubeconfig so default namespace in --help is "default" not the current kubeconfig context.
This is required since otherwise `./hack/verify-codegen.sh` would fail on machines where kubectl context NS is other  than `default`.
=> fix: codegen does not use current ns

docs/reference/func_yaml.md
- correction the docs for build section
-
-
Fixes #2183
```release-note
```
**Docs**
```docs
```
=> corrected doc

pkg/knative/deployer.go
-
-
-
/kind bug
Fixes #2257
```release-note
```
**Docs**
```docs
```
=> corrected error msg

cmd/deploy.go, cmd/deploy_test.go, cmd/run.go
allow tagged images to be deployed directly when specifying --build & --push as false
- with extra tests
fixes https://github.com/knative/func/issues/2331
=> fix: Allow undigested images to be deployed directly 

.github/workflows/test-unit.yaml
It appears that the cargo in no longer part of GHA image at least for macOS.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Fix failure in GHA caused by missing cargo bin

test/e2e/scenario_runtime-http_test.go
- Add e2e tests for Go functions using s2i builder (**except** for OnCluster builds scenarios)
=> Adding GO s2i to e2e test suite

cmd/build.go, cmd/deploy.go, cmd/deploy_test.go, cmd/run.go, cmd/run_test.go, pkg/docker/runner_int_test.go, pkg/functions/client.go, pkg/functions/client_int_test.go, pkg/oci/pusher_test.go
In order to match the `deploy` command, make it possible to `run` digested images as well when building into the container
Ive added a way to use digested/ valid undigested images to be run using `func run` cmd. With`--build=false` one can also run the undigested images directly via skipping the build and using the `--image` for the image name that they want to deploy.
Ive also added tests that cover which image gets passed on to `.Build.Image` (which is the image used for the runner) and therefore what image actually gets "run".
Added a return value to `client.Push` which now matches build function (bool indicating if the current push/build was successful or not) 
todo:
=> allow digested images to be 'run'

Dockerfile.utils, cmd/func-util/main.go, pkg/pipelines/tekton/tasks.go, pkg/pipelines/tekton/templates.go, pkg/pipelines/tekton/templates_pack.go, pkg/pipelines/tekton/templates_s2i.go, test/oncluster/scenario_runtime_test.go
- :gift: Enabled on-cluster s2i build for Go by adding scaffolding task into the tekton pipeline.
This is alternative version where the util image is rootfull. Since git and buildpack are already rootfull I don't see any issue with this. In addition this does not require FSGroup setting which makes it easier to port it in midstream. For OCP we would have to remove the FSGroup part in midstream patching process.
Fixes #2443
```release-note
feat: enabled on-cluster s2i build for Go
```
=> On cluster s2i build for Go (alternative version)

Dockerfile.utils, cmd/func-util/main.go, go.mod, go.sum, pkg/pipelines/tekton/tasks.go
- Incorporate `s2i`into the func-utils image.
=> Add s2i to the func-utils image

Makefile
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Revert bad changes

pkg/testing/testing.go
This chages are meant to preventing dubios ownership repository error on git unit tests (running on Prow/CI)
Sample error observed on midstream CI
```
--- FAIL: TestTemplates_Remote (0.01s)
templates_test.go:184: failed to get repository from URI ("http://127.0.0.1:38599/repository.git"): failed to clone repository: unexpected client error: unexpected requesting "http://127.0.0.1:38599/repository.git/info/refs?service=git-upload-pack" status code: 500
fatal: detected dubious ownership in repository at '/go/src/github.com/openshift-knative/kn-plugin-func/pkg/functions/testdata/repository.git'
To add an exception for this directory, call:
git config --global --add safe.directory /go/src/github.com/openshift-knative/kn-plugin-func/pkg/functions/testdata/repository.git
```
=> test: preventing dubios ownership repository error on git unit tests

pkg/k8s/dialer.go, pkg/k8s/dialer_unit_test.go
It appears that Go's `MatchReader()` returns `true` only if two characters are written to the writer after the searched word. Thta's mostly all right because `socat` actually writes several more lines to stderr. However this new implementation is better it should signal immediately when searched patter is written to the writer.
See: https://pkg.go.dev/github.com/agext/regexp#section-documentation
>Note that regular expression matches may need to examine text beyond the text returned by a match, so the methods that match text from a RuneReader may read arbitrarily far into the input before returning.
See also: https://stackoverflow.com/questions/76559206/how-to-match-a-regular-expression-on-a-slow-hanging-io-reader-in-go
KMP: https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_ …
=> Improve socat connection success detection using KMP

cmd/deploy.go, cmd/deploy_test.go
Makes the image digest check and validation a bit more permissive.
Fixes #2508
/kind bug
```release-note
Fixes a bug where registries could sometimes not specify port
```
=> fix: make image digest check more permissive

pkg/builders/s2i/assemblers.go, pkg/functions/runner.go, pkg/oci/containerize_go.go
- Remove unnecessary 'go get' commands
=> Remove unnecessary 'go get' commands

pkg/pipelines/tekton/templates_s2i.go
- :broom: Remove unnecessary annotations from Pipeline-as-Code template
These extra annotations prevents the pipeline to be triggered on Openshift 
/kind cleanup
=> Remove unnecessary annotations from Pipeline-as-Code template

pkg/pipelines/tekton/tasks.go
- :broom: Set default value for REGISTRY param on func-s2i task
/kind cleanup
=> Set default value for REGISTRY param on func-s2i task

test/e2e/scenario_config-envs_test.go, test/e2e/scenario_config-labels_test.go, test/e2e/scenario_config-volumes_test.go, test/e2e/scenario_remote-repository_test.go
- :broom: Making config envs tests builder agnostic
/kind cleanup
The referred test are written using go functions which previously were only supported with `pack` builder. Since `s2i` builder also can build go functions now, the `--builder` specific flags are no longer required.
=> test: making e2e config tests builder agnostic

pkg/builders/s2i/builder.go, pkg/pipelines/tekton/pipelines_provider.go
When running on Windows the path separators in symlink target is backslash. This must be fixed up when uploading source code into docker daemon or into cluster volume.
Fixes #2529
/kind bug
```release-note
fix: Go functions fails to build using S2I on Windows
```
=> Fix symlink path separators

.github/workflows/test-unit.yaml, test/oncluster/scenario_remote-repository_test.go
- :broom: Set branch on remote repository test.
- It also contains a fix environment [error](https://github.com/knative/func/actions/runs/11284604957/job/31403100368?pr=2540#step:9:136) on python test-template run on GitHub action
/kind cleanup
=> Enforce branch on test remote repository

pkg/pipelines/tekton/tasks.go
- :bug: Fix missing `source` workspaces declaration in the `scaffold` task. This led to TaskRun ending with `TaskRunValidationFailed: workspace binding "source" does not match any declared workspace`.
This behaviour was observed by @alanreynosov on his k3s cluster, we have not seen it so far.
/kind bug
```release-note
fix: workspace binding "source" does not match any declared workspace for scaffold task
```
=> Fix missing workspaces decl in the scaffold task

cmd/prompt/prompt.go, pkg/docker/creds/credentials.go, pkg/docker/creds/credentials_test.go
Added `repository` value (now it is `registry/repository`) to prompt for credentials where its used for printing out tto terminal "during the prompt" to make it easier for the user to see what he is trying to provide credentials for.
Additionally I have created a [new issue](https://github.com/knative/func/issues/2595) that is a followup to this and its' purpose is to further optimize this "credentials" process
fix https://github.com/knative/func/issues/2562
=> add repository to the credentials prompt

pkg/docker/runner_int_test.go, pkg/functions/client_int_test.go, pkg/k8s/dialer_test.go, pkg/k8s/logs_test.go, pkg/k8s/persistent_volumes_test.go, pkg/knative/integration_test.go, pkg/pipelines/tekton/gitlab_test.go, pkg/pipelines/tekton/pipelines_integration_test.go
- :broom: Fix some linter errors in integration tests
=> Fix some linter errors in integration tests

hack/update-builder.go
Enable arm64 support for tiny builder (Java,Go).
This PR actually enables only Java since some additional work has to be done for Go because upstream paketo buildpack do not support Go fully yet.
=> Provide tiny buildpack builder image for ARM64

hack/update-builder.go
Fixed authorization by setting keychain for the pack client.
This is required since recently we set pull policy to "always" recently.
=> Fix authorization for buildpack builder periodic task

hack/update-builder.go
Added adjustments that enable Go buildpack build on arm64 machines. Paketo buildpack do not distribute serveral buildpacks in arm64 variant, so we need to build them.
Namely we need to build:
* go
* go-dist
* go-build
* go-mod-vendor
* git
fixes #2623
=> Enable Go ARM64 buildpack

.github/workflows/ci.yaml
Keeps the Go version used by Knative projects in sync with each-other and tooling.
/kind cleanup
=> use knative go setup in ci

.github/workflows/ci.yaml, .gitignore, Dockerfile.utils, hack/fetch-util-img-prerequisites.sh, hack/setup-testing-images.sh
Removed dependency on 
* `index.docker.io/library/golang:1.23-alpine3.20` and
* `index.docker.io/library/alpine:latest`.
For future I consider making the image `scratch` or at least `distroless` but for now it's still `alpine`.
Also we might consider skipping the `builder` part -- we could build the binaries locally and then use `COPY`.
Also I hate the fact that the `ADD` clause do not have `--from` flag, because of that I have to do fetching outside of the `Dockerfile`.
=> Remove dependency on docker hub

.github/workflows/test-e2e-oncluster.yaml, pkg/docker/pusher.go, pkg/pipelines/tekton/gitlab_test.go
* Removed usage of ttl.sh registry in the tests.
* Fixed detection of hostname resolution failure.
=> Remove usage of ttl.sh

cmd/run_test.go
add a test for "Func run with digested image when function is already built, expecting to override said built image"
=> test for func run with digested image override

hack/allocate.sh, hack/install-binaries.sh
beginning with eventing 1.17, tests now fail -> kind type of eventing CRD was never capitalised (how did this work?) and eventing now requires 1.30+ k8s version -> bumping
=> fix: capitalise kind broker and bump versions in script

Dockerfile.utils
Previously I thought the platform does not matter for 'scratch'. However the image build is failing in CI.
It worked on my machine with both podman and moby.
=> Set platform of builder image

pkg/oci/containerize_test.go, pkg/oci/testdata/test-links/absoluteLink, pkg/oci/testdata/test-links/absoluteLinkWindows
Some tools dislike having questionable symlinks in git repository so we must create this symlinks dynamically in the test instead of having it committed into the repository.
=> Create test symlinks dynamically

cmd/deploy.go, docs/reference/func_deploy.md, pkg/functions/function.go, pkg/k8s/persistent_volumes.go, pkg/k8s/persistent_volumes_test.go, pkg/pipelines/tekton/pipelines_provider.go, pkg/pipelines/tekton/pipelines_provider_test.go, schema/func_yaml-schema.json
Adds the --remote-storage-class flag which allows specifying a storage class name for the PVC used for on-cluster builds.
```release-note
- Adds the ability to specify a storage class for remote build volumes with --remote-storage-class
```
=> feat: remote storage class

cmd/invoke.go
- removes base64 encoding of request in `invoke` command  
/kind bug  
Fixes #2545  
<div align="center">
</div>
=> Bug: Fixes Incorrect Implementation of --file Option

cmd/invoke.go, pkg/functions/client_test.go, pkg/functions/invoke.go
Changes the datatype of `Data` member of InvokeMessage to be of type `[]byte` as discussed in https://github.com/knative/func/pull/2715#issuecomment-2686007798
Fixes #2732
=> Refactor data member of the InvokeMessage to be []byte

.github/workflows/ci.yaml, .github/workflows/test-e2e-oncluster-runtime.yaml, .github/workflows/test-e2e-oncluster.yaml, .github/workflows/test-e2e-runtime.yaml, .github/workflows/test-e2e.yaml, .github/workflows/test-integration.yaml, .github/workflows/test-podman.yaml
Add a retry functionality to our current allocate script in the workflows and the e2e runtime test which I saw were the most affected by the flakiness of (probably) not enough resources on the host the runners run on. 
This should ensure that less human resources are needed for maintenance of these tests
=> Add a retry functionality to workflows

Makefile
bump golangci in our scripts (used in ci.yaml) to match the new version in knative/actions
https://github.com/knative/actions/commit/da50b2717e4c596bc79f7d49aea97b7cd7fc0a68
- failing workflow on main branch (ci) https://github.com/knative/func/actions/runs/13788097455/job/38562329024
=> golangci bump in Makefile

pkg/builders/builders_int_test.go, pkg/builders/testdata/go-fn-with-private-deps/.funcignore, pkg/builders/testdata/go-fn-with-private-deps/.gitignore, pkg/builders/testdata/go-fn-with-private-deps/README.md, pkg/builders/testdata/go-fn-with-private-deps/func.yaml, pkg/builders/testdata/go-fn-with-private-deps/go.mod, pkg/builders/testdata/go-fn-with-private-deps/go.sum, pkg/builders/testdata/go-fn-with-private-deps/handle.go, pkg/builders/testdata/go-fn-with-private-deps/handle_test.go
Just added tests that are skipped for now. The actual functionality will be added later.
=> Add testcase for Go private repositories

pkg/docker/creds/credentials_test.go
The unit test got flaky after the auth version bump (im pretty sure) so in attempt to remedy this flakyness I edited the auth test function.
Main changes>
- certificate generation gets its own function
- removed the http default transport hack which got created at the `startServer` and changed it into: create custom http transport on each run and pass it to the called function.
=> fix: create custom http transport for each run for Auth tests

pkg/builders/builders_int_test.go, pkg/builders/testdata/go-fn-with-private-deps/go.mod, pkg/builders/testdata/go-fn-with-private-deps/go.sum
* Use tiny instead of base BP builder (since it has smaller footprint).
* Decrease minimal required Go version (S2I images are on Go 1.22 supported by RH).
* Make the self-signed certificate CA==true so it works with `update-ca-trust` utility.
=> Test adjustments

pkg/functions/function.go, pkg/functions/function_unit_test.go, pkg/k8s/labels/labels.go, pkg/knative/deployer.go, pkg/knative/lister.go
- Removes `function.knative.dev` and `boson.dev` annotations.
- Adds conditional check for `dapr.io` annotations to only add them if `dapr-system` namespace exists.
Fixes #2565
(with dapr installed in cluster)
```
$ kubectl describe --all-namespaces kservice 
Name:         func-test
Namespace:    default
Labels:       <none>
Annotations:  dapr.io/app-id: func-test
dapr.io/app-port: 8080
dapr.io/enable-api-logging: true
dapr.io/enabled: true
dapr.io/metrics-port: 9092
serving.knative.dev/creator: kubernetes-admin
serving.knative.dev/lastModifier: kubernetes-admin
```
(without dapr installed)
```
$ kubectl describe --all-namespaces kservice
Name:         func-test
Namespace:    default
Labels:       <none>
Annotations:  serving.knative.dev/creator: kubernetes-admin …
```
=> Removes redundant default labels and annotations

pkg/builders/builders_int_test.go, pkg/builders/buildpacks/builder.go, pkg/functions/function.go, schema/func_yaml-schema.json
This is in particular useful for using paket bindings, e.g. to inject git credentials into build process.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Allow host mounts for build phahse

pkg/builders/s2i/builder.go, pkg/builders/s2i/builder_test.go
Basically a revert of https://github.com/knative/func/pull/1063.
Today's podman  (+v4.9)  works all right.
=> Use s2i in standard mode, not "as-dockerfile"

pkg/builders/s2i/assemblers.go
- :bug: Return error code when the function was not compiled
- :bug: Run `go mod tidy` on scaffoded code
/kind bug
```release-note
fix: Go s2i build issue with user added dependencies
```
=> Improvements for Go s2i assembler

pkg/scaffolding/scaffold.go, pkg/scaffolding/scaffold_test.go, pkg/scaffolding/testdata/testwrite/go/scaffolding/instanced-http/go.mod
Using incorrect name works for a functions with flat structure -- no sub-packages. When sub-packages are used we need to refer the user module by its true name.
```release
fix: allow sub-modules for Go functions
```
=> Fix: Go scaffolding uses correct module name

hack/cmd/update-builder/main.go
The paketo project moved some buildpack from gcr.io to docker.io.
=> Fix buildpacks builder update task

.github/workflows/test-e2e-runtime.yaml
- :gift: Adding test on arm64 for go and quarkus runtimes
/kind cleanup
=> Update e2e ci workflow to test against arm for go and quarkus

hack/cmd/update-builder/main.go
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Enable arm64 python buildpack

test/e2e/scenario_config-envs_test.go
e2e scenarion config test errorf format fix
This new format is for go 1.24 which is introduced in the next open deps PR
=> fix: e2e scenarion config test errorf format for go 1.24 

.github/workflows/test-podman-next.yaml
- :broom: Update podman next install to use fedora 41 packages
=> upgrade podman-next packages to fedora 41 for nightly podman test

pkg/builders/builders_int_test.go, pkg/builders/buildpacks/builder.go
Zero value implies override (to root presumably),
we must set it to negative value.
I really dislike that zero value is not neutral here.
fixes: #2516
```release-note
fix: error "failed to write group file" when using untrusted builder (#2516)
```
=> Fix: do not override uid/git in buildpack builder

pkg/builders/buildpacks/builder.go
Make heroku's builders trusted.
fixes #2516
```release-note
feat: make heroku's builders trusted
```
=> Make  docker.io/heroku/ builders trusted

hack/cmd/update-builder/main.go
The paketo is moving to docker.io from gcr.io.
=> Fix quarkus buildpack image reference

pkg/pipelines/tekton/tasks.go
- :bug: Tekton task "func-buildpacks" prepare/results steps use non-multi-arch bash:5.1.4 image, causing exec format errors on ARM64
/kind bug
Fixes #2835
```
fix: fixes issue with func in-cluster build/deploy pipelines to work on ARM64
```
=> Issue #2835 - Fix Tekton task "func-buildpacks" prepare/results steps use non-multi-arch bash:5.1.4 image, causing exec format errors on ARM64

cmd/mcp.go, cmd/root.go, docs/reference/func.md, docs/reference/func_mcp.md, go.mod, go.sum, pkg/mcp/mcp.go
This PR aims to add `func mcp` command which can be used to start a MCP (Model Context Protocol) server.
Part of #2690
=> feat: adds command for mcp server

cmd/build.go
This initialized check is redundant, and leads to an error in a forthcoming E2E test case, and is thus removed here preemptively.
/kind cleanup
=> fix: remove redundant initialized check

cmd/config_envs.go, docs/reference/func_config_envs_remove.md
```release-note
func config remove now supports noninteractive usecases via a --name flag
```
=> feat: add noninteractive path to func config envs remove

pkg/functions/runner.go
The "PORT" env is deprecated in favor of LISTEN_ADDRESS.  This change moves us further towards fully implementing that across the runtimes.  PORT is left for now for backwards compatibility.
=> feat: add LISTEN_ADDRESS to Python default runner

cmd/deploy.go
Give a more informative error when attempting to run a `func deploy --remote --git-url=x` that we still need local source.
This is needed because, conceptually local source would not be required for this case, but we need to update the remote build pipeline flow to check out the code on-demand in order for it to read metadata (like function name).  For now, this code flow expects the source code to be available locally.
=> feat: improved error on remote deploy without local source

hack/allocate.sh, hack/common.sh, hack/install-binaries.sh, hack/registry.sh
Development cluster setup scripts now support MacOS.
```release-note
Local clusters can now be set up on MacOS via the repository's allocate.sh and registry.sh scripts.
```
=> feat: macos support for dev cluster scripts

pkg/builders/s2i/builder.go, pkg/oci/go_builder.go, pkg/oci/python_builder.go
- :gift: Python and Go function listen dualstack.
On Linux listening on `[::]` also listen on `0.0.0.0`.
```release-note
feat: Python and Go function listen dualstack
```
=> feat: Python,Go func listen dual-stack

cmd/describe.go, cmd/describe_test.go, pkg/functions/client.go, pkg/knative/describer.go
Adds a "Labels" section to describe command's output.
Note that, as with the other `func config ...` commands, adding unit tests is not possible without a refactor.  The forthcoming E2E tests do test these features, and unit tests will be added when these subcommands are refactored to match the testability of the other commands.
```release-note
Function describe subcommand now includes labels.
```
=> feat: add labels to func describe

test/e2e/scenario_subscribe_test.go
Preventing 503 error on e2e subscriber test, by ginving a little more time before assertion.
=> Prevent 503 on e2e subscriber test

.gitignore, pkg/functions/client_int_test.go, pkg/functions/client_test.go, pkg/functions/function_test.go, pkg/functions/repositories_test.go, pkg/functions/repository_test.go, pkg/functions/templates_test.go, pkg/functions/testdata/default_home/README.md, pkg/oci/go_builder.go
- Default builder and pusher set to embedded Host Builder/Pusher(oci)
- Most tests clear environment
- Environment defaults can be controlled via environment variables
- Tests which require back-compat `git` binary actively check and skip when running with a cleared environment (both integration and unit).
- Bugfixes for when run in tandem with E2E tests
- Ignores go-created directories in the default home path (testdata)
/kind cleanup
=> chore: integration test isolation

pkg/docker/creds/credentials_test.go, pkg/docker/pusher_test.go, pkg/docker/runner_test.go, pkg/functions/client_test.go, pkg/functions/config_test.go, pkg/functions/function_envs_unit_test.go, pkg/functions/function_git_unit_test.go, pkg/functions/function_labels_unit_test.go, pkg/functions/function_migrations_unit_test.go, pkg/functions/function_options_unit_test.go, pkg/functions/function_test.go, pkg/functions/function_unit_test.go, pkg/functions/function_volumes_unit_test.go, pkg/functions/instances_test.go, pkg/functions/job_test.go, pkg/functions/repositories_test.go, pkg/functions/repository_test.go, pkg/functions/runner_test.go, pkg/functions/templates_test.go, pkg/knative/deployer_test.go, pkg/pipelines/tekton/validate_test.go, pkg/scaffolding/detectors_test.go, pkg/scaffolding/scaffold_test.go
removes !integration build tags
The current build tagging system was predicated on the idea that
integraion, e2e and unit tests are entirely separate.  The correct way
to treat these is as inclusive with unit tests.  Thus this pr removes
the exclusion of unit test from integration tests runs, treating `-tags
integration` as indicating "unit tests plus integration tests".
/kind cleanup
=> chore: fix build and test tags

pkg/oci/mock/registry.go
=> chore: reduce logging verbosity in mocks

.github/workflows/test-integration.yaml, docs/CONTRIBUTING.md, hack/allocate.sh, hack/install-gitlab.sh, hack/patch-hosts.sh, hack/test.sh, pkg/builders/builders_int_test.go, pkg/builders/testdata/go-fn-with-private-deps/go.mod, pkg/builders/testdata/go-fn-with-private-deps/go.sum, pkg/builders/testdata/go-fn-with-private-deps/handle.go, pkg/pipelines/tekton/pipelines_int_test.go, test/e2e/scenario_subscribe_test.go
The `localtest.me` domain is shorter than `127.0.0.1.sslip.io`, but foremostly  is has `AAAA` record.
=> Use localtest.me instead of sslip.io

pkg/mcp/mcp.go
This PR adds resources and prompts of the func subcommands `help` for the LLM context
=> mcp: adds resources and prompts for func subcommands

Makefile, go.mod, pkg/app/app.go, pkg/functions/function.go, pkg/version/version.go
- Refer correct version of schema in func.yaml. Before we erroneously referred `specversion`, *not* `git` reference (branch/tag/hash).
- Moved version info into separate package to break cyclical dependency.
/kind bug
```release-note
fix: refer correct version of schema in func.yaml
```
=> fix: refer correct version of schema in func.yaml

hack/install-git-server.sh, test/common/gitserver.go
Use k8s primitives pod/svc/ingress instead of knative service.
=> test: simplify func-git service

cmd/build.go, cmd/build_test.go, cmd/deploy.go, cmd/deploy_test.go, cmd/run.go, cmd/run_test.go, docs/reference/func_build.md, docs/reference/func_deploy.md, docs/reference/func_run.md, pkg/functions/function.go, pkg/oci/builder.go, pkg/oci/builder_test.go, pkg/oci/go_builder.go, pkg/oci/python_builder.go, schema/func_yaml-schema.json
- add `--base-image` flag for `build/deploy/run` for specifying the base image that function will be built upon (host builder only)
```release-note
add --base-image flag to override the base image for host builds
```
=> feat: base image flag for host builds

pkg/mcp/help.go, pkg/mcp/mcp.go, pkg/mcp/tools.go
- This PR adds the remainder of config commands (`labels` and `envs`) to the MCP server
=> mcp: adds labels and envs config tools and resources

pkg/k8s/security_context.go
Fixes a mismatch in container file permissions, surfacing during local E2E testing when switching between local, remote, and builders.
```
$ func deploy --remote --builder=pack --registry=registry.default.svc.cluster.local:5000/func -v
Error: cannot upload sources to the PVC: cannot start the pod: pod prematurely exited (output: "ERROR: cannot purge dest dir: unlinkat
/tmp/volume_mnt/source/.s2i/bin/assemble: permission denied\n", exitcode: 1)
e2e_test.go:1249: exit status 1
```
=> fix pod security context fs permissions

pkg/functions/client.go
linter failing in main https://github.com/knative/func/actions/runs/16489108500/job/46619720738#step:4:12
- Labels (map[string]string) type is unsupported in xml, exclude it
=> fix: linter reporting xml unsupported type

cmd/run.go, test/e2e/scenario_extended_flow_test.go, test/e2e/scenario_no_container_test.go
fixes #2900 
- Updated the non-JSON console output in [cmd/run.go](cci:7://file:///c:/Users/RAYYAN/Desktop/func/cmd/run.go:0:0-0:0) to use `net.JoinHostPort` for better host:port formatting
- The console output now shows both host and port in a more reliable format
The previous implementation only showed the port number in the console output, which could be confusing when running in different environments. The new implementation:
- Uses the standard library's `net.JoinHostPort` for consistent host:port formatting
The changes were tested by:
1. Running the function locally and verifying the new output format
see the output of  testing 
```txt
rayyan@rayyan-seliya:/mnt/c/Users/RAYYAN/Desktop/func/myfunction$ ../func run --address=127.0.0.1:8081 …
```
=> fix: update console output to show both host and port 

hack/cmd/update-builder/main.go
There is a bug paketo-buildpacks/packit/issues/650. This commits mitigates the issue by explicitly setting the arch.
=> Fix for arm64 buildpacks

pkg/oci/python_builder.go
related to #2964
- :bug: Host builder picks base-image with the same version of Python that is used locally.
/kind bug
```release-note
fix: host builder uses base-image with correct version of Python
```
=> fix: Python host builder base image version

pkg/mcp/help.go, pkg/mcp/mcp.go
- Adds support for remote func templates  in the `func mcp`
=> mcp: adds remote template support

pkg/mcp/mcp.go
- fix the url now that repo has been transfered
=> fix: func templates reference in mcp

hack/component-versions.json
temporarily fix components to prevent downgrading because 1.19 was marked as pre-release
=> fix-components

cmd/build.go, cmd/client.go, cmd/prompt/prompt.go, cmd/prompt/prompt_test.go, pkg/creds/credentials.go, pkg/creds/credentials_test.go, pkg/docker/pusher.go, pkg/docker/pusher_test.go, pkg/k8s/keychains.go, pkg/k8s/openshift.go, pkg/oci/pusher.go, pkg/pipelines/tekton/gitlab_int_test.go, pkg/pipelines/tekton/pipelines_int_test.go, pkg/pipelines/tekton/pipelines_provider.go
**Refactor OCI Pusher Authentication**
* Reuse `cmd/client`’s `credentialsProvider` instead of relying on the keychain
* Add interactive fallback for the pusher when no credentials are provided by a `credentialsProvider`
* Introduce additional credential loaders (ACR, GCP) for broader registry support
=> oci: refactors the auth for pusher

cmd/subscribe.go
**Changes**
- :broom: Update error message shown when `func subscribe` is run outside a function directory.
- Made the message more user-friendly and easier for beginners to understand.
- Replaced cryptic technical error with clear, actionable guidance.
- Provides context-specific information about event subscription workflow.
Fixes #3024 
```release-note
Improve error message when `func subscribe` is run outside function directory
to be more beginner-friendly and provide clear guidance on creating functions
before subscribing to events.
```
=> Improve error message when `func subscribe` is run outside function directory

cmd/invoke.go
**Changes**
- :broom: Update error message shown when `func invoke` is run outside a function directory.
- Made the message more user-friendly and easier for beginners to understand.
- Added step-by-step workflow guidance with examples for both new and existing functions.
Fixes #3017 
```release-note
Improve error message when `func invoke` is run outside function directory
to be more beginner-friendly, include step-by-step workflow guidance.
```
=> Improve error message when `func invoke` is run outside function directory

cmd/run.go, hack/component-versions.json, hack/component-versions.sh
**Changes**
- :broom: Update error message shown when `func run` is run outside a function directory.
- Made the message more user-friendly and easier for beginners to understand.
- Added step-by-step workflow guidance with examples for both new and existing functions.
- Provides context-specific guidance that `func run` runs functions locally for testing.
Fixes #3021 
```release-note
Improve error message when `func run` is run outside function directory
to be more beginner-friendly, include step-by-step workflow guidance, and 
explain that func run is used for local testing.
```
=> improve error message for func run making it more beginner friendly

cmd/create.go
- :broom: Update error message shown when `--language` flag is missing in `func create`.
- Made the message more user-friendly and easier for beginners to understand.
- Added example usage and a pointer to `func languages` for more details.
Fixes #3015
```release-note
Improve error message when `--language` flag is missing in `func create`
to be more beginner-friendly, include example usage, and point to `func languages`.
```
=> Improve error message when `--language` flag is missing in `func create`

docs/mcp-integration/integration.md
Completes the integration documentation for `func mcp` 
=> Adds docs for mcp integration

cmd/build.go, cmd/deploy.go, pkg/functions/errors.go
- :bug: Fix confusing UX when using --platform flag without S2I builder
- :broom: Implement 2-layer error system for platform restriction errors
- :gift: Add educational guidance about builder capabilities
Fixes #3061 
Implement a 2-layer error system 
- **Layer 1** (Technical): Return `ErrPlatformNotSupported` from validation in `pkg/functions/errors.go`
- **Layer 2** (CLI): Catch the error in `cmd/build.go` and `cmd/deploy.go` and wrap with user-friendly guidance
```release-note
func build and func deploy commands now provide clearer, more educational error messages when the --platform flag is used without the S2I builder, with actionable guidance and builder capability explanations.
```
=> fix the platform restriction error providing more educational guidance 
